Repository nocodb/nocodb, pull requests merged in 2022-10, with the labels that each got.

#3857 test: pg grid view share
  packages/nc-gui/components/virtual-cell/components/ListChildItems.vue
  scripts/cypress/integration/common/4f_grid_view_share.js
  scripts/cypress/integration/common/4f_pg_grid_view_share.js
  scripts/cypress/integration/test/pg-restViews.js
  scripts/cypress/support/commands.js
  scripts/cypress/support/page_objects/mainPage.js
Labels: trigger-CI

#3830 Fix : Avoid re-rendering smartsheet
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/Gallery.vue
  packages/nc-gui/components/smartsheet/Grid.vue
  packages/nc-gui/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui/components/smartsheet/sidebar/index.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
  packages/nc-gui/composables/useViews.ts
  packages/nc-gui/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui/pages/[projectType]/[projectId]/index/index.vue
  packages/nc-gui/pages/[projectType]/[projectId]/index/index/[type]/[title]/[[viewTitle]].vue
  packages/nc-gui/pages/[projectType]/form/[viewId]/index.vue
  scripts/cypress/integration/common/00_pre_configurations.js
  scripts/cypress/integration/common/4c_form_view_detailed.js
  scripts/cypress/integration/common/5a_user_role.js
  scripts/cypress/integration/common/9a_QuickTest.js
  scripts/cypress/support/commands.js
  scripts/cypress/support/page_objects/navigation.js
Labels: trigger-CI

#3914 [DOCS] Add LICENSE link to ReadMe
  README.md
Labels: 🎃 For : Hacktoberfest

#3883 refactor(nc-gui): update logo animation
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/general/NocoIcon.vue
  packages/nc-gui/pages/forgot-password.vue
  packages/nc-gui/pages/index/index/[projectId].vue
  packages/nc-gui/pages/index/index/create-external.vue
  packages/nc-gui/pages/index/index/create.vue
  packages/nc-gui/pages/signin.vue
  packages/nc-gui/pages/signup/[[token]].vue
Labels: 👓 Scope : View

#3905 test: remove wait from LTAR
  scripts/cypress/integration/common/00_pre_configurations.js
  scripts/cypress/integration/common/1b_table_column_operations.js
  scripts/cypress/integration/common/3c_lookup_column.js
  scripts/cypress/integration/common/3d_rollup_column.js
  scripts/cypress/integration/common/3e_duration_column.js
  scripts/cypress/integration/common/3f_link_to_another_record.js
  scripts/cypress/integration/common/5a_user_role.js
  scripts/cypress/integration/common/9a_QuickTest.js
  scripts/cypress/support/commands.js
  scripts/cypress/support/page_objects/mainPage.js
  scripts/cypress/support/page_objects/navigation.js
Labels: trigger-CI, Scope : Test [E2E]

#3936 fix(nc-gui): ring opacity
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/cell/attachment/Carousel.vue
  packages/nc-gui/components/cell/attachment/Modal.vue
  packages/nc-gui/components/cell/attachment/index.vue
  packages/nc-gui/components/dashboard/TreeView.vue
  packages/nc-gui/components/general/MiniSidebar.vue
  packages/nc-gui/layouts/base.vue
  packages/nc-gui/pages/[projectType]/form/[viewId]/index.vue
  packages/nc-gui/pages/forgot-password.vue
  packages/nc-gui/pages/index/index/[projectId].vue
  packages/nc-gui/pages/index/index/create.vue
  packages/nc-gui/pages/index/index/index.vue
  packages/nc-gui/pages/index/user/index.vue
  packages/nc-gui/pages/signin.vue
  packages/nc-gui/pages/signup/[[token]].vue
  packages/nc-gui/windi.config.ts
Labels: 🐛 Type: Bug

#3938 fix(nc-gui): correctly update tab after renaming table
  packages/nc-gui/components/dlg/TableRename.vue
  packages/nc-gui/components/general/TruncateText.vue
Labels: 🐛 Type: Bug

#3945 fix(nc-gui): add google auth button to signin page
  packages/nc-gui/lang/en.json
  packages/nc-gui/pages/signin.vue
  packages/nc-gui/pages/signup/[[token]].vue
Labels: 🐛 Type: Bug, 👮 Scope : Auth

#3967 test: ensure add new row tooltip disappears
  scripts/cypress/integration/common/1b_table_column_operations.js
  scripts/cypress/integration/common/3a_filter_sort_fields_operations.js
  scripts/cypress/integration/common/3e_duration_column.js
  scripts/cypress/integration/common/3f_link_to_another_record.js
  scripts/cypress/integration/common/4f_grid_view_share.js
  scripts/cypress/integration/common/4f_pg_grid_view_share.js
  scripts/cypress/integration/common/8a_webhook.js
  scripts/cypress/support/page_objects/mainPage.js
Labels: trigger-CI

#3965 fix(nc-gui): filter options by label
  packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue
Labels: 🐛 Type: Bug, 🌮 Scope : Table

#3669 feat(nc-gui): add survey mode option to share view
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components.d.ts
  packages/nc-gui/components/cell/Url.vue
  packages/nc-gui/components/cell/attachment/Carousel.vue
  packages/nc-gui/components/cell/attachment/index.vue
  packages/nc-gui/components/cell/attachment/utils.ts
  packages/nc-gui/components/general/NocoIcon.vue
  packages/nc-gui/components/general/PoweredBy.vue
  packages/nc-gui/components/smartsheet/Cell.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/Grid.vue
  packages/nc-gui/components/smartsheet/Toolbar.vue
  packages/nc-gui/components/smartsheet/VirtualCell.vue
  packages/nc-gui/components/smartsheet/sidebar/index.vue
  packages/nc-gui/components/smartsheet/toolbar/AddRow.vue
  packages/nc-gui/components/smartsheet/toolbar/Reload.vue
  packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
  packages/nc-gui/components/virtual-cell/BelongsTo.vue
  packages/nc-gui/composables/useSharedFormViewStore.ts
  packages/nc-gui/composables/useTheme/index.ts
  packages/nc-gui/context/index.ts
  packages/nc-gui/lib/types.ts
  packages/nc-gui/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui/pages/[projectType]/form/[viewId].vue
  packages/nc-gui/pages/[projectType]/form/[viewId]/index.vue
  packages/nc-gui/pages/[projectType]/form/[viewId]/index/index.vue
  packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue
  packages/nc-gui/pages/error/404.vue
  packages/nc-gui/pages/index/index.vue
  packages/nc-gui/pages/index/index/index.vue
  scripts/cypress/integration/common/4b_table_view_share.js
  scripts/cypress/support/commands.js
Labels: 🔦 Type: Feature, 👓 Scope : View, trigger-CI

#3977 Fix: Table delete - active table deletion
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
  packages/nc-gui/composables/useGridViewColumnWidth.ts
  packages/nc-gui/composables/useViewColumns.ts
  packages/nc-gui/composables/useViewFilters.ts
Labels: trigger-CI

#3978 chore(nc-gui): disable theme for non form shared views
  packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
Labels: 🧱 Type: Refactoring

#3983 Update Korean.md
  scripts/markdown/readme/languages/korean.md
Labels: 🎃 For : Hacktoberfest

#3981 test: survey form
  packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue
  scripts/cypress/integration/common/4i_survey_form.js
  scripts/cypress/integration/test/pg-restViews.js
  scripts/cypress/integration/test/restViews.js
  scripts/cypress/integration/test/xcdb-restViews.js
  scripts/cypress/support/commands.js
  scripts/cypress/support/page_objects/mainPage.js
Labels: Scope : Test [E2E]

#3980 feat(nc-gui): add animation to survey form on keypress
  packages/nc-gui/components.d.ts
  packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
  packages/nc-gui/lib/types.ts
  packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue
Labels: 🔦 Type: Feature, 👓 Scope : View

#3976 docs: nocodb-docs updates
  README.md
  packages/noco-docs/content/en/developer-resources/accessing-apis.md
  packages/noco-docs/content/en/developer-resources/webhooks.md
  packages/noco-docs/content/en/engineering/development-setup.md
  packages/noco-docs/content/en/engineering/testing.md
  packages/noco-docs/content/en/getting-started/installation.md
  packages/noco-docs/content/en/index.md
  packages/noco-docs/content/en/setup-and-usages/audit.md
  packages/noco-docs/content/en/setup-and-usages/code-snippets.md
  packages/noco-docs/content/en/setup-and-usages/dashboard.md
  packages/noco-docs/content/en/setup-and-usages/languages.md
  packages/noco-docs/content/en/setup-and-usages/meta-management.md
  packages/noco-docs/content/en/setup-and-usages/rollup.md
  packages/noco-docs/content/en/setup-and-usages/share-view.md
  packages/noco-docs/content/en/setup-and-usages/sync-schema.md
  packages/noco-docs/content/en/setup-and-usages/table-operations.md
  packages/noco-docs/content/en/setup-and-usages/team-and-auth.md
  packages/noco-docs/content/en/setup-and-usages/views.md
  packages/noco-docs/content/settings.json
  packages/noco-docs/nuxt.config.js
  packages/noco-docs/package-lock.json
  packages/noco-docs/static/favicon-128.png
  packages/noco-docs/static/favicon-16.png
  packages/noco-docs/static/favicon-32.png
  packages/noco-docs/static/favicon-64.png
  packages/noco-docs/static/icon.png
Labels: 📋 Scope : Docs

#3776 Fix: Grid view flickering on LTAR link/unlink
  packages/nc-gui/components/smartsheet/Row.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/composables/useLTARStore.ts
  packages/nc-gui/context/index.ts
Labels: trigger-CI

#4025 feat: automatically create a new row on navigating next within last row
  packages/nc-gui/components/smartsheet/Cell.vue
  packages/nc-gui/components/smartsheet/Grid.vue
Labels: 👀 Status: In Review

#4027 fix(nc-gui): prevent gallery cover img error
  packages/nc-gui/components/smartsheet/Gallery.vue
  packages/nc-gui/components/smartsheet/Kanban.vue
Labels: 🐛 Type: Bug, 👓 Scope : View

#4026 fix(nc-gui): use column label or title for error msg in form view
  packages/nc-gui/composables/useSharedFormViewStore.ts
  packages/nc-gui/lang/en.json
Labels: 🐛 Type: Bug, 👀 Status: In Review, 👓 Scope : View

#3370 fix: tab level state
  packages/nc-gui/components/cell/MultiSelect.vue
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/composables/useTabs.ts
  packages/nc-gui/composables/useViewFilters.ts
  packages/nc-gui/composables/useViewSorts.ts
  packages/nc-gui/lib/types.ts
Labels: 🐛 Type: Bug, 🛑 Status: Do Not Merge

#4030 fix(nc-gui): remove `useMetas` from watch cb
  packages/nc-gui/components/smartsheet/Grid.vue
Labels: 🐛 Type: Bug, 👓 Scope : View

#4052 fix(nc-gui): correct input style padding for form views
  packages/nc-gui/components/cell/Duration.vue
  packages/nc-gui/components/cell/Percent.vue
  packages/nc-gui/components/cell/Text.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue
Labels: 🐛 Type: Bug

#4054 fix(nc-gui): apply distinct key on page
  packages/nc-gui/pages/[projectType]/[projectId]/index/index.vue
Labels: 🐛 Type: Bug, 👓 Scope : View

#4057 refactor(nc-gui): add default nocodb theme color to picker
  packages/nc-gui/composables/useTheme/index.ts
  packages/nc-gui/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui/utils/colorsUtils.ts
Labels: 🧱 Type: Refactoring, 👓 Scope : View

#4062 fix(nc-gui): remove `useMetas` from cb fn
  packages/nc-gui/components/smartsheet/Cell.vue
  packages/nc-gui/components/smartsheet/Grid.vue
  packages/nc-gui/composables/useViewData.ts
Labels: 🐛 Type: Bug, 👓 Scope : View

#4058 feat(nc-gui): add ping animation to logo on click
  packages/nc-gui/components/general/NocoIcon.vue
  packages/nc-gui/components/general/PoweredBy.vue
Labels: 🔦 Type: Feature

#3931 chore(nc-gui): fix types and cleanup unused vars
  packages/nc-gui/components/cell/Decimal.vue
  packages/nc-gui/components/cell/Float.vue
  packages/nc-gui/components/cell/Integer.vue
  packages/nc-gui/components/cell/MultiSelect.vue
  packages/nc-gui/components/cell/Percent.vue
  packages/nc-gui/components/general/ShareBaseButton.vue
  packages/nc-gui/components/shared-view/Grid.vue
  packages/nc-gui/components/smartsheet/sidebar/toolbar/DebugMeta.vue
  packages/nc-gui/components/smartsheet/sidebar/toolbar/DeleteTable.vue
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
  packages/nc-gui/lib/types.ts
  packages/nc-gui/utils/viewUtils.ts
Labels: 🧱 Type: Refactoring

#4066 chore(nc-gui): update to latest vue flow pkg
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/erd/Flow.vue
  packages/nc-gui/components/erd/RelationEdge.vue
  packages/nc-gui/components/erd/TableNode.vue
  packages/nc-gui/components/erd/View.vue
  packages/nc-gui/components/erd/utils.ts
  packages/nc-gui/package-lock.json
  packages/nc-gui/package.json
Labels: 🐛 Type: Bug, 🧱 Type: Refactoring

#4121 refactor(nc-gui): extend tooltip toggle conditions
  packages/nc-gui/components/dashboard/TreeView.vue
  packages/nc-gui/components/general/Tooltip.vue
Labels: 🧱 Type: Refactoring

#4071 feat(nc-gui): add color scale to erd view
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/dashboard/settings/AppStore.vue
  packages/nc-gui/components/dashboard/settings/Erd.vue
  packages/nc-gui/components/erd/ConfigPanel.vue
  packages/nc-gui/components/erd/Flow.vue
  packages/nc-gui/components/erd/HistogramPanel.vue
  packages/nc-gui/components/erd/RelationEdge.vue
  packages/nc-gui/components/erd/TableNode.vue
  packages/nc-gui/components/erd/View.vue
  packages/nc-gui/components/erd/utils.ts
  packages/nc-gui/components/general/Tooltip.vue
  packages/nc-gui/components/smartsheet/toolbar/Erd.vue
  packages/nc-gui/package-lock.json
  packages/nc-gui/package.json
Labels: 🔦 Type: Feature, 👓 Scope : View, trigger-CI

#4101 feat: better scroll for borders and sticky header
  packages/nc-gui/components/smartsheet/Grid.vue
  packages/nc-gui/composables/useMultiSelect/index.ts
Labels: 🔦 Type: Feature, 🌮 Scope : Table

#4114 fix: handle currency cell manual save
  packages/nc-gui/components/cell/Currency.vue
  packages/nc-gui/components/smartsheet/Cell.vue
  packages/nc-gui/composables/useColumn.ts
Labels: 🐛 Type: Bug, 👀 Status: In Review

#4149 fix(nc-gui): use `TableDataCell` component to set cell refs
  packages/nc-gui/components/smartsheet/Grid.vue
  packages/nc-gui/components/smartsheet/Row.vue
  packages/nc-gui/components/smartsheet/TableDataCell.vue
  packages/nc-gui/composables/useSmartsheetStore.ts
Labels: 🐛 Type: Bug

#4141 fix(nc-gui): add detached expanded form
  packages/nc-gui/components/cell/DatePicker.vue
  packages/nc-gui/components/cell/DateTimePicker.vue
  packages/nc-gui/components/cell/Text.vue
  packages/nc-gui/components/cell/TimePicker.vue
  packages/nc-gui/components/cell/YearPicker.vue
  packages/nc-gui/components/cell/attachment/utils.ts
  packages/nc-gui/components/shared-view/Gallery.vue
  packages/nc-gui/components/shared-view/Grid.vue
  packages/nc-gui/components/shared-view/Kanban.vue
  packages/nc-gui/components/smartsheet/Cell.vue
  packages/nc-gui/components/smartsheet/Gallery.vue
  packages/nc-gui/components/smartsheet/Grid.vue
  packages/nc-gui/components/smartsheet/Kanban.vue
  packages/nc-gui/components/smartsheet/expanded-form/Detached.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/components/virtual-cell/BelongsTo.vue
  packages/nc-gui/components/virtual-cell/HasMany.vue
  packages/nc-gui/components/virtual-cell/Lookup.vue
  packages/nc-gui/components/virtual-cell/ManyToMany.vue
  packages/nc-gui/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui/components/virtual-cell/components/ListChildItems.vue
  packages/nc-gui/composables/useDialog/index.ts
  packages/nc-gui/composables/useExpandedFormDetached/index.ts
  packages/nc-gui/composables/useRoles/index.ts
  packages/nc-gui/context/index.ts
  packages/nc-gui/layouts/base.vue
  packages/nc-gui/pages/[projectType]/view/[viewId].vue
  scripts/cypress/integration/common/1a_table_operations.js
  scripts/cypress/integration/common/1b_table_column_operations.js
  scripts/cypress/integration/common/2b_table_with_m2m_column.js
Labels: 🐛 Type: Bug, 👓 Scope : View

#4135 feat: import optimization
  packages/nc-gui/.eslintrc.js
  packages/nc-gui/components/dlg/QuickImport.vue
  packages/nc-gui/components/smartsheet/toolbar/MoreActions.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewActions.vue
  packages/nc-gui/components/template/Editor.vue
  packages/nc-gui/lib/types.ts
  packages/nc-gui/utils/dateTimeUtils.ts
  packages/nc-gui/utils/parsers/CSVTemplateAdapter.ts
  packages/nc-gui/utils/parsers/ExcelTemplateAdapter.ts
  packages/nc-gui/utils/parsers/ExcelUrlTemplateAdapter.ts
  packages/nc-gui/utils/parsers/JSONTemplateAdapter.ts
  packages/nc-gui/utils/parsers/JSONUrlTemplateAdapter.ts
  packages/nc-gui/utils/parsers/parserHelpers.ts
  packages/noco-docs/content/en/setup-and-usages/table-operations.md
Labels: 👀 Status: Review Needed

#4179 fix(nc-gui): checkbox unclickable
  packages/nc-gui/components/cell/Checkbox.vue
Labels: 🐛 Type: Bug

#4099 fix(nc-gui): dark mode styles for longtext field in form view
  packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
  packages/nc-gui/composables/useMultiSelect/index.ts
  packages/nc-gui/composables/useViewData.ts
  packages/nc-gui/pages/[projectType]/form/[viewId]/index.vue
  packages/nc-gui/pages/[projectType]/form/[viewId]/index/survey.vue
Labels: 🐛 Type: Bug, 👓 Scope : View
