Repository nocodb/nocodb, pull requests merged in 2022-11, with the labels that each got.

#3570 feat: upgrade knex
  .github/workflows/release-executables.yml
  .github/workflows/release-timely-executables.yml
  packages/nc-gui/lib/constants.ts
  packages/nocodb/Dockerfile
  packages/nocodb/package-lock.json
  packages/nocodb/package.json
  packages/nocodb/src/interface/config.ts
  packages/nocodb/src/lib/db/sql-client/lib/KnexClient.ts
  packages/nocodb/src/lib/db/sql-client/lib/mssql/MssqlClient.ts
  packages/nocodb/src/lib/db/sql-client/lib/pg/PgClient.ts
  packages/nocodb/src/lib/db/sql-client/lib/sqlite/SqliteClient.ts
  packages/nocodb/src/lib/db/sql-data-mapper/lib/BaseModel.ts
  packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSql.ts
  packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/BaseModelSqlv2.ts
  packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/CustomKnex.ts
  packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/conditionV2.ts
  packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/genRollupSelect.ts
  packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/genRollupSelectv2.ts
  packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/mapFunctionName.ts
  packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/sortV2.ts
  packages/nocodb/src/lib/db/sql-mgr/v2/SqlMgrv2Trans.ts
  packages/nocodb/src/lib/meta/api/dataApis/dataAliasApis.ts
  packages/nocodb/src/lib/meta/api/publicApis/publicDataApis.ts
  packages/nocodb/src/lib/migrations/v1/nc_002_add_m2m.ts
  packages/nocodb/src/lib/migrations/v1/nc_003_add_fkn_column.ts
  packages/nocodb/src/lib/migrations/v1/nc_004_add_view_type_column.ts
  packages/nocodb/src/lib/migrations/v1/nc_005_add_view_name_column.ts
  packages/nocodb/src/lib/migrations/v1/nc_006_alter_nc_shared_views.ts
  packages/nocodb/src/lib/migrations/v1/nc_007_alter_nc_shared_views_1.ts
  packages/nocodb/src/lib/migrations/v1/nc_008_add_nc_shared_bases.ts
  packages/nocodb/src/lib/migrations/v1/nc_009_add_model_order.ts
  packages/nocodb/src/lib/migrations/v1/nc_010_add_parent_title_column.ts
  packages/nocodb/src/lib/migrations/v1/nc_011_remove_old_ses_plugin.ts
  packages/nocodb/src/lib/migrations/v2/nc_012_alter_column_data_types.ts
  packages/nocodb/src/lib/migrations/v2/nc_013_sync_source.ts
  packages/nocodb/src/lib/migrations/v2/nc_014_alter_column_data_types.ts
  packages/nocodb/src/lib/migrations/v2/nc_015_add_meta_col_in_column_table.ts
  packages/nocodb/src/lib/migrations/v2/nc_016_alter_hooklog_payload_types.ts
  packages/nocodb/src/lib/migrations/v2/nc_017_add_user_token_version_column.ts
  packages/nocodb/src/lib/migrations/v2/nc_018_add_meta_in_view.ts
  packages/nocodb/src/lib/migrations/v2/nc_019_add_meta_in_meta_tables.ts
  packages/nocodb/src/lib/migrations/v2/nc_020_kanban_view.ts
  packages/nocodb/src/lib/services/test/TestResetService/index.ts
  packages/nocodb/src/lib/services/test/TestResetService/resetMetaSakilaSqliteProject.ts
  packages/nocodb/src/lib/services/test/TestResetService/resetMysqlSakilaProject.ts
  packages/nocodb/src/lib/services/test/TestResetService/resetPgSakilaProject.ts
  packages/nocodb/src/lib/utils/common/NcConnectionMgr.ts
  packages/nocodb/tests/unit/TestDbMngr.ts
Labels: 👀 Status: In Review

#4289 fix(nc-gui): overlapping edge labels
  packages/nc-gui/components/erd/Flow.vue
  packages/nc-gui/components/erd/RelationEdge.vue
  packages/nc-gui/package-lock.json
  packages/nc-gui/package.json
  scripts/playwright/pages/Dashboard/commonBase/Erd.ts
Labels: 🐛 Type: Bug

#4182 Save and restore last opened view
  packages/nc-gui/components/smartsheet/sidebar/index.vue
  packages/nc-gui/composables/useProject.ts
  scripts/cypress/integration/common/4c_form_view_detailed.js
Labels: 🔦 Type: Feature

#4306 fix(nc-gui): ref access in auth middleware
  packages/nc-gui/middleware/auth.global.ts
Labels: 🐛 Type: Bug

#4222 Fix: Grid cell - keyboard shortcut issues
  packages/nc-gui/components.d.ts
  packages/nc-gui/components/cell/Checkbox.vue
  packages/nc-gui/components/cell/Currency.vue
  packages/nc-gui/components/cell/DatePicker.vue
  packages/nc-gui/components/cell/DateTimePicker.vue
  packages/nc-gui/components/cell/Decimal.vue
  packages/nc-gui/components/cell/Duration.vue
  packages/nc-gui/components/cell/Email.vue
  packages/nc-gui/components/cell/Float.vue
  packages/nc-gui/components/cell/Integer.vue
  packages/nc-gui/components/cell/MultiSelect.vue
  packages/nc-gui/components/cell/Percent.vue
  packages/nc-gui/components/cell/Rating.vue
  packages/nc-gui/components/cell/SingleSelect.vue
  packages/nc-gui/components/cell/Text.vue
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/cell/TimePicker.vue
  packages/nc-gui/components/cell/Url.vue
  packages/nc-gui/components/cell/YearPicker.vue
  packages/nc-gui/components/cell/attachment/index.vue
  packages/nc-gui/components/smartsheet/Cell.vue
  packages/nc-gui/components/smartsheet/Grid.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/virtual-cell/BelongsTo.vue
  packages/nc-gui/components/virtual-cell/Formula.vue
  packages/nc-gui/components/virtual-cell/HasMany.vue
  packages/nc-gui/components/virtual-cell/Lookup.vue
  packages/nc-gui/components/virtual-cell/ManyToMany.vue
  packages/nc-gui/components/virtual-cell/Rollup.vue
  packages/nc-gui/components/virtual-cell/components/ListItems.vue
  packages/nc-gui/composables/useMultiSelect/index.ts
  packages/nc-gui/composables/useSelectedCellKeyupListener/index.ts
  packages/nc-gui/composables/useTable.ts
  packages/nc-gui/utils/browserUtils.ts
  packages/nc-gui/utils/columnUtils.ts
  packages/nc-gui/utils/index.ts
  packages/nocodb/src/lib/Noco.ts
  packages/nocodb/src/lib/version-upgrader/NcUpgrader.ts
  packages/nocodb/src/lib/version-upgrader/ncDataTypesUpgrader.ts
  packages/nocodb/src/run/docker.ts
  packages/nocodb/src/run/dockerRunMysql.ts
  packages/nocodb/src/run/dockerRunPG.ts
  packages/nocodb/src/run/dockerRunPG_CyQuick.ts
  tests/playwright/pages/Dashboard/common/Cell/SelectOptionCell.ts
Labels: trigger-CI

#4390 fix(nc-gui): apply ltr/rtl direction on language switch
  packages/nc-gui/components/general/language/Menu.vue
  packages/nc-gui/components/smartsheet/toolbar/ShareView.vue
  packages/nc-gui/lib/types.ts
  packages/nc-gui/pages/[projectType]/form/[viewId].vue
  packages/nc-gui/plugins/a.i18n.ts
  packages/nc-gui/utils/viewUtils.ts
Labels: 🐛 Type: Bug

#3847 refactor(nc-gui): reduce computed values generated by cells
  packages/nc-gui/components.d.ts
  packages/nc-gui/components/cell/Email.vue
  packages/nc-gui/components/dashboard/TreeView.vue
  packages/nc-gui/components/smartsheet/Cell.vue
  packages/nc-gui/components/smartsheet/VirtualCell.vue
  packages/nc-gui/components/smartsheet/header/CellIcon.ts
  packages/nc-gui/components/smartsheet/header/CellIcon.vue
  packages/nc-gui/components/smartsheet/header/VirtualCell.vue
  packages/nc-gui/components/smartsheet/header/VirtualCellIcon.ts
  packages/nc-gui/components/tabs/auth/user-management/UsersModal.vue
  packages/nc-gui/components/virtual-cell/Lookup.vue
  packages/nc-gui/composables/useColumn.ts
  packages/nc-gui/composables/useProject.ts
  packages/nc-gui/composables/useSmartsheetRowStore.ts
  packages/nc-gui/composables/useVirtualCell.ts
  packages/nc-gui/pages/forgot-password.vue
  packages/nc-gui/pages/signin.vue
  packages/nc-gui/pages/signup/[[token]].vue
  packages/nc-gui/utils/cell.ts
  packages/nc-gui/utils/parsers/parserHelpers.ts
  packages/nc-gui/utils/validation.ts
  packages/nc-gui/utils/virtualCell.ts
Labels: 🛑 Status: Do Not Merge, 🧱 Type: Refactoring, 👓 Scope : View

#4431 Fix: Re-render page if navigation error thrown
  packages/nc-gui/app.vue
  packages/nocodb/src/lib/meta/api/swagger/redocHtml.ts
Labels: trigger-CI

#4521 Added stress testing of newly added test to CI
  .github/workflows/ci-cd.yml
  .github/workflows/playwright-test-workflow.yml
  tests/playwright/.gitignore
  tests/playwright/scripts/stressTestNewlyAddedTest.js
Labels: trigger-CI

#4538 fix(test): Made default file field size limit to 20MB and is configurable using NC_ATTACHMENT_FIELD_SIZE env variable
  packages/noco-docs/content/en/getting-started/installation.md
  packages/nocodb/src/lib/constants/index.ts
  packages/nocodb/src/lib/meta/NcMetaMgr.ts
  packages/nocodb/src/lib/meta/NcMetaMgrv2.ts
  packages/nocodb/src/lib/meta/api/attachmentApis.ts
  packages/nocodb/src/lib/meta/api/publicApis/publicDataApis.ts
  packages/nocodb/src/lib/services/test/TestResetService/resetMysqlSakilaProject.ts
  tests/playwright/fixtures/sampleFiles/sampleImage.jpeg
  tests/playwright/pages/Dashboard/Form/index.ts
  tests/playwright/pages/SharedForm/index.ts
  tests/playwright/tests/columnAttachments.spec.ts
  tests/playwright/tests/viewForm.spec.ts
Labels: trigger-CI
