Repository nocodb/nocodb, pull requests merged in 2022-09, with the labels that each got.

#3428 fix(gui-v2): check import file mime types
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/index.vue
Labels: Scope: vue3

#3393 fix(gui-v2): pagination logic
  packages/nc-gui-v2/composables/useViewData.ts
Labels: Scope: vue3

#3439 fix(gui-v2): missing data in quick import after renaming
  packages/nc-gui-v2/components/template/Editor.vue
Labels: Scope: vue3

#3460 fix(gui-v2): add missing allowCSVDownload condition
  packages/nc-gui-v2/components/smartsheet/Toolbar.vue
Labels: Scope: vue3

#3475 fix(gui-v2): add missing isUIAllowed for UserManagement & ApiTokenManagement
  packages/nc-gui-v2/components/tabs/Auth.vue
Labels: Scope: vue3

#3484 fix(gui-v2): skip system LTAR columns
  packages/nc-gui-v2/components/smartsheet-column/FormulaOptions.vue
Labels: Scope: vue3

#3489 fix(gui-v2): set metas with updated model after renaming tables
  packages/nc-gui-v2/components/dlg/TableRename.vue
Labels: Scope: vue3

#3481 fix: theme palette
  packages/nc-gui-v2/components/general/ChromeWrapper.vue
  packages/nc-gui-v2/components/general/ColorPicker.vue
  packages/nc-gui-v2/composables/useProject.ts
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui-v2/pages/index/index/index.vue
Labels: Scope: vue3

#3496 fix(gui-v2): re-find cell ref for attachment dropzone on order change
  packages/nc-gui-v2/components/cell/attachment/index.vue
Labels: Scope: vue3

#3498 fix: block attempts to edit primary key column
  packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
Labels: Scope: vue3

#3493 fix(gui-v2): add reloadEventHook.trigger() to get the latest localColumn value
  packages/nc-gui-v2/components/smartsheet/Form.vue
  packages/nc-gui-v2/composables/useViewColumns.ts
Labels: Scope: vue3

#3492 fix(gui-v2): avoid watch logic to trigger even after signout
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
  packages/nc-gui-v2/composables/useViewColumns.ts
Labels: Scope: vue3

#3501 fix: gallery view
  packages/nc-gui-v2/components/cell/attachment/index.vue
  packages/nc-gui-v2/components/smartsheet/Form.vue
  packages/nc-gui-v2/components/smartsheet/Gallery.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/context/index.ts
Labels: Scope: vue3

#3502 feat: implement TruncateText component
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/general/TruncateText.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ViewActions.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index.vue
Labels: Scope: vue3

#3577 feat: added a form for creating tokens
  packages/nc-gui/components/tabs/auth/ApiTokenManagement.vue
Labels: Scope: vue3

#3602 fix(nc-gui): lazy load languages for initial load perf
  packages/nc-gui/components/general/language/Menu.vue
  packages/nc-gui/components/general/language/index.vue
  packages/nc-gui/composables/useGlobal/state.ts
  packages/nc-gui/layouts/base.vue
  packages/nc-gui/lib/types.ts
  packages/nc-gui/nuxt-shim.d.ts
  packages/nc-gui/nuxt.config.ts
  packages/nc-gui/package-lock.json
  packages/nc-gui/package.json
  packages/nc-gui/pages/signin.vue
  packages/nc-gui/plugins/a.i18n.ts
  packages/nc-gui/plugins/state.ts
Labels: Scope: vue3

#3630 feat(nc-gui): add web types for directives
  packages/nc-gui/components/smartsheet-toolbar/ShareView.vue
  packages/nc-gui/package.json
  packages/nc-gui/web-types.json
Labels: Scope: vue3

#3642 fix(nc-gui): checkbox cell unselectable
  packages/nc-gui/components/cell/Checkbox.vue
Labels: Type: Bug, Product : View

#3637 fix(nc-gui): project state not properly reset
  packages/nc-gui/composables/useProject.ts
  packages/nc-gui/composables/useViewData.ts
  packages/nc-gui/lib/types.ts
  packages/nc-gui/nuxt-shim.d.ts
  packages/nc-gui/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui/pages/[projectType]/[projectId]/index/index.vue
  packages/nc-gui/pages/[projectType]/[projectId]/index/index/[type]/[title]/[[viewTitle]].vue
  packages/nc-gui/pages/index/index/index.vue
Labels: Type: Bug, Type: In Development, Product : View

#3660 fix(nc-gui): right sidebar collapse not working
  packages/nc-gui/components/smartsheet/sidebar/index.vue
  packages/nc-gui/components/smartsheet/sidebar/toolbar/ToggleDrawer.vue
  packages/nc-gui/components/smartsheet/sidebar/toolbar/index.vue
  packages/nc-gui/composables/useSidebar/index.ts
Labels: Type: Bug, Product : View

#3664 feat(nc-gui): store sidebar states separately by id
  packages/nc-gui/components/general/MiniSidebar.vue
  packages/nc-gui/components/smartsheet/Toolbar.vue
  packages/nc-gui/components/smartsheet/sidebar/index.vue
  packages/nc-gui/components/smartsheet/sidebar/toolbar/DeleteTable.vue
  packages/nc-gui/components/smartsheet/sidebar/toolbar/ToggleDrawer.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/composables/useSidebar/index.ts
  packages/nc-gui/layouts/default.vue
  packages/nc-gui/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui/pages/[projectType]/[projectId]/index/index.vue
  packages/nc-gui/pages/[projectType]/form/[viewId].vue
  packages/nc-gui/pages/index/index/[projectId].vue
  packages/nc-gui/pages/index/index/create-external.vue
  packages/nc-gui/pages/index/index/create.vue
  packages/nc-gui/pages/index/index/index.vue
  packages/nc-gui/pages/signin.vue
  packages/nc-gui/utils/memStorage.ts
Labels: Type: Feature, Product : View

#3641 fix(nc-gui): remove injection usage in callback
  packages/nc-gui/components/smartsheet-column/EditOrAdd.vue
  packages/nc-gui/composables/useColumnCreateStore.ts
  packages/nc-gui/composables/useSmartsheetRowStore.ts
Labels: Type: Bug, Type: In Development, Product : View

#3646 refactor(nc-gui): hide loading spinner when reloading from webhook filters
  packages/nc-gui/components/smartsheet-toolbar/ColumnFilter.vue
  packages/nc-gui/components/smartsheet/Grid.vue
  packages/nc-gui/components/webhook/Drawer.vue
  packages/nc-gui/components/webhook/Editor.vue
  packages/nc-gui/composables/useViewFilters.ts
  packages/nc-gui/context/index.ts
Labels: Type: Refactoring, Product : View

#3701 fix(nc-gui): reset roles on app load
  packages/nc-gui/composables/useGlobal/index.ts
  packages/nc-gui/composables/useGlobal/state.ts
  packages/nc-gui/composables/useGlobal/types.ts
Labels: Type: Bug, Product : View

#3760 fix: import- self link, empty options
  packages/nocodb/package.json
  packages/nocodb/src/lib/meta/api/sync/helpers/job.ts
  packages/nocodb/src/lib/meta/api/sync/helpers/readAndProcessData.ts
Labels: Type: AT Import

#3703 chore(nc-gui): cleanup types and unused code
  packages/nc-gui/.eslintrc.js
  packages/nc-gui/app.vue
  packages/nc-gui/components/general/PreviewAs.vue
  packages/nc-gui/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui/components/smartsheet/sidebar/RenameableMenuItem.vue
  packages/nc-gui/components/smartsheet/sidebar/index.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/composables/index.ts
  packages/nc-gui/composables/useAttachment.ts
  packages/nc-gui/composables/useGlobal/index.ts
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/composables/useProject.ts
  packages/nc-gui/composables/useRoles/index.ts
  packages/nc-gui/composables/useSharedFormViewStore.ts
  packages/nc-gui/composables/useSidebar/index.ts
  packages/nc-gui/composables/useTheme/index.ts
  packages/nc-gui/composables/useUIPermission/index.ts
  packages/nc-gui/composables/useUIPermission/rolePermissions.ts
  packages/nc-gui/layouts/default.vue
  packages/nc-gui/lib/enums.ts
  packages/nc-gui/lib/types.ts
  packages/nc-gui/plugins/tele.ts
  packages/nc-gui/utils/index.ts
Labels: Type: Refactoring, Product : View

#3773 test(misc): re-alignment & optimizations
  .github/workflows/ci-cd.yml
  scripts/cypress/cypress.json
  scripts/cypress/integration/common/00_pre_configurations.js
  scripts/cypress/integration/common/4e_form_view_share.js
  scripts/cypress/integration/common/4f_grid_view_share.js
  scripts/cypress/integration/common/6d_language_validation.js
  scripts/cypress/integration/common/6e_project_operations.js
  scripts/cypress/integration/common/6f_attachments.js
  scripts/cypress/integration/common/6g_base_share.js
  scripts/cypress/integration/common/8a_webhook.js
  scripts/cypress/integration/test/db-independent.js
  scripts/cypress/integration/test/pg-restMisc.js
  scripts/cypress/integration/test/restMisc.js
  scripts/cypress/integration/test/xcdb-restMisc.js
  scripts/cypress/support/commands.js
  scripts/cypress/support/page_objects/navigation.js
Labels: Status: Do Not Merge

#3798 test(expanded-form): wait for page load
  scripts/cypress/integration/common/4g_table_view_expanded_form.js
Labels: 🛑 Status: Do Not Merge

#3797 test(misc): wait clean up
  packages/nc-gui/components/smartsheet-header/Menu.vue
  scripts/cypress/integration/common/5a_user_role.js
  scripts/cypress/integration/common/6f_attachments.js
  scripts/cypress/integration/common/6g_base_share.js
  scripts/cypress/integration/common/7a_create_project_from_excel.js
  scripts/cypress/integration/common/8a_webhook.js
  scripts/cypress/integration/common/9a_QuickTest.js
  scripts/cypress/integration/spec/roleValidation.spec.js
  scripts/cypress/support/commands.js
  scripts/cypress/support/page_objects/mainPage.js
Labels: 🛑 Status: Do Not Merge

#3795 fix(nc-gui): adding max-width-250px to sharedViewList password
  packages/nc-gui/components/smartsheet-toolbar/SharedViewList.vue
Labels: 👓 Scope : View

#3807 test: cy wait cleanup
  scripts/cypress/integration/common/00_pre_configurations.js
  scripts/cypress/integration/common/1a_table_operations.js
  scripts/cypress/integration/common/1b_table_column_operations.js
  scripts/cypress/integration/common/2b_table_with_m2m_column.js
  scripts/cypress/integration/common/3a_filter_sort_fields_operations.js
  scripts/cypress/integration/common/3c_lookup_column.js
  scripts/cypress/integration/common/3d_rollup_column.js
  scripts/cypress/integration/common/3e_duration_column.js
  scripts/cypress/integration/common/3f_link_to_another_record.js
  scripts/cypress/integration/common/4a_table_view_grid_gallery_form.js
  scripts/cypress/integration/common/4c_form_view_detailed.js
  scripts/cypress/integration/common/4e_form_view_share.js
  scripts/cypress/integration/common/4f_pg_grid_view_share.js
  scripts/cypress/integration/common/5a_user_role.js
  scripts/cypress/integration/common/5b_preview_role.js
  scripts/cypress/integration/common/6f_attachments.js
  scripts/cypress/integration/common/6g_base_share.js
  scripts/cypress/integration/common/7a_create_project_from_excel.js
  scripts/cypress/integration/common/8a_webhook.js
  scripts/cypress/integration/spec/roleValidation.spec.js
  scripts/cypress/integration/test/explicitLogin.js
  scripts/cypress/support/commands.js
  scripts/cypress/support/page_objects/mainPage.js
  scripts/cypress/support/page_objects/navigation.js
Labels: 🛑 Status: Do Not Merge

#3809 fix(nc-gui): adding min-w-4 to icons in gallery view drawer
  packages/nc-gui/components/smartsheet/expanded-form/Header.vue
Labels: 🐛 Type: Bug, 👓 Scope : View

#3819 feat(nc-gui): add LanguageAlias enum
  packages/nc-gui/lib/enums.ts
  packages/nc-gui/plugins/a.i18n.ts
  packages/nc-gui/plugins/state.ts
Labels: 🐛 Type: Bug, 🔦 Type: Feature, 👓 Scope : View

#3810 feat(nc-gui): shared-view postmessage on locationchange
  packages/nc-gui/layouts/shared-view.vue
Labels: 🔦 Type: Feature, 👓 Scope : View

#3816 feat(nc-gui): select multiple rows and copy
  packages/nc-gui/components/smartsheet/Grid.vue
  packages/nc-gui/components/smartsheet/toolbar/SharedViewList.vue
  packages/nc-gui/composables/useMultiSelect/index.ts
Labels: 🔦 Type: Feature, 👓 Scope : View

#3846 test: enable preview mode tests
  packages/nc-gui/components/general/PreviewAs.vue
  scripts/cypress/integration/common/5b_preview_role.js
  scripts/cypress/integration/common/5c_super_user_role.js
  scripts/cypress/integration/test/pg-restRoles.js
  scripts/cypress/integration/test/restRoles.js
  scripts/cypress/integration/test/xcdb-restRoles.js
Labels: trigger-CI

#3845 test: enable duration column tests
  scripts/cypress/integration/common/3e_duration_column.js
  scripts/cypress/integration/test/pg-restTableOps.js
  scripts/cypress/integration/test/restTableOps.js
  scripts/cypress/integration/test/xcdb-restTableOps.js
Labels: trigger-CI

#3844 test: enable LTAR tests in SQLite, PG
  scripts/cypress/integration/test/pg-restTableOps.js
  scripts/cypress/integration/test/xcdb-restTableOps.js
Labels: trigger-CI

#3862 test: update intercept message during shared base load
  scripts/cypress/integration/common/6g_base_share.js
Labels: trigger-CI
