Repository nocodb/nocodb, pull requests merged in 2022-08, with the labels that each got.

#2908 feat(gui-v2): Formula Cell
  packages/nc-gui-v2/components/virtual-cell/Formula.vue
  packages/nc-gui-v2/utils/dateTimeUtils.ts
Labels: Scope: vue3

#2854 User management and API Token Management added
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/dashboard/settings/SettingsModal.vue
  packages/nc-gui-v2/components/tabs/Auth.vue
  packages/nc-gui-v2/components/tabs/auth/ApiTokenManagement.vue
  packages/nc-gui-v2/components/tabs/auth/UserManagement.vue
  packages/nc-gui-v2/components/tabs/auth/user-management/FeedbackForm.vue
  packages/nc-gui-v2/components/tabs/auth/user-management/ShareBase.vue
  packages/nc-gui-v2/components/tabs/auth/user-management/UsersModal.vue
  packages/nc-gui-v2/composables/useGlobalState/index.ts
  packages/nc-gui-v2/composables/useGlobalState/initialFeedBackForm.ts
  packages/nc-gui-v2/lib/enums.ts
  packages/nc-gui-v2/lib/types.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/nc/[projectId]/index.vue
  packages/nc-gui-v2/pages/nc/[projectId]/index/index/auth.vue
  packages/nc-gui-v2/plugins/api.ts
  packages/nc-gui-v2/plugins/initializeFeedbackForm.ts
  packages/nc-gui-v2/utils/dateTimeUtils.ts
  packages/nc-gui-v2/utils/urlUtils.ts
  packages/nc-gui-v2/utils/userUtils.ts
Labels: Scope: vue3

#2837 feat(gui-v2): add views sidebar
  packages/nc-gui-v2/.eslintrc.js
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/assets/img/discourse-icon.png
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/dlg/ViewCreate.vue
  packages/nc-gui-v2/components/dlg/ViewDelete.vue
  packages/nc-gui-v2/components/general/FlippingCard.vue
  packages/nc-gui-v2/components/general/Social.vue
  packages/nc-gui-v2/components/general/Sponsors.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ToggleDrawer.vue
  packages/nc-gui-v2/components/smartsheet/Pagination.vue
  packages/nc-gui-v2/components/smartsheet/Sidebar.vue
  packages/nc-gui-v2/components/smartsheet/Toolbar.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/composables/useApi/index.ts
  packages/nc-gui-v2/composables/useApi/interceptors.ts
  packages/nc-gui-v2/composables/useGlobalState/index.ts
  packages/nc-gui-v2/composables/useTabs.ts
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/composables/useViewCreate.ts
  packages/nc-gui-v2/composables/useViews.ts
  packages/nc-gui-v2/context/index.ts
  packages/nc-gui-v2/layouts/default.vue
  packages/nc-gui-v2/lib/index.ts
  packages/nc-gui-v2/nuxt-shim.d.ts
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/forgot-password.vue
  packages/nc-gui-v2/pages/index/user/index/index.vue
  packages/nc-gui-v2/pages/nc/[projectId]/index.vue
  packages/nc-gui-v2/pages/nc/[projectId]/index/index.vue
  packages/nc-gui-v2/pages/project/index.vue
  packages/nc-gui-v2/pages/project/index/create-external.vue
  packages/nc-gui-v2/pages/signin.vue
  packages/nc-gui-v2/pages/signup.vue
  packages/nc-gui-v2/plugins/ant.ts
  packages/nc-gui-v2/plugins/api.ts
  packages/nc-gui-v2/tsconfig.json
  packages/nc-gui-v2/utils/generateName.ts
  packages/nc-gui-v2/utils/index.ts
  packages/nc-gui-v2/utils/projectCreateUtils.ts
Labels: Scope: vue3

#2892 refactor(gui-v2): fix right sidebar layout
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components/dashboard/TabView.vue
  packages/nc-gui-v2/components/dlg/ViewCreate.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/AddRow.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/DeleteTable.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/LockMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/Reload.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ShareView.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ToggleDrawer.vue
  packages/nc-gui-v2/components/smartsheet/Toolbar.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/Toolbar.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/composables/useApi.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/pages/nc/[projectId]/index/index.vue
Labels: Scope: vue3

#2932 fix(gui-v2): use promise reject when returning api error
  packages/nc-gui-v2/composables/useApi/index.ts
  packages/nc-gui-v2/plugins/state.ts
Labels: Scope: vue3

#2933 feat(gui-v2): add `dayjs` plugin file
  packages/nc-gui-v2/plugins/a.dayjs.ts
  packages/nc-gui-v2/utils/dateTimeUtils.ts
Labels: Scope: vue3

#2935 chore(gui-v2): add plugin export from dayjs plugin file
  packages/nc-gui-v2/plugins/a.dayjs.ts
Labels: Scope: vue3

#2936 refactor(gui-v2): change right sidebar toggle icons
  packages/nc-gui-v2/components/smartsheet-toolbar/ToggleDrawer.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/context/index.ts
Labels: Scope: vue3

#2930 fix(gui-v2): cell follow ups
  packages/nc-gui-v2/components/cell/Email.vue
  packages/nc-gui-v2/components/cell/Url.vue
  packages/nc-gui-v2/components/virtual-cell/Formula.vue
Labels: Scope: vue3

#2942 feat(gui-v2): add `useInjectionState` composable
  packages/nc-gui-v2/composables/index.ts
  packages/nc-gui-v2/composables/useInjectionState/index.ts
Labels: Scope: vue3

#2940 fix(gui-v2): permission type not allowing wildcard
  packages/nc-gui-v2/composables/useUIPermission/index.ts
  packages/nc-gui-v2/composables/useUIPermission/rolePermissions.ts
Labels: Scope: vue3

#2937 chore(gui-v2): update menu styles to fill height properly
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
Labels: Scope: vue3

#2943 feat(gui-v2): accept keyname as arg for useInjectionState
  packages/nc-gui-v2/composables/useInjectionState/index.ts
Labels: Scope: vue3

#2860 refactor(gui-v2): Smartsheet toolbar
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/dlg/TableCreate.vue
  packages/nc-gui-v2/components/dlg/TableRename.vue
  packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCellIcon.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilter.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/DeleteTable.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldListAutoCompleteDropdown.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/LockMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SearchData.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ShareView.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SharedViewList.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SortListMenu.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/composables/index.ts
  packages/nc-gui-v2/composables/useDashboard.ts
  packages/nc-gui-v2/composables/useSmartsheetStore.ts
  packages/nc-gui-v2/composables/useTable.ts
  packages/nc-gui-v2/composables/useTableCreate.ts
  packages/nc-gui-v2/composables/useUIPermission/index.ts
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/composables/useViewFilters.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/utils/sortUtils.ts
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/src/lib/models/View.ts
  packages/nocodb/src/lib/version-upgrader/ncProjectUpgraderV2_0090000.ts
  scripts/sdk/swagger.json
Labels: Scope: vue3

#2910 feat(gui-v2): percent cell
  packages/nc-gui-v2/components/cell/Percent.vue
  packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/composables/useColumn.ts
  packages/nc-gui-v2/utils/percentUtils.ts
Labels: Scope: vue3

#2907 feat(gui-v2): Rating Cell
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/cell/Rating.vue
Labels: Scope: vue3

#2928 feat(gui-v2): number cell
  packages/nc-gui-v2/components/cell/Float.vue
  packages/nc-gui-v2/components/cell/Integer.vue
  packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
Labels: Scope: vue3

#2945 feat(gui-v2): Decimal Cell
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/cell/Decimal.vue
  packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/composables/useColumn.ts
Labels: Scope: vue3

#2961 refactor: remove user context information from webhook panel
  packages/nc-gui-v2/components/webhook/Editor.vue
  packages/nc-gui-v2/components/webhook/Test.vue
Labels: Type: In Development, Scope: vue3

#2948 refactor(gui-v2): show tooltip on bottomRight when sidebar is open
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/AddRow.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/DeleteTable.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/LockMenu.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/Reload.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/ToggleDrawer.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/index.vue
Labels: Scope: vue3

#2959 feat(gui-v2): SingleLineText Cell
  packages/nc-gui-v2/components/cell/Text.vue
Labels: Scope: vue3

#2960 feat(gui-v2): LongText Cell
  packages/nc-gui-v2/components/cell/TextArea.vue
Labels: Scope: vue3

#2949 feat(gui-v2): Count Cell
  packages/nc-gui-v2/components/smartsheet-header/VirtualCellIcon.vue
  packages/nc-gui-v2/components/smartsheet/VirtualCell.vue
  packages/nc-gui-v2/components/virtual-cell/Count.vue
  packages/nc-gui-v2/composables/useVirtualCell.ts
  packages/nocodb-sdk/src/lib/UITypes.ts
Labels: Scope: vue3

#2950 feat(gui-v2): SpecificDBType Cell
  packages/nc-gui-v2/components/smartsheet-header/VirtualCellIcon.vue
  packages/nocodb-sdk/src/lib/UITypes.ts
Labels: Scope: vue3

#2975 feat(gui-v2): duration options
  packages/nc-gui-v2/components/cell/Duration.vue
  packages/nc-gui-v2/components/smartsheet-column/DurationOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
  packages/nc-gui-v2/utils/durationUtils.ts
  packages/nc-gui-v2/utils/index.ts
Labels: Scope: vue3

#2972 feat(gui-v2): implement attachment cell
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/cell/Attachment.vue
  packages/nc-gui-v2/components/cell/Currency.vue
  packages/nc-gui-v2/components/cell/Email.vue
  packages/nc-gui-v2/components/cell/Float.vue
  packages/nc-gui-v2/components/cell/Integer.vue
  packages/nc-gui-v2/components/cell/JsonEditableCell.vue
  packages/nc-gui-v2/components/cell/MultiSelect.vue
  packages/nc-gui-v2/components/cell/SingleSelect.vue
  packages/nc-gui-v2/components/cell/Text.vue
  packages/nc-gui-v2/components/cell/TextArea.vue
  packages/nc-gui-v2/components/cell/Url.vue
  packages/nc-gui-v2/components/cell/attachment/Carousel.vue
  packages/nc-gui-v2/components/cell/attachment/Modal.vue
  packages/nc-gui-v2/components/cell/attachment/index.vue
  packages/nc-gui-v2/components/cell/attachment/sort.ts
  packages/nc-gui-v2/components/cell/attachment/utils.ts
  packages/nc-gui-v2/components/general/Overlay.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/context/index.ts
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/tsconfig.json
  packages/nc-gui-v2/utils/urlUtils.ts
Labels: Scope: vue3

#2976 refactor/i18n: new language support- hi, bn (@drsantam)
  packages/nc-gui/components/utils/Language.vue
  packages/nc-gui/lang/bn.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/plugins/i18n.js
  scripts/cypress/integration/common/6d_language_validation.js
Labels: Type: i18n translation

#2979 feat(gui-v2): rating column
  packages/nc-gui-v2/components/cell/Checkbox.vue
  packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
  packages/nc-gui-v2/components/smartsheet-column/RatingOptions.vue
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/utils/iconUtils.ts
  packages/nc-gui-v2/utils/index.ts
Labels: Scope: vue3

#2947 feat(gui-v2): Grid operations
  packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
  packages/nc-gui-v2/components/smartsheet-header/Cell.vue
  packages/nc-gui-v2/components/smartsheet-header/Menu.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/composables/useGridViewColumnWidth.ts
  packages/nc-gui-v2/composables/useViewData.ts
Labels: Scope: vue3

#2984 fix(gui-v2): fix empty meta & feed default values
  packages/nc-gui-v2/components/smartsheet-column/CurrencyOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/DurationOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/RatingOptions.vue
  packages/nc-gui-v2/composables/useColumnCreateStore.ts
Labels: Scope: vue3

#2991 fix: Provide edit-enabled in cell level
  packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/composables/useColumnCreateStore.ts
Labels: Scope: vue3

#2986 feat(gui-v2): checkbox options
  packages/nc-gui-v2/components/smartsheet-column/CheckboxOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
Labels: Scope: vue3

#2983 chore(gui-v2): apply theme scrollbar on ant modal
  packages/nc-gui-v2/assets/style-v2.scss
Labels: Scope: vue3

#3016 fix(gui-v2): select object value issue
  packages/nc-gui-v2/components/smartsheet-column/CheckboxOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/RatingOptions.vue
Labels: Scope: vue3

#3019 feat(gui-v2): add icons resolver to component auto-loader
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/nuxt.config.ts
Labels: Scope: vue3

#3037 fix: gui-v2 - sync filter auto save prop with localstorage
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
  packages/nc-gui-v2/composables/useGlobal/state.ts
  packages/nc-gui-v2/composables/useGlobal/types.ts
Labels: Scope: vue3

#3039 fix(gui-v2): filter and row count
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
  packages/nc-gui-v2/composables/useViewData.ts
Labels: Scope: vue3

#3044 chore(gui-v2): fix typecheck issues
  packages/nc-gui-v2/.eslintrc.js
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/cell/Currency.vue
  packages/nc-gui-v2/components/cell/Decimal.vue
  packages/nc-gui-v2/components/cell/Email.vue
  packages/nc-gui-v2/components/cell/Float.vue
  packages/nc-gui-v2/components/cell/Integer.vue
  packages/nc-gui-v2/components/cell/Json.vue
  packages/nc-gui-v2/components/cell/Rating.vue
  packages/nc-gui-v2/components/cell/SingleSelect.vue
  packages/nc-gui-v2/components/cell/Text.vue
  packages/nc-gui-v2/components/cell/TextArea.vue
  packages/nc-gui-v2/components/cell/Url.vue
  packages/nc-gui-v2/components/cell/attachment/Modal.vue
  packages/nc-gui-v2/components/dashboard/settings/UIAcl.vue
  packages/nc-gui-v2/components/general/Language.vue
  packages/nc-gui-v2/components/smartsheet-column/AdvancedOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/CheckboxOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/FormulaOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/LinkedToAnotherRecordOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/LookupOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/RollupOptions.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilter.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SearchData.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/DeleteTable.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/LockMenu.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/Reload.vue
  packages/nc-gui-v2/components/tabs/auth/user-management/ShareBase.vue
  packages/nc-gui-v2/components/virtual-cell/BelongsTo.vue
  packages/nc-gui-v2/components/virtual-cell/Formula.vue
  packages/nc-gui-v2/components/virtual-cell/HasMany.vue
  packages/nc-gui-v2/components/virtual-cell/Lookup.vue
  packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
  packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue
  packages/nc-gui-v2/components/virtual-cell/components/ListItems.vue
  packages/nc-gui-v2/components/webhook/Editor.vue
  packages/nc-gui-v2/components/webhook/List.vue
  packages/nc-gui-v2/composables/useColumnCreateStore.ts
  packages/nc-gui-v2/composables/useLTARStore.ts
  packages/nc-gui-v2/composables/useTableCreate.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/vue-color-shims.d.ts
Labels: Scope: vue3

#3023 feat(gui-v2): implement project menu
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/cell/attachment/index.vue
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/dashboard/settings/Modal.vue
  packages/nc-gui-v2/components/general/Language.vue
  packages/nc-gui-v2/components/general/MiniSidebar.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/Pagination.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/AddRow.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/LockMenu.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/ToggleDrawer.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/index.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/composables/index.ts
  packages/nc-gui-v2/composables/useGlobal/state.ts
  packages/nc-gui-v2/composables/useGlobal/types.ts
  packages/nc-gui-v2/composables/useInjectionState/index.ts
  packages/nc-gui-v2/composables/useSidebar/index.ts
  packages/nc-gui-v2/layouts/base.vue
  packages/nc-gui-v2/layouts/default.vue
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/index/index.vue
  packages/nc-gui-v2/pages/index/user/index.vue
  packages/nc-gui-v2/pages/index/user/index/index.vue
  packages/nc-gui-v2/pages/nc/[projectId]/index.vue
  packages/nc-gui-v2/pages/nc/[projectId]/index/index.vue
  packages/nc-gui-v2/pages/project/index/[id].vue
  packages/nc-gui-v2/pages/project/index/create-external.vue
  packages/nc-gui-v2/pages/project/index/create.vue
  packages/nc-gui-v2/pages/signin.vue
  packages/nc-gui-v2/plugins/state.ts
  packages/nc-gui-v2/tsconfig.json
  packages/nc-gui-v2/utils/viewUtils.ts
  packages/nc-gui-v2/windi.config.ts
Labels: Scope: vue3

#3052 chore(gui-v2): fix dropzone ref
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/cell/attachment/index.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/layouts/base.vue
Labels: Scope: vue3

#3022 feat(gui-v2): Single/multi select
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/cell/MultiSelect.vue
  packages/nc-gui-v2/components/cell/SingleSelect.vue
  packages/nc-gui-v2/components/general/ColorPicker.vue
  packages/nc-gui-v2/components/smartsheet-column/CheckboxOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
  packages/nc-gui-v2/components/smartsheet-column/RatingOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/SelectOptions.vue
  packages/nc-gui-v2/components/smartsheet-header/Menu.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nocodb-sdk/src/lib/Api.ts
  scripts/sdk/swagger.json
Labels: Scope: vue3

#3066 chore(gui-v2): attachment cell fixes
  packages/nc-gui-v2/components/cell/attachment/index.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/composables/useSmartsheetStore.ts
Labels: Scope: vue3

#3049 fix(gui-v2): formula
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
  packages/nc-gui-v2/components/smartsheet-column/FormulaOptions.vue
  packages/nc-gui-v2/components/virtual-cell/Formula.vue
Labels: Scope: vue3

#3035 vue3: API Snippet
  packages/nc-gui-v2/components/monaco/Editor.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/menu/ApiSnippet.vue
  packages/nc-gui-v2/composables/useGlobal/state.ts
  packages/nc-gui-v2/composables/useGlobal/types.ts
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/plugins/state.ts
Labels: Scope: vue3

#3025 vue3: Expanded form
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/smartsheet-column/FormulaOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/SelectOptions.vue
  packages/nc-gui-v2/components/smartsheet-header/Cell.vue
  packages/nc-gui-v2/components/smartsheet-header/Menu.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/Row.vue
  packages/nc-gui-v2/components/smartsheet/expanded-form/Comments.vue
  packages/nc-gui-v2/components/smartsheet/expanded-form/Header.vue
  packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue
  packages/nc-gui-v2/components/virtual-cell/BelongsTo.vue
  packages/nc-gui-v2/components/virtual-cell/HasMany.vue
  packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
  packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue
  packages/nc-gui-v2/components/virtual-cell/components/ListItems.vue
  packages/nc-gui-v2/composables/index.ts
  packages/nc-gui-v2/composables/useExpandedFormStore.ts
  packages/nc-gui-v2/composables/useLTARStore.ts
  packages/nc-gui-v2/composables/useSmartsheetRowStore.ts
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/plugins/domPurify.ts
  packages/nc-gui-v2/tsconfig.json
  packages/nc-gui-v2/utils/dataUtils.ts
  packages/nc-gui-v2/utils/index.ts
  packages/nc-gui/components/project/spreadsheet/components/ExpandedForm.vue
  packages/nocodb-sdk/src/lib/Api.ts
  scripts/sdk/swagger.json
Labels: Scope: vue3

#3076 feat(gui-v2): excel import
  packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
  packages/nc-gui-v2/lang/ar.json
  packages/nc-gui-v2/lang/bn.json
  packages/nc-gui-v2/lang/da.json
  packages/nc-gui-v2/lang/de.json
  packages/nc-gui-v2/lang/en.json
  packages/nc-gui-v2/lang/es.json
  packages/nc-gui-v2/lang/fa.json
  packages/nc-gui-v2/lang/fi.json
  packages/nc-gui-v2/lang/fr.json
  packages/nc-gui-v2/lang/hi.json
  packages/nc-gui-v2/lang/hr.json
  packages/nc-gui-v2/lang/id.json
  packages/nc-gui-v2/lang/it_IT.json
  packages/nc-gui-v2/lang/iw.json
  packages/nc-gui-v2/lang/ja.json
  packages/nc-gui-v2/lang/ko.json
  packages/nc-gui-v2/lang/lv.json
  packages/nc-gui-v2/lang/nl.json
  packages/nc-gui-v2/lang/no.json
  packages/nc-gui-v2/lang/pl.json
  packages/nc-gui-v2/lang/pt.json
  packages/nc-gui-v2/lang/pt_BR.json
  packages/nc-gui-v2/lang/ru.json
  packages/nc-gui-v2/lang/sl.json
  packages/nc-gui-v2/lang/sv.json
  packages/nc-gui-v2/lang/th.json
  packages/nc-gui-v2/lang/tr.json
  packages/nc-gui-v2/lang/uk.json
  packages/nc-gui-v2/lang/vi.json
  packages/nc-gui-v2/lang/zh_CN.json
  packages/nc-gui-v2/lang/zh_HK.json
  packages/nc-gui-v2/lang/zh_TW.json
Labels: Scope: vue3

#3030 feat(gui-v2): form view
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
  packages/nc-gui-v2/components/smartsheet-header/Cell.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
  packages/nc-gui-v2/components/smartsheet/Form.vue
  packages/nc-gui-v2/components/smartsheet/Toolbar.vue
  packages/nc-gui-v2/composables/useColumnCreateStore.ts
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/src/lib/models/View.ts
  scripts/sdk/swagger.json
Labels: Scope: vue3

#3067 vue3: Follow up on User management
  packages/nc-gui-v2/components/tabs/auth/UserManagement.vue
  packages/nc-gui-v2/components/tabs/auth/user-management/ShareBase.vue
  packages/nc-gui-v2/components/tabs/auth/user-management/UsersModal.vue
  packages/nc-gui-v2/composables/useUIPermission/rolePermissions.ts
  packages/nc-gui-v2/lang/en.json
  packages/nc-gui-v2/lib/enums.ts
  packages/nc-gui-v2/utils/urlUtils.ts
  packages/nc-gui-v2/utils/userUtils.ts
Labels: Scope: vue3

#3078 fix(gui-v2): form view follow-up issues
  packages/nc-gui-v2/components/dlg/ViewCreate.vue
  packages/nc-gui-v2/components/smartsheet/Form.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
  packages/nc-gui-v2/composables/useViewData.ts
Labels: Scope: vue3

#3051 fix(gui-v2): Misc issues
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/dashboard/settings/AppStore.vue
  packages/nc-gui-v2/components/dashboard/settings/Metadata.vue
  packages/nc-gui-v2/components/dashboard/settings/UIAcl.vue
  packages/nc-gui-v2/components/dashboard/settings/app-store/AppInstall.vue
  packages/nc-gui-v2/components/dlg/AirtableImport.vue
  packages/nc-gui-v2/components/dlg/QuickImport.vue
  packages/nc-gui-v2/components/dlg/TableRename.vue
  packages/nc-gui-v2/components/smartsheet-column/FormulaOptions.vue
  packages/nc-gui-v2/components/smartsheet-header/Menu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ShareView.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SharedViewList.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/LockMenu.vue
  packages/nc-gui-v2/components/tabs/auth/ApiTokenManagement.vue
  packages/nc-gui-v2/components/tabs/auth/UserManagement.vue
  packages/nc-gui-v2/components/tabs/auth/user-management/ShareBase.vue
  packages/nc-gui-v2/components/tabs/auth/user-management/UsersModal.vue
  packages/nc-gui-v2/components/template/Editor.vue
  packages/nc-gui-v2/components/template/utils.ts
  packages/nc-gui-v2/components/webhook/Editor.vue
  packages/nc-gui-v2/components/webhook/List.vue
  packages/nc-gui-v2/components/webhook/Test.vue
  packages/nc-gui-v2/composables/useColumnCreateStore.ts
  packages/nc-gui-v2/composables/useTable.ts
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/composables/useViews.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/index/index.vue
  packages/nc-gui-v2/pages/project/index/[id].vue
  packages/nc-gui-v2/pages/project/index/create-external.vue
  packages/nc-gui-v2/pages/project/index/create.vue
  packages/nc-gui-v2/pages/projects/index.vue
  packages/nc-gui-v2/plugins/toastr.ts
  packages/nc-gui-v2/utils/index.ts
  packages/nc-gui-v2/utils/parsers/ExcelTemplateAdapter.ts
Labels: Scope: vue3

#3091 vue3: Add preview as option
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/general/PreviewAs.vue
  packages/nc-gui-v2/composables/useApi/interceptors.ts
  packages/nc-gui-v2/composables/useGlobal/state.ts
  packages/nc-gui-v2/composables/useGlobal/types.ts
  packages/nc-gui-v2/composables/useUIPermission/index.ts
  packages/nc-gui-v2/pages/nc/[projectId]/index.vue
Labels: Scope: vue3

#3095 feat(gui-v2): close dropdown menu on esc keydown
  packages/nc-gui-v2/pages/nc/[projectId]/index.vue
Labels: Scope: vue3

#3099 refactor(gui-v2): remove vuetify from language switcher
  packages/nc-gui-v2/components/general/Language.vue
  packages/nc-gui-v2/nuxt.config.ts
Labels: Scope: vue3

#3096 refactor(gui-v2): ui updates
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/smartsheet-header/Cell.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilter.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldListAutoCompleteDropdown.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ShareView.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SortListMenu.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/Toolbar.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/pages/nc/[projectId]/index/index.vue
  packages/nc-gui-v2/utils/colorsUtils.ts
Labels: Scope: vue3

#3101 feat(gui-v2): settings modal overflow
  packages/nc-gui-v2/components/dashboard/settings/Metadata.vue
  packages/nc-gui-v2/components/dashboard/settings/Modal.vue
  packages/nc-gui-v2/components/dashboard/settings/UIAcl.vue
Labels: Scope: vue3

#3108 fix(gui-v2): close timepicker on outside click
  packages/nc-gui-v2/components/cell/TimePicker.vue
Labels: Scope: vue3

#3094 fix(gui-v2): abort renaming view on failed validation
  packages/nc-gui-v2/components/smartsheet-header/Cell.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
Labels: Scope: vue3

#3112 fix(gui-v2): check if project title is being in use when renaming
  packages/nocodb/src/lib/meta/api/projectApis.ts
Labels: Scope: vue3

#3110 fix(gui-v2): sign out after reset pwd like v1
  packages/nc-gui-v2/pages/index/user/index/index.vue
Labels: Scope: vue3

#3111 fix(gui-v2): add missing logos
  packages/nc-gui-v2/layouts/base.vue
  packages/nc-gui-v2/pages/project/index/create-external.vue
  packages/nc-gui-v2/pages/project/index/create.vue
Labels: Scope: vue3

#3113 refactor(gui-v2): use message instead of notification
  packages/nc-gui-v2/components/cell/attachment/utils.ts
  packages/nc-gui-v2/components/dashboard/settings/AppStore.vue
  packages/nc-gui-v2/components/dashboard/settings/Metadata.vue
  packages/nc-gui-v2/components/dashboard/settings/UIAcl.vue
  packages/nc-gui-v2/components/dashboard/settings/app-store/AppInstall.vue
  packages/nc-gui-v2/components/dlg/AirtableImport.vue
  packages/nc-gui-v2/components/dlg/QuickImport.vue
  packages/nc-gui-v2/components/dlg/TableRename.vue
  packages/nc-gui-v2/components/dlg/ViewCreate.vue
  packages/nc-gui-v2/components/dlg/ViewDelete.vue
  packages/nc-gui-v2/components/smartsheet-header/Menu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ShareView.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SharedViewList.vue
  packages/nc-gui-v2/components/smartsheet/Form.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/menu/ApiSnippet.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/LockMenu.vue
  packages/nc-gui-v2/components/tabs/auth/ApiTokenManagement.vue
  packages/nc-gui-v2/components/tabs/auth/UserManagement.vue
  packages/nc-gui-v2/components/tabs/auth/user-management/ShareBase.vue
  packages/nc-gui-v2/components/tabs/auth/user-management/UsersModal.vue
  packages/nc-gui-v2/components/template/Editor.vue
  packages/nc-gui-v2/components/webhook/Editor.vue
  packages/nc-gui-v2/components/webhook/List.vue
  packages/nc-gui-v2/components/webhook/Test.vue
  packages/nc-gui-v2/composables/useColumnCreateStore.ts
  packages/nc-gui-v2/composables/useExpandedFormStore.ts
  packages/nc-gui-v2/composables/useGlobal/actions.ts
  packages/nc-gui-v2/composables/useLTARStore.ts
  packages/nc-gui-v2/composables/useSmartsheetRowStore.ts
  packages/nc-gui-v2/composables/useTable.ts
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/pages/index/index.vue
  packages/nc-gui-v2/pages/project/index/[id].vue
  packages/nc-gui-v2/pages/project/index/create-external.vue
  packages/nc-gui-v2/pages/project/index/create.vue
  packages/nc-gui-v2/pages/projects/index.vue
Labels: Scope: vue3

#3082 fix(gui-v2): select improvements
  packages/nc-gui-v2/components/cell/MultiSelect.vue
  packages/nc-gui-v2/components/cell/SingleSelect.vue
  packages/nc-gui-v2/components/smartsheet-header/Menu.vue
  packages/nocodb/src/lib/meta/api/columnApis.ts
Labels: Scope: vue3

#3087 fix(gui-v2): add i18n / isUIAllowed
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/cell/Checkbox.vue
  packages/nc-gui-v2/components/cell/Currency.vue
  packages/nc-gui-v2/components/cell/DatePicker.vue
  packages/nc-gui-v2/components/cell/DateTimePicker.vue
  packages/nc-gui-v2/components/cell/Decimal.vue
  packages/nc-gui-v2/components/cell/Duration.vue
  packages/nc-gui-v2/components/cell/Email.vue
  packages/nc-gui-v2/components/cell/Float.vue
  packages/nc-gui-v2/components/cell/Integer.vue
  packages/nc-gui-v2/components/cell/Json.vue
  packages/nc-gui-v2/components/cell/MultiSelect.vue
  packages/nc-gui-v2/components/cell/Percent.vue
  packages/nc-gui-v2/components/cell/Rating.vue
  packages/nc-gui-v2/components/cell/SingleSelect.vue
  packages/nc-gui-v2/components/cell/Text.vue
  packages/nc-gui-v2/components/cell/TextArea.vue
  packages/nc-gui-v2/components/cell/TimePicker.vue
  packages/nc-gui-v2/components/cell/Url.vue
  packages/nc-gui-v2/components/cell/YearPicker.vue
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/dashboard/settings/Modal.vue
  packages/nc-gui-v2/components/smartsheet-header/Cell.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ShareView.vue
  packages/nc-gui-v2/components/smartsheet/Form.vue
  packages/nc-gui-v2/components/smartsheet/Gallery.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/expanded-form/Header.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/index.vue
  packages/nc-gui-v2/components/tabs/auth/ApiTokenManagement.vue
  packages/nc-gui-v2/components/virtual-cell/BelongsTo.vue
  packages/nc-gui-v2/components/virtual-cell/HasMany.vue
  packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
  packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/composables/useViewSorts.ts
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index.vue
  packages/nc-gui-v2/pages/index/index.vue
Labels: Scope: vue3

#3133 fix(gui-v2): form layout
  packages/nc-gui-v2/components/smartsheet/Form.vue
Labels: Scope: vue3

#3134 fix(gui-v2): column edit/add handling
  packages/nc-gui-v2/components/smartsheet-column/AdvancedOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/CheckboxOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/CurrencyOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/DateOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/DurationOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
  packages/nc-gui-v2/components/smartsheet-column/EditOrAddProvider.vue
  packages/nc-gui-v2/components/smartsheet-column/FormulaOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/LinkedToAnotherRecordOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/LookupOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/PercentOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/RatingOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/RollupOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/SelectOptions.vue
  packages/nc-gui-v2/components/smartsheet-column/SpecificDBTypeOptions.vue
  packages/nc-gui-v2/components/smartsheet-header/Cell.vue
  packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
  packages/nc-gui-v2/components/smartsheet/Form.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/composables/useColumn.ts
  packages/nc-gui-v2/composables/useColumnCreateStore.ts
  packages/nc-gui-v2/package.json
Labels: Scope: vue3

#3149 fix(gui-v2): remove formulaSuggestionDrawer
  packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
  packages/nc-gui-v2/components/smartsheet-column/FormulaOptions.vue
Labels: Scope: vue3

#3153 fix(gui-v2): update default active index
  packages/nc-gui-v2/composables/useTabs.ts
Labels: Scope: vue3

#3162 feat(gui-v2): reopen attachment modal on carousel close
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/cell/attachment/Carousel.vue
  packages/nc-gui-v2/components/cell/attachment/Modal.vue
  packages/nc-gui-v2/components/cell/attachment/index.vue
  packages/nc-gui-v2/components/general/PreviewAs.vue
Labels: Scope: vue3

#3157 feat(gui-v2): misc issues (con't)
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/dashboard/settings/Misc.vue
  packages/nc-gui-v2/components/dashboard/settings/Modal.vue
  packages/nc-gui-v2/components/dashboard/settings/UIAcl.vue
  packages/nc-gui-v2/components/general/ReleaseInfo.vue
  packages/nc-gui-v2/components/general/ShareBaseButton.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/DebugMeta.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/DeleteCache.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/DeleteTable.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/ExportCache.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/index.vue
  packages/nc-gui-v2/composables/useGlobal/state.ts
  packages/nc-gui-v2/composables/useGlobal/types.ts
  packages/nc-gui-v2/composables/useProject.ts
  packages/nc-gui-v2/layouts/base.vue
Labels: Scope: vue3

#3166 vue3: Swagger API URL, Project info copy and Auth token copy
  packages/nc-gui-v2/composables/useProject.ts
  packages/nc-gui-v2/lib/types.ts
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui-v2/utils/urlUtils.ts
Labels: Scope: vue3

#3169 fix(gui-v2): show form items in editable state and handle LTAR columns
  packages/nc-gui-v2/components/cell/DatePicker.vue
  packages/nc-gui-v2/components/cell/DateTimePicker.vue
  packages/nc-gui-v2/components/cell/Json.vue
  packages/nc-gui-v2/components/cell/TimePicker.vue
  packages/nc-gui-v2/components/cell/YearPicker.vue
  packages/nc-gui-v2/components/smartsheet/Form.vue
  packages/nc-gui-v2/components/virtual-cell/BelongsTo.vue
  packages/nc-gui-v2/components/virtual-cell/HasMany.vue
  packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
  packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue
  packages/nc-gui-v2/components/virtual-cell/components/ListItems.vue
  packages/nc-gui-v2/composables/useLTARStore.ts
  packages/nc-gui-v2/composables/useSmartsheetRowStore.ts
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/context/index.ts
Labels: Scope: vue3

#3172 fix(gui-v2): minor improvements
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/smartsheet-header/Cell.vue
  packages/nc-gui-v2/components/smartsheet-header/Menu.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCellIcon.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/expanded-form/Comments.vue
  packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue
  packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
Labels: Scope: vue3

#3198 fix(gui-v2): formula AC tree
  packages/nc-gui-v2/utils/NcAutocompleteTree.ts
Labels: Scope: vue3

#3192 chore(gui-v2): remove placeholders for *Picker cells
  packages/nc-gui-v2/components/cell/DatePicker.vue
  packages/nc-gui-v2/components/cell/DateTimePicker.vue
  packages/nc-gui-v2/components/cell/TimePicker.vue
  packages/nc-gui-v2/components/cell/YearPicker.vue
Labels: Scope: vue3

#3195 chore(gui-v2): hide some right toolbar buttons in form view
  packages/nc-gui-v2/components/smartsheet/Form.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/index.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
Labels: Scope: vue3

#3174 feat(gui-v2): sidebar state with localStorage
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/AddRow.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/DeleteTable.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/Reload.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/composables/useSidebar/index.ts
  packages/nc-gui-v2/context/index.ts
Labels: Scope: vue3

#3204 fix: Lookup, Rollup, Count
  packages/nc-gui-v2/components/smartsheet/VirtualCell.vue
Labels: Scope: vue3

#3171 chore(gui-v2): style and import cleanups
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/general/PreviewAs.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilter.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/index.vue
  packages/nc-gui-v2/pages/[projectType]/view/[viewId].vue
  packages/nc-gui-v2/pages/forgot-password.vue
  packages/nc-gui-v2/pages/index/index.vue
  packages/nc-gui-v2/pages/signin.vue
  packages/nc-gui-v2/pages/signup/[[token]].vue
Labels: Scope: vue3

#3180 Reverted percent to how percent is handled in v1
  packages/nc-gui-v2/components/cell/Percent.vue
  packages/nc-gui-v2/components/smartsheet-column/EditOrAdd.vue
  packages/nc-gui-v2/components/smartsheet-column/PercentOptions.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
Labels: Scope: vue3

#3203 fix(gui-v2): easter icons appear when toggling toolbar icons twice
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
Labels: Scope: vue3

#3197 Follow up on shared view
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/components/cell/Checkbox.vue
  packages/nc-gui-v2/components/shared-view/Grid.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ShareView.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/composables/useSharedView.ts
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/layouts/shared-view.vue
  packages/nc-gui-v2/lib/types.ts
  packages/nc-gui-v2/middleware/auth.global.ts
  packages/nc-gui-v2/pages/[projectType]/view/[viewId].vue
Labels: Scope: vue3

#3213 fix(gui-v2): fields menu
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
  packages/nc-gui-v2/composables/useViewColumns.ts
Labels: Scope: vue3

#3209 feat(gui-v2): isLocked
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components/cell/YearPicker.vue
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/smartsheet-header/Menu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/AddRow.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/components/virtual-cell/BelongsTo.vue
  packages/nc-gui-v2/components/virtual-cell/HasMany.vue
  packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
  packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui-v2/composables/useSharedView.ts
  packages/nc-gui-v2/context/index.ts
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
Labels: Scope: vue3

#3224 fix(gui-v2): disable lookup in form
  packages/nc-gui-v2/components/smartsheet/Form.vue
Labels: Scope: vue3

#3225 Made `Add new row` button functional
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/toolbar/AddRow.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/context/index.ts
Labels: Scope: vue3

#3228 chore(gui-v2): navigate to auth tab on project select
  packages/nc-gui-v2/pages/index/index.vue
Labels: Scope: vue3

#3211 feat(gui-v2): add dropzone to project intro page
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/dlg/AirtableImport.vue
  packages/nc-gui-v2/components/dlg/QuickImport.vue
  packages/nc-gui-v2/components/dlg/TableCreate.vue
  packages/nc-gui-v2/components/general/Language.vue
  packages/nc-gui-v2/components/general/PreviewAs.vue
  packages/nc-gui-v2/components/smartsheet-header/Menu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/template/Editor.vue
  packages/nc-gui-v2/composables/index.ts
  packages/nc-gui-v2/composables/useDialog/index.ts
  packages/nc-gui-v2/composables/useGlobal/actions.ts
  packages/nc-gui-v2/composables/useViewFilters.ts
  packages/nc-gui-v2/layouts/base.vue
  packages/nc-gui-v2/nuxt-shim.d.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/index.vue
  packages/nc-gui-v2/plugins/ant.ts
Labels: Scope: vue3

#3232 fix(gui-v2): dblclick not triggered on renmable menu item
  packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
Labels: Scope: vue3

#3243 chore(gui-v2): fix menu style spacings and colorings
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/general/MiniSidebar.vue
  packages/nc-gui-v2/components/general/PreviewAs.vue
  packages/nc-gui-v2/components/general/language/Menu.vue
  packages/nc-gui-v2/components/general/language/index.vue
  packages/nc-gui-v2/layouts/base.vue
  packages/nc-gui-v2/layouts/shared-view.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index.vue
Labels: Scope: vue3

#3237 Fixed table column toggle while table creation
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/dlg/TableCreate.vue
  packages/nc-gui-v2/composables/useTable.ts
  packages/nc-gui-v2/lib/constants.ts
Labels: Scope: vue3

#3240 fix(gui-v2): disable context menu
  packages/nc-gui-v2/components/general/PreviewAs.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
Labels: Scope: vue3

#3234 fix(gui-v2) shared base issues
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ShareView.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/virtual-cell/BelongsTo.vue
  packages/nc-gui-v2/components/virtual-cell/HasMany.vue
  packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
  packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui-v2/composables/useProject.ts
  packages/nc-gui-v2/composables/useUIPermission/index.ts
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/composables/useViewFilters.ts
  packages/nc-gui-v2/composables/useViewSorts.ts
  packages/nc-gui-v2/layouts/base.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/index.vue
  packages/nocodb/src/lib/utils/projectAcl.ts
Labels: Scope: vue3

#3263 fix(gui-v2): reload the page if the same form view is clicked
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
Labels: Scope: vue3

#3260 fix(gui-v2): webhook layout
  packages/nc-gui-v2/components/webhook/Drawer.vue
  packages/nc-gui-v2/components/webhook/Editor.vue
  packages/nc-gui-v2/components/webhook/List.vue
Labels: Scope: vue3

#3258 fix(gui-v2): remove incorrect isUIAllowed
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
Labels: Scope: vue3

#3257 fix(gui-v2): includeM2M display
  packages/nc-gui-v2/components/dashboard/settings/UIAcl.vue
  packages/nocodb/src/lib/meta/api/tableApis.ts
Labels: Scope: vue3

#3247 fix(gui-v2): view break issue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
Labels: Scope: vue3

#3252 feat(gui-v2): add google auth signup option
  packages/nc-gui-v2/assets/style.scss
  packages/nc-gui-v2/components/general/SocialCard.vue
  packages/nc-gui-v2/components/general/Sponsors.vue
  packages/nc-gui-v2/composables/useTheme/index.ts
  packages/nc-gui-v2/layouts/base.vue
  packages/nc-gui-v2/layouts/default.vue
  packages/nc-gui-v2/middleware/auth.global.ts
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/index/index.vue
  packages/nc-gui-v2/pages/signup/[[token]].vue
Labels: Scope: vue3

#3272 fix(gui-v2): cannot read properties of undefined (reading 'length')
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilter.vue
Labels: Scope: vue3

#3251 fix/Added filter sorting for user with viewer role
  packages/nc-gui-v2/components/shared-view/Grid.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilter.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
  packages/nc-gui-v2/composables/useSmartsheetStore.ts
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/composables/useViewFilters.ts
  packages/nc-gui-v2/composables/useViewSorts.ts
Labels: Scope: vue3

#3281 fix(gui-v2): close correct tab on `x` icon click
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index.vue
Labels: Scope: vue3

#3276 vue3: Improved welcome page UI and some other UI fixes
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/dlg/TableCreate.vue
  packages/nc-gui-v2/layouts/shared-view.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/index.vue
Labels: Scope: vue3

#3285 fix(gui-v2): context menu styles
  packages/nc-gui-v2/components/smartsheet/Grid.vue
Labels: Scope: vue3

#3288 vue3: Fixed styling of search and bottom buttons of tree view
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/general/HelpAndSupport.vue
  packages/nc-gui-v2/components/general/ShareBaseButton.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SearchData.vue
Labels: Scope: vue3

#3287 chore(gui-v2): fix modal menu styles
  packages/nc-gui-v2/components/dashboard/settings/Modal.vue
  packages/nc-gui-v2/components/general/HelpAndSupport.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SearchData.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui-v2/windi.config.ts
Labels: Scope: vue3

#3280 refactor(gui-v2): make create and update project pages subpages of dashboard
  packages/nc-gui-v2/assets/style.scss
  packages/nc-gui-v2/components/dashboard/GithubStarButton.vue
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/general/ShareBaseButton.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuBottom.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/RenameableMenuItem.vue
  packages/nc-gui-v2/components/smartsheet/sidebar/index.vue
  packages/nc-gui-v2/github-star.shims.d.ts
  packages/nc-gui-v2/layouts/base.vue
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui-v2/pages/index/index.vue
  packages/nc-gui-v2/pages/index/index/[id].vue
  packages/nc-gui-v2/pages/index/index/create-external.vue
  packages/nc-gui-v2/pages/index/index/create.vue
  packages/nc-gui-v2/pages/index/index/index.vue
  packages/nc-gui-v2/pages/index/user/index/index.vue
  packages/nc-gui-v2/pages/project/index.vue
  packages/nc-gui-v2/pages/project/index/[id].vue
  packages/nc-gui-v2/pages/project/index/create.vue
  packages/nc-gui-v2/pages/signin.vue
Labels: Scope: vue3

#3117 fix(gui-v2): table rename
  packages/nc-gui-v2/components/dlg/TableCreate.vue
  packages/nc-gui-v2/components/dlg/TableRename.vue
  packages/nc-gui-v2/composables/useProject.ts
  packages/nc-gui-v2/composables/useTable.ts
  packages/nc-gui/components/ProjectTreeView.vue
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/src/lib/meta/api/tableApis.ts
  packages/nocodb/src/lib/models/Model.ts
  scripts/cypress/integration/common/1a_table_operations.js
  scripts/sdk/swagger.json
Labels: Scope: vue3

#3244 feat(gui-v2): add smtp rejectUnauthorized
  packages/nc-gui-v2/components/dashboard/settings/app-store/AppInstall.vue
  packages/nocodb/src/lib/plugins/smtp/SMTP.ts
  packages/nocodb/src/lib/plugins/smtp/index.ts
  packages/nocodb/tests/pg-cy-quick/01-cy-quick.sql
  scripts/cypress/support/page_objects/mainPage.js
Labels: Scope: vue3

#3292 vue3: Fixed UI issues for Viewer and Shared view
  packages/nc-gui-v2/components/shared-view/Grid.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/Export.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ExportSubActions.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ViewActions.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ViewInfo.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/Toolbar.vue
  packages/nc-gui-v2/composables/useUIPermission/rolePermissions.ts
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/layouts/shared-view.vue
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index/index/index.vue
Labels: Scope: vue3

#3298 refactor(gui-v2): remove shared base btn from header
  packages/nc-gui-v2/layouts/base.vue
Labels: Scope: vue3

#3268 fix(gui-v2): gallery view
  packages/nc-gui-v2/components/cell/attachment/index.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/smartsheet/Gallery.vue
  packages/nc-gui-v2/composables/useViewColumns.ts
Labels: Scope: vue3

#3300 fix(gui-v2): attachments not loading in shared view
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/cell/Text.vue
  packages/nc-gui-v2/components/cell/attachment/index.vue
  packages/nc-gui-v2/components/cell/attachment/utils.ts
  packages/nc-gui-v2/components/general/HelpAndSupport.vue
  packages/nc-gui-v2/components/shared-view/Form.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SortListMenu.vue
  packages/nc-gui-v2/components/smartsheet/Form.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/composables/useSharedFormViewStore.ts
  packages/nc-gui-v2/composables/useSmartsheetRowStore.ts
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/layouts/default.vue
  packages/nc-gui-v2/nuxt-shim.d.ts
  packages/nc-gui-v2/pages/[projectType]/form/[viewId].vue
  packages/nc-gui-v2/pages/[projectType]/form/[viewId]/index.vue
  packages/nc-gui-v2/utils/urlUtils.ts
  packages/nc-gui-v2/windi.config.ts
Labels: Scope: vue3

#3307 chore(gui-v2): type fixes on create-external page
  packages/nc-gui-v2/pages/index/index/create-external.vue
  packages/nc-gui-v2/utils/projectCreateUtils.ts
Labels: Scope: vue3

#3315 fix(gui-v2): retain hook.notification.payload data
  packages/nc-gui-v2/components/webhook/Editor.vue
Labels: Scope: vue3

#3319 fix(gui-v2): incorrect sheet names in excel import
  packages/nc-gui-v2/components/template/Editor.vue
Labels: Scope: vue3

#3324 fix(gui-v2): trigger reload in updateOrSaveRow
  packages/nc-gui-v2/composables/useViewData.ts
Labels: Scope: vue3

#3325 fix(gui-v2): link to field correction
  packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue
Labels: Scope: vue3

#3353 fix(gui-v2) missing expand cell in shared view
  packages/nc-gui-v2/components/smartsheet/expanded-form/index.vue
  packages/nc-gui-v2/components/virtual-cell/HasMany.vue
  packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue
  packages/nc-gui-v2/composables/useLTARStore.ts
Labels: Scope: vue3

#3355 fix(gui-v2): exclude col.cdf case
  packages/nc-gui-v2/components/smartsheet/Form.vue
Labels: Scope: vue3

#3343 fix: route update on rename view
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
Labels: Scope: vue3

#3356 fix: avoid complete page reload on clicking view name in right navbar
  packages/nc-gui-v2/components/smartsheet/sidebar/MenuTop.vue
Labels: Scope: vue3

#3365 fix(gui-v2): undefined view in shared form
  packages/nc-gui-v2/composables/useLTARStore.ts
Labels: Scope: vue3

#3368 feat(gui-v2): project theme/color
  packages/nc-gui-v2/assets/style.scss
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/general/ColorPicker.vue
  packages/nc-gui-v2/composables/useProject.ts
  packages/nc-gui-v2/composables/useTheme/index.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui-v2/pages/index/index/[id].vue
  packages/nc-gui-v2/pages/index/index/index.vue
  packages/nocodb/src/lib/meta/api/projectApis.ts
  packages/nocodb/src/lib/meta/helpers/extractProps.ts
  packages/nocodb/src/lib/models/Base.ts
  packages/nocodb/src/lib/models/FormViewColumn.ts
  packages/nocodb/src/lib/models/FormulaColumn.ts
  packages/nocodb/src/lib/models/GridViewColumn.ts
  packages/nocodb/src/lib/models/HookLog.ts
  packages/nocodb/src/lib/models/Project.ts
  packages/nocodb/src/lib/models/SyncSource.ts
  packages/nocodb/src/lib/models/User.ts
  packages/nocodb/src/lib/models/View.ts
Labels: Scope: vue3

#3383 fix(gui-v2): include fields, sortArrJson, and filterArrJson when extracting CSV data
  packages/nc-gui-v2/components/smartsheet-toolbar/ExportSubActions.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
  packages/nocodb-sdk/package.json
  packages/nocodb/src/lib/meta/api/dataApis/helpers.ts
Labels: Scope: vue3

#3387 fix(gui-v2): image paths
  packages/nc-gui-v2/assets/img/ants-leaf-cutter.jpeg
  packages/nc-gui-v2/assets/img/social/email.png
  packages/nc-gui-v2/assets/img/social/facebook.png
  packages/nc-gui-v2/assets/img/social/google-plus.png
  packages/nc-gui-v2/assets/img/social/googlemaps.png
  packages/nc-gui-v2/assets/img/social/gov.uk.png
  packages/nc-gui-v2/assets/img/social/instagram.png
  packages/nc-gui-v2/assets/img/social/linkedin.png
  packages/nc-gui-v2/assets/img/social/medium.png
  packages/nc-gui-v2/assets/img/social/onthemarket.png
  packages/nc-gui-v2/assets/img/social/pinterest.png
  packages/nc-gui-v2/assets/img/social/png/douban.png
  packages/nc-gui-v2/assets/img/social/png/facebook.png
  packages/nc-gui-v2/assets/img/social/png/gmail.png
  packages/nc-gui-v2/assets/img/social/png/google-plus.png
  packages/nc-gui-v2/assets/img/social/png/line.png
  packages/nc-gui-v2/assets/img/social/png/linkedin.png
  packages/nc-gui-v2/assets/img/social/png/medium.png
  packages/nc-gui-v2/assets/img/social/png/odnoklassniki.png
  packages/nc-gui-v2/assets/img/social/png/renren.png
  packages/nc-gui-v2/assets/img/social/png/skype.png
  packages/nc-gui-v2/assets/img/social/png/telegram.png
  packages/nc-gui-v2/assets/img/social/png/twitter.png
  packages/nc-gui-v2/assets/img/social/png/viber.png
  packages/nc-gui-v2/assets/img/social/png/vk.png
  packages/nc-gui-v2/assets/img/social/png/wechat.png
  packages/nc-gui-v2/assets/img/social/png/weibo.png
  packages/nc-gui-v2/assets/img/social/png/whatsapp.png
  packages/nc-gui-v2/assets/img/social/png/wykop.jpg
  packages/nc-gui-v2/assets/img/social/reddit.png
  packages/nc-gui-v2/assets/img/social/scribd.png
  packages/nc-gui-v2/assets/img/social/snapchat.png
  packages/nc-gui-v2/assets/img/social/tumblr.png
  packages/nc-gui-v2/assets/img/social/twitter.png
  packages/nc-gui-v2/assets/img/social/whatsapp.png
  packages/nc-gui-v2/assets/img/social/zoopla.jpg
  packages/nc-gui-v2/components/general/Share.vue
  packages/nc-gui-v2/components/general/Sponsors.vue
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/public/favicon.ico
  packages/nc-gui/nuxt.config.js
Labels: Scope: vue3

#3390 fix: project theme
  packages/nc-gui-v2/composables/useInjectionState/index.ts
  packages/nc-gui-v2/composables/useProject.ts
  packages/nc-gui-v2/composables/useTheme/index.ts
  packages/nc-gui-v2/pages/[projectType]/[projectId]/index.vue
  packages/nc-gui-v2/pages/index/index/[projectId].vue
  packages/nc-gui-v2/pages/index/index/index.vue
Labels: Scope: vue3

#3395 fix(gui-v2): use import data with the first key
  packages/nc-gui-v2/components/template/Editor.vue
Labels: Scope: vue3

#3396 test: cicd wait
  .github/workflows/ci-cd-v2.yml
Labels: Status: Do Not Merge, Scope: vue3
