Repository nocodb/nocodb, pull requests merged in 2022-07, with the labels that each got.

#2585 feat(gui-v2,deps): add unplugin-icons
  packages/nc-gui-v2/components/general/Language.vue
  packages/nc-gui-v2/layouts/default.vue
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/tsconfig.json
Labels: Scope : Frontend

#2584 feat(gui-v2): project list
  packages/nc-gui-v2/assets/style.css
  packages/nc-gui-v2/components/general/Language.vue
  packages/nc-gui-v2/components/general/Sponsors.vue
  packages/nc-gui-v2/composables/useColors.ts
  packages/nc-gui-v2/composables/useGlobalState.ts
  packages/nc-gui-v2/layouts/default.vue
  packages/nc-gui-v2/lib/types.ts
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/projects/create-external.vue
  packages/nc-gui-v2/pages/projects/create.vue
  packages/nc-gui-v2/pages/projects/index.vue
  packages/nc-gui-v2/plugins/vuetify.ts
  packages/nc-gui-v2/public/ants-leaf-cutter.jpeg
  packages/nc-gui-v2/public/favicon-32.png
  packages/nc-gui-v2/public/icon.png
  packages/nc-gui-v2/utils/colorsUtils.ts
  packages/nc-gui-v2/windi.config.ts
Labels: Scope : Frontend

#2593 feat(gui-v2): add page transitions
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/assets/style-v2.css
  packages/nc-gui-v2/assets/style.css
  packages/nc-gui-v2/components/general/Sponsors.vue
  packages/nc-gui-v2/layouts/default.vue
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/windi.config.ts
Labels: Scope : Frontend

#2602 feat(gui-v2): add signIn action to global state
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/composables/useGlobalState.ts
  packages/nc-gui-v2/lib/types.ts
  packages/nc-gui-v2/middleware/auth.global.ts
  packages/nc-gui-v2/pages/signin.vue
Labels: Scope : Frontend

#2612 chore(gui-v2): type and code-style fixes
  packages/nc-gui-v2/components/cell/Attachment.vue
  packages/nc-gui-v2/components/cell/Checkbox.vue
  packages/nc-gui-v2/components/cell/DatePicker.vue
  packages/nc-gui-v2/components/cell/DateTimePicker.vue
  packages/nc-gui-v2/components/cell/Email.vue
  packages/nc-gui-v2/components/cell/Float.vue
  packages/nc-gui-v2/components/cell/Integer.vue
  packages/nc-gui-v2/components/cell/MultiSelect.vue
  packages/nc-gui-v2/components/cell/Rating.vue
  packages/nc-gui-v2/components/cell/SingleSelect.vue
  packages/nc-gui-v2/components/cell/Text.vue
  packages/nc-gui-v2/components/cell/TextArea.vue
  packages/nc-gui-v2/components/cell/Url.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/Pagination.vue
  packages/nc-gui-v2/components/smartsheet/VirtualCell.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/components/virtual-cell/Formula.vue
  packages/nc-gui-v2/components/virtual-cell/HasMany.vue
  packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
Labels: Scope : Frontend

#2609 feat(gui-v2,deps): use jwt expiry to check if user is still signed in
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/components/general/Language.vue
  packages/nc-gui-v2/composables/useGlobalState.ts
  packages/nc-gui-v2/lib/enums.ts
  packages/nc-gui-v2/lib/types.ts
  packages/nc-gui-v2/middleware/auth.global.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/signin.vue
  packages/nc-gui-v2/plugins/api.ts
Labels: Scope : Frontend

#2638 fix(gui-v2): detect browser language & match against locale
  packages/nc-gui-v2/composables/useGlobalState.ts
  packages/nc-gui-v2/nuxt-shim.d.ts
  packages/nc-gui-v2/plugins/i18n.ts
  packages/nc-gui-v2/plugins/state.ts
Labels: Scope : Frontend

#2621 feat(gui-v2): add list view
  packages/nc-gui-v2/components/general/Language.vue
  packages/nc-gui-v2/pages/projects/index.vue
  packages/nc-gui-v2/pages/projects/index/index.vue
  packages/nc-gui-v2/pages/projects/index/list.vue
Labels: Scope : Frontend

#2639 feat(gui-v2): sidebar
  packages/nc-gui-v2/assets/style-v2.css
  packages/nc-gui-v2/components/general/Language.vue
  packages/nc-gui-v2/components/general/Share.vue
  packages/nc-gui-v2/components/general/Social.vue
  packages/nc-gui-v2/components/general/Sponsors.vue
  packages/nc-gui-v2/pages/projects/index.vue
  packages/nc-gui-v2/pages/projects/index/index.vue
  packages/nc-gui-v2/public/social/email.png
  packages/nc-gui-v2/public/social/facebook.png
  packages/nc-gui-v2/public/social/google-plus.png
  packages/nc-gui-v2/public/social/googlemaps.png
  packages/nc-gui-v2/public/social/gov.uk.png
  packages/nc-gui-v2/public/social/instagram.png
  packages/nc-gui-v2/public/social/linkedin.png
  packages/nc-gui-v2/public/social/medium.png
  packages/nc-gui-v2/public/social/onthemarket.png
  packages/nc-gui-v2/public/social/pinterest.png
  packages/nc-gui-v2/public/social/png/douban.png
  packages/nc-gui-v2/public/social/png/facebook.png
  packages/nc-gui-v2/public/social/png/gmail.png
  packages/nc-gui-v2/public/social/png/google-plus.png
  packages/nc-gui-v2/public/social/png/line.png
  packages/nc-gui-v2/public/social/png/linkedin.png
  packages/nc-gui-v2/public/social/png/medium.png
  packages/nc-gui-v2/public/social/png/odnoklassniki.png
  packages/nc-gui-v2/public/social/png/renren.png
  packages/nc-gui-v2/public/social/png/skype.png
  packages/nc-gui-v2/public/social/png/telegram.png
  packages/nc-gui-v2/public/social/png/twitter.png
  packages/nc-gui-v2/public/social/png/viber.png
  packages/nc-gui-v2/public/social/png/vk.png
  packages/nc-gui-v2/public/social/png/wechat.png
  packages/nc-gui-v2/public/social/png/weibo.png
  packages/nc-gui-v2/public/social/png/whatsapp.png
  packages/nc-gui-v2/public/social/png/wykop.jpg
  packages/nc-gui-v2/public/social/reddit.png
  packages/nc-gui-v2/public/social/scribd.png
  packages/nc-gui-v2/public/social/snapchat.png
  packages/nc-gui-v2/public/social/tumblr.png
  packages/nc-gui-v2/public/social/twitter.png
  packages/nc-gui-v2/public/social/whatsapp.png
  packages/nc-gui-v2/public/social/zoopla.jpg
Labels: Scope : Frontend

#2622 Feat/guiv2 gallery fields filter sort
  packages/nc-gui-v2/components/cell/DateTimePicker.vue
  packages/nc-gui-v2/components/index.ts
  packages/nc-gui-v2/components/smartsheet-header/Cell.vue
  packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCellIcon.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilter.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldListAutoCompleteDropdown.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenuItem.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SortListMenu.vue
  packages/nc-gui-v2/components/smartsheet/Form.vue
  packages/nc-gui-v2/components/smartsheet/Gallery.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/Toolbar.vue
  packages/nc-gui-v2/components/smartsheet/VirtualCell.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/composables/useViewFilters.ts
  packages/nc-gui-v2/composables/useViewSorts.ts
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/utils/filterUtils.ts
  packages/nocodb-sdk/src/lib/Api.ts
  scripts/sdk/swagger.json
Labels: Scope : Frontend

#2643 feat(gui-v2): add dark mode to state and some styles
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/assets/style-v2.css
  packages/nc-gui-v2/components/general/ColorModeSwitcher.vue
  packages/nc-gui-v2/components/general/Sponsors.vue
  packages/nc-gui-v2/composables/useColors.ts
  packages/nc-gui-v2/composables/useGlobalState.ts
  packages/nc-gui-v2/pages/projects/index.vue
  packages/nc-gui-v2/pages/projects/index/list.vue
  packages/nc-gui-v2/plugins/state.ts
Labels: Scope : Frontend

#2645 feat(gui-v2): add sidebar switcher to header
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/composables/useGlobalState.ts
  packages/nc-gui-v2/lib/types.ts
  packages/nc-gui-v2/pages/projects/index.vue
  packages/nc-gui-v2/pages/projects/index/index.vue
Labels: Scope : Frontend

#2642 feat(gui-v2,testing): add vitest and a simple component test
  packages/nc-gui-v2/components/general/Sponsors.test.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/plugins/i18n.ts
  packages/nc-gui-v2/plugins/vuetify.ts
  packages/nc-gui-v2/test/vite.config.ts
  packages/nc-gui-v2/test/vuetify.config.js
Labels: Scope : Frontend

#2653 Feat/fields toggling
  packages/nc-gui-v2/components/index.ts
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/composables/useViewColumns.ts
Labels: Scope : Frontend

#2655 feat(gui-v2): url cell
  packages/nc-gui-v2/components/cell/Url.vue
  packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/utils/urlUtils.ts
Labels: Scope : Frontend

#2641 feat/add-dynamic-feedback-form-submission
  packages/nc-gui/components/FeedbackForm.vue
  packages/nc-gui/plugins/projectLoader.js
  packages/nc-gui/store/settings.js
  packages/nocodb/src/lib/meta/api/utilApis.ts
Labels: Status: Do Not Merge

#2651 feat(gui-v2): update signup form
  packages/nc-gui-v2/composables/useGlobalState.ts
  packages/nc-gui-v2/pages/signin.vue
  packages/nc-gui-v2/pages/signup.vue
Labels: Scope : Frontend

#2722 feat(gui-v2): add user settings page
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/general/Language.vue
  packages/nc-gui-v2/components/general/Sponsors.vue
  packages/nc-gui-v2/layouts/default.vue
  packages/nc-gui-v2/pages/index.vue
  packages/nc-gui-v2/pages/index/create-external.vue
  packages/nc-gui-v2/pages/index/create.vue
  packages/nc-gui-v2/pages/index/index.vue
  packages/nc-gui-v2/pages/index/index/index.vue
  packages/nc-gui-v2/pages/index/index/list.vue
  packages/nc-gui-v2/pages/index/user/index.vue
  packages/nc-gui-v2/pages/index/user/index/index.vue
  packages/nc-gui-v2/pages/projects/index.vue
  packages/nc-gui-v2/pages/signin.vue
  packages/nc-gui-v2/pages/signup.vue
  packages/nc-gui-v2/windi.config.ts
Labels: Scope : Frontend

#2729 Feat/project tree - add settings modal
  packages/nc-gui-v2/components/dashboard/TreeView.vue
Labels: Scope : Frontend

#2728 fix(gui-v2): sidebar showing when collapsed
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/pages/index/index.vue
Labels: Scope : Frontend

#2735 feat: add isUIAllowed composable
  packages/nc-gui-v2/composables/useUIPermission/index.ts
  packages/nc-gui-v2/composables/useUIPermission/rolePermissions.ts
  packages/nc-gui-v2/lib/enums.ts
  packages/nc-gui-v2/lib/types.ts
  packages/nc-gui/helpers/rolePermissions.js
Labels: Scope : Frontend

#2742 chore(gui-v2): update theme primary color
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
Labels: Scope : Frontend

#2744 refactor(gui-v2): replace vuetify form with ant form
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/general/NocoIcon.vue
  packages/nc-gui-v2/composables/useGlobalState.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/forgot-password.vue
  packages/nc-gui-v2/pages/index/index.vue
  packages/nc-gui-v2/pages/index/user/index.vue
  packages/nc-gui-v2/pages/index/user/index/index.vue
  packages/nc-gui-v2/pages/signin.vue
  packages/nc-gui-v2/pages/signup.vue
Labels: Scope : Frontend

#2757 chore(gui-v2): cleanup user settings page
  packages/nc-gui-v2/pages/index/index.vue
  packages/nc-gui-v2/pages/index/index/index.vue
  packages/nc-gui-v2/pages/index/index/list.vue
  packages/nc-gui-v2/pages/index/user/index.vue
  packages/nc-gui-v2/pages/index/user/index/index.vue
Labels: Scope : Frontend

#2758 refactor(gui-v2): disable dark mode
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/composables/useGlobalState.ts
Labels: Scope : Frontend, Scope: vue3

#2791 feat(gui-v2): load team and auth tab
  packages/nc-gui-v2/components/dashboard/TabView.vue
  packages/nc-gui-v2/components/tabs/Auth.vue
  packages/nc-gui-v2/composables/useTabs.ts
  packages/nc-gui-v2/pages/nc/[projectId].vue
Labels: Scope: vue3

#2796 feat(gui-v2): get project roles
  packages/nc-gui-v2/composables/useProject.ts
  packages/nc-gui-v2/composables/useUIPermission/index.ts
  packages/nc-gui-v2/lib/constants.ts
Labels: Scope: vue3

#2734 feat(gui-v2): add `AuditTab`
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/dashboard/settings/AuditTab.vue
  packages/nc-gui-v2/utils/dateTimeUtils.ts
Labels: Scope: vue3

#2803 refactor(gui-v2): move injection keys to context dir
  packages/nc-gui-v2/components/cell/Attachment.vue
  packages/nc-gui-v2/components/cell/Checkbox.vue
  packages/nc-gui-v2/components/cell/DateTimePicker.vue
  packages/nc-gui-v2/components/cell/Duration.vue
  packages/nc-gui-v2/components/cell/MultiSelect.vue
  packages/nc-gui-v2/components/cell/Rating.vue
  packages/nc-gui-v2/components/cell/SingleSelect.vue
  packages/nc-gui-v2/components/cell/Url.vue
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/dlg/TableCreate.vue
  packages/nc-gui-v2/components/dlg/ViewCreate.vue
  packages/nc-gui-v2/components/smartsheet-header/Cell.vue
  packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCell.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCellIcon.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilter.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldListAutoCompleteDropdown.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SortListMenu.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
  packages/nc-gui-v2/components/smartsheet/Gallery.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/Pagination.vue
  packages/nc-gui-v2/components/smartsheet/Sidebar.vue
  packages/nc-gui-v2/components/smartsheet/VirtualCell.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/components/virtual-cell/BelongsTo.vue
  packages/nc-gui-v2/components/virtual-cell/Formula.vue
  packages/nc-gui-v2/components/virtual-cell/HasMany.vue
  packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
  packages/nc-gui-v2/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui-v2/composables/useColumn.ts
  packages/nc-gui-v2/composables/useMetas.ts
  packages/nc-gui-v2/composables/useProject.ts
  packages/nc-gui-v2/composables/useTableCreate.ts
  packages/nc-gui-v2/composables/useViewData.ts
  packages/nc-gui-v2/context/index.ts
  packages/nc-gui-v2/pages/nc/[projectId].vue
Labels: Scope: vue3

#2811 refactor(gui-v2): accept projectId as arg in `useProject`
  packages/nc-gui-v2/composables/useProject.ts
Labels: Scope: vue3

#2830 refactor(gui-v2): cleanup project create utils
  packages/nc-gui-v2/lib/enums.ts
  packages/nc-gui-v2/lib/types.ts
  packages/nc-gui-v2/pages/index/index.vue
  packages/nc-gui-v2/pages/project/index/create-external.vue
  packages/nc-gui-v2/pages/signin.vue
  packages/nc-gui-v2/pages/signup.vue
  packages/nc-gui-v2/utils/projectCreateUtils.ts
Labels: Scope: vue3

#2828 refactor(gui-v2): cleanup template editor component
  packages/nc-gui-v2/components/template/Editor.vue
  packages/nc-gui-v2/components/template/utils.ts
Labels: Scope: vue3

#2750 feat(gui-v2): templates
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/template/Editor.vue
  packages/nc-gui-v2/components/template/utils.ts
Labels: Scope: vue3

#2794 Feat/nav drawer
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/dlg/TableRename.vue
  packages/nc-gui-v2/composables/useMetas.ts
  packages/nc-gui-v2/composables/useTabs.ts
  packages/nc-gui-v2/lib/enums.ts
  packages/nc-gui-v2/lib/types.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/index/index.vue
  packages/nc-gui-v2/pages/nc/[projectId].vue
  packages/nc-gui-v2/pages/project/index/create-external.vue
  packages/nc-gui-v2/pages/signin.vue
  packages/nc-gui-v2/pages/signup.vue
  packages/nc-gui-v2/utils/projectCreateUtils.ts
  packages/nc-gui-v2/utils/validation.ts
Labels: Scope: vue3

#2831 chore(gui-v2): fix eslint issues
  packages/nc-gui-v2/components/cell/Duration.vue
  packages/nc-gui-v2/components/cell/JsonEditableCell.vue
  packages/nc-gui-v2/components/cell/Time.vue
  packages/nc-gui-v2/components/dlg/TableCreate.vue
  packages/nc-gui-v2/components/smartsheet-header/VirtualCellIcon.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/LockMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SortListMenu.vue
  packages/nc-gui-v2/components/virtual-cell/components/ListChildItems.vue
  packages/nc-gui-v2/components/virtual-cell/components/ListChildItemsModal.vue
  packages/nc-gui-v2/components/virtual-cell/components/ListItems.vue
  packages/nc-gui-v2/composables/useViewCreate.ts
  packages/nc-gui-v2/plugins/i18n.ts
Labels: Scope: vue3

#2798 feat(gui-v2): App Store
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/dashboard/settings/AppStore.vue
  packages/nc-gui-v2/components/dashboard/settings/appStore/AppInstall.vue
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/public/plugins/aws.png
  packages/nc-gui-v2/public/plugins/backblaze.jpeg
  packages/nc-gui-v2/public/plugins/discord.png
  packages/nc-gui-v2/public/plugins/gcs.png
  packages/nc-gui-v2/public/plugins/linode.svg
  packages/nc-gui-v2/public/plugins/mailersend.svg
  packages/nc-gui-v2/public/plugins/mattermost.png
  packages/nc-gui-v2/public/plugins/minio.png
  packages/nc-gui-v2/public/plugins/ovhCloud.png
  packages/nc-gui-v2/public/plugins/s3.png
  packages/nc-gui-v2/public/plugins/scaleway.png
  packages/nc-gui-v2/public/plugins/slack.webp
  packages/nc-gui-v2/public/plugins/spaces.png
  packages/nc-gui-v2/public/plugins/teams.ico
  packages/nc-gui-v2/public/plugins/twilio.png
  packages/nc-gui-v2/public/plugins/upcloud.png
  packages/nc-gui-v2/public/plugins/vultr.png
  packages/nc-gui-v2/public/plugins/whatsapp.png
Labels: Scope: vue3

#2836 fix(gui-v2): force disable dark mode
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/composables/useGlobalState.ts
Labels: Scope: vue3

#2840 test: cypress markers for tab & tree view
  packages/nc-gui-v2/components/dashboard/TabView.vue
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/dashboard/settings/AppStore.vue
Labels: Scope: vue3

#2795 feat(gui-v2): quick import
  packages/nc-gui-v2/app.vue
  packages/nc-gui-v2/components.d.ts
  packages/nc-gui-v2/components/dashboard/TabView.vue
  packages/nc-gui-v2/components/dlg/AirtableImport.vue
  packages/nc-gui-v2/components/dlg/QuickImport.vue
  packages/nc-gui-v2/components/dlg/TableCreate.vue
  packages/nc-gui-v2/components/monaco/Editor.vue
  packages/nc-gui-v2/components/template/Editor.vue
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/utils/parsers/CSVTemplateAdapter.ts
  packages/nc-gui-v2/utils/parsers/ExcelTemplateAdapter.ts
  packages/nc-gui-v2/utils/parsers/ExcelUrlTemplateAdapter.ts
  packages/nc-gui-v2/utils/parsers/JSONTemplateAdapter.ts
  packages/nc-gui-v2/utils/parsers/JSONUrlTemplateAdapter.ts
  packages/nc-gui-v2/utils/parsers/TemplateGenerator.ts
  packages/nc-gui-v2/utils/parsers/index.ts
  packages/nc-gui-v2/utils/parsers/parserHelpers.ts
  packages/nc-gui-v2/utils/validation.ts
Labels: Scope: vue3

#2841 feat(gui-v2): Project metadata
  packages/nc-gui-v2/components/dashboard/settings/Metadata.vue
  packages/nc-gui-v2/components/dashboard/settings/SettingsModal.vue
  packages/nc-gui-v2/components/dashboard/settings/UIAcl.vue
Labels: Scope: vue3

#2819 fix(gui-v2): Main view ( tab view ) & Toolbar
  packages/nc-gui-v2/assets/style-v2.scss
  packages/nc-gui-v2/components/cell/TextArea.vue
  packages/nc-gui-v2/components/dashboard/TreeView.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/AddRow.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilter.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ColumnFilterMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/DeleteTable.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldListAutoCompleteDropdown.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/FieldsMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/LockMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/MoreActions.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/Reload.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SearchData.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ShareView.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/SortListMenu.vue
  packages/nc-gui-v2/components/smartsheet-toolbar/ToggleDrawer.vue
  packages/nc-gui-v2/components/smartsheet/Grid.vue
  packages/nc-gui-v2/components/smartsheet/Pagination.vue
  packages/nc-gui-v2/components/smartsheet/Toolbar.vue
  packages/nc-gui-v2/components/tabs/Smartsheet.vue
  packages/nc-gui-v2/components/virtual-cell/BelongsTo.vue
  packages/nc-gui-v2/components/virtual-cell/ManyToMany.vue
  packages/nc-gui-v2/composables/useTabs.ts
  packages/nc-gui-v2/composables/useViewColumns.ts
  packages/nc-gui-v2/context/index.ts
  packages/nc-gui-v2/nuxt.config.ts
  packages/nc-gui-v2/package-lock.json
  packages/nc-gui-v2/package.json
  packages/nc-gui-v2/pages/nc/[projectId]/index.vue
  packages/nc-gui-v2/pages/nc/[projectId]/index/index.vue
  packages/nc-gui-v2/pages/nc/[projectId]/index/index/[type]/[title]/[[viewTitle]].vue
  packages/nc-gui-v2/pages/nc/[projectId]/index/index/auth.vue
  packages/nc-gui-v2/pages/nc/[projectId]/index/index/index.vue
  packages/nc-gui-v2/pages/project/index/create-external.vue
  packages/nocodb-sdk/src/lib/helperFunctions.ts
Labels: Scope: vue3

#2888 feat(gui-v2): Email Cell
  packages/nc-gui-v2/components/cell/Email.vue
  packages/nc-gui-v2/components/smartsheet-header/CellIcon.vue
  packages/nc-gui-v2/components/smartsheet/Cell.vue
Labels: Scope: vue3
