Repository nocodb/nocodb, pull requests merged in 2023-11, with the labels that each got.

#6861 fix(nc-gui): column hash not updated on meta change
  packages/nc-gui/components/smartsheet/details/Fields.vue
Labels: 🛑 Status: Do Not Merge

#6935 fix: Issues related to filter
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/conditionV2.ts
Labels: trigger-CI

#6940 fix: Google OAuth based token generation logic correction
  packages/nc-gui/middleware/auth.global.ts
Labels: 🛑 Status: Do Not Merge

#7023 fix: on clicking table node navigate to default view
  packages/nc-gui/composables/useTableNew.ts
  packages/nc-gui/store/views.ts
Labels: 🚧 Status: Changes Requested

#7019 feat: Missing formula functions support
  packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
  packages/nc-gui/utils/formulaUtils.ts
  packages/nc-gui/utils/urlUtils.ts
  packages/noco-docs/docs/070.fields/040.field-types/060.formula/015.operators.md
  packages/noco-docs/docs/070.fields/040.field-types/060.formula/020.numeric-functions.md
  packages/noco-docs/docs/070.fields/040.field-types/060.formula/030.string-functions.md
  packages/nocodb-sdk/src/lib/formulaHelpers.ts
  packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts
  packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
  packages/nocodb/src/db/functionMappings/commonFns.ts
  packages/nocodb/src/db/functionMappings/mysql.ts
  packages/nocodb/src/db/functionMappings/pg.ts
  packages/nocodb/src/db/mapFunctionName.ts
  tests/playwright/.env.example
  tests/playwright/tests/db/columns/columnFormula.spec.ts
Labels: trigger-CI

#7054 Miscellaneous bug fixes/enhancements
  packages/nc-gui/components/cell/MultiSelect.vue
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/column/SelectOptions.vue
  packages/nc-gui/components/virtual-cell/Lookup.vue
  packages/nc-gui/components/virtual-cell/QrCode.vue
  packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/generateLookupSelectQuery.ts
  packages/nocodb/src/db/sortV2.ts
Labels: 🛑 Status: Do Not Merge, trigger-CI

#7044 Remove signup link from signup page if invite only signup enabled
  packages/nc-gui/composables/useGlobal/state.ts
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/pages/signin.vue
  packages/nocodb/src/models/Store.ts
  packages/nocodb/src/services/utils.service.ts
  packages/nocodb/src/utils/globals.ts
Labels: trigger-CI

#7070 fix: Validate select options before insert
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/services/columns.service.ts
  packages/nocodb/tests/unit/factory/column.ts
  packages/nocodb/tests/unit/rest/tests/filter.test.ts
Labels: 🛑 Status: Do Not Merge
