Repository nocodb/nocodb, pull requests merged in 2023-09, with the labels that each got.

#6311 fix: Add upgrader for creating missing LTAR index in metadb projects
  packages/nc-gui/components.d.ts
  packages/nocodb/src/modules/global/init-meta-service.provider.ts
  packages/nocodb/src/version-upgrader/NcUpgrader.ts
  packages/nocodb/src/version-upgrader/ncXcdbLTARIndexUpgrader.ts
Labels: trigger-CI

#6354 fix: project collaborators "Date Joined" is always "a few seconds ago"
  packages/nocodb/src/models/ProjectUser.ts
Labels: 👀 Status: In Review

#6370 Fixed Sidebar projectnode ctx menu
  packages/nc-gui/assets/nc-icons/star-remove.svg
  packages/nc-gui/assets/nc-icons/star.svg
  packages/nc-gui/components/cell/GeoData.vue
  packages/nc-gui/components/dashboard/Sidebar.vue
  packages/nc-gui/components/dashboard/Sidebar/TopSection.vue
  packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
  packages/nc-gui/components/dashboard/TreeView/BaseOptions.vue
  packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
  packages/nc-gui/components/dashboard/TreeView/TableNode.vue
  packages/nc-gui/components/dashboard/TreeView/index.vue
  packages/nc-gui/components/dashboard/View.vue
  packages/nc-gui/components/general/EmojiPicker.vue
  packages/nc-gui/components/general/Loader.vue
  packages/nc-gui/components/nc/Button.vue
  packages/nc-gui/components/nc/Divider.vue
  packages/nc-gui/components/nc/Dropdown.vue
  packages/nc-gui/components/nc/Menu.vue
  packages/nc-gui/components/nc/MenuItem.vue
  packages/nc-gui/components/nc/SubMenu.vue
  packages/nc-gui/components/smartsheet/sidebar/toolbar/Webhook.vue
  packages/nc-gui/components/workspace/CreateProjectDlg.vue
  packages/nc-gui/components/workspace/EmptyPlaceholder.vue
  packages/nc-gui/context/index.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/layouts/dashboard.vue
  packages/nc-gui/pages/index.vue
  packages/nc-gui/store/projects.ts
  packages/nc-gui/utils/iconUtils.ts
  tests/playwright/pages/Dashboard/TreeView.ts
  tests/playwright/pages/Dashboard/common/LeftSidebar/index.ts
  tests/playwright/pages/Dashboard/index.ts
  tests/playwright/pages/SharedForm/index.ts
  tests/playwright/pages/WorkspacePage/ContainerPage.ts
  tests/playwright/setup/index.ts
  tests/playwright/tests/db/columns/columnAttachments.spec.ts
Labels: 🛑 Status: Do Not Merge

#6387 fix(nc-gui): long text expand in shared view
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/smartsheet/Cell.vue
Labels: 👀 Status: In Review

#6390 fix(nc-gui): ui updates
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/cell/Email.vue
  packages/nc-gui/components/dashboard/Sidebar.vue
  packages/nc-gui/components/dashboard/Sidebar/TopSection.vue
  packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
  packages/nc-gui/components/general/WorkspaceIcon.vue
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nc-gui/components/smartsheet/column/AdvancedOptions.vue
  packages/nc-gui/components/smartsheet/column/SelectOptions.vue
  packages/nc-gui/components/smartsheet/header/CellIcon.ts
  packages/nc-gui/utils/cell.ts
  packages/nc-gui/utils/iconUtils.ts
Labels: 👀 Status: In Review

#6444 Removed right view sidebar
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/dashboard/Sidebar.vue
  packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
  packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
  packages/nc-gui/components/dashboard/TreeView/TableList.vue
  packages/nc-gui/components/dashboard/TreeView/TableNode.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsList.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue
  packages/nc-gui/components/dashboard/TreeView/index.vue
  packages/nc-gui/components/dashboard/View.vue
  packages/nc-gui/components/dlg/ViewCreate.vue
  packages/nc-gui/components/general/DeleteModal.vue
  packages/nc-gui/components/nc/Select.vue
  packages/nc-gui/components/project/AllTables.vue
  packages/nc-gui/components/smartsheet/grid/GroupBy.vue
  packages/nc-gui/components/smartsheet/sidebar/MenuBottom.vue
  packages/nc-gui/components/smartsheet/sidebar/index.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/components/tabs/SmartsheetResizable.vue
  packages/nc-gui/composables/useViewData.ts
  packages/nc-gui/context/index.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/lib/acl.ts
  packages/nc-gui/pages/index/[typeOrId]/[projectId]/index/index/index.vue
  packages/nc-gui/pages/index/[typeOrId]/view/[viewId].vue
  packages/nc-gui/store/tables.ts
  packages/nc-gui/store/views.ts
  packages/nc-gui/utils/baseUtils.ts
  tests/playwright/pages/Dashboard/Grid/Column/LTAR/LinkRecord.ts
  tests/playwright/pages/Dashboard/Sidebar/index.ts
  tests/playwright/pages/Dashboard/TreeView.ts
  tests/playwright/pages/Dashboard/ViewSidebar/index.ts
  tests/playwright/pages/Dashboard/common/Cell/index.ts
  tests/playwright/pages/Dashboard/common/Topbar/Share.ts
  tests/playwright/pages/Dashboard/common/Topbar/index.ts
  tests/playwright/pages/Dashboard/index.ts
  tests/playwright/pages/SharedForm/index.ts
  tests/playwright/tests/db/columns/columnAttachments.spec.ts
  tests/playwright/tests/db/features/baseShare.spec.ts
  tests/playwright/tests/db/features/undo-redo.spec.ts
  tests/playwright/tests/db/general/toolbarOperations.spec.ts
  tests/playwright/tests/db/general/views.spec.ts
  tests/playwright/tests/db/views/viewForm.spec.ts
  tests/playwright/tests/db/views/viewKanban.spec.ts
Labels: 🛑 Status: Do Not Merge

#6455 Font switched to manrope
  packages/nc-gui/assets/css/global.css
  packages/nc-gui/assets/style.scss
  packages/nc-gui/assets/style/fonts.css
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-100.eot
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-100.svg
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-100.ttf
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-100.woff
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-100.woff2
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-200.eot
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-200.svg
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-200.ttf
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-200.woff
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-200.woff2
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-300.eot
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-300.svg
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-300.ttf
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-300.woff
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-300.woff2
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-500.eot
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-500.svg
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-500.ttf
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-500.woff
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-500.woff2
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-600.eot
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-600.svg
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-600.ttf
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-600.woff
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-600.woff2
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-700.eot
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-700.svg
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-700.ttf
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-700.woff
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-700.woff2
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-800.eot
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-800.svg
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-800.ttf
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-800.woff
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-800.woff2
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-900.eot
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-900.svg
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-900.ttf
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-900.woff
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-900.woff2
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-regular.eot
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-regular.svg
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-regular.ttf
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-regular.woff
  packages/nc-gui/assets/style/inter/inter-v12-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-regular.woff2
  packages/nc-gui/assets/style/manrope/Manrope-VariableFont_wght.ttf
  packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
  packages/nc-gui/components/nc/Button.vue
  packages/nc-gui/components/nc/MenuItem.vue
  packages/nc-gui/components/smartsheet/topbar/SelectMode.vue
Labels: 🛑 Status: Do Not Merge

#6474 Added Mobile responsive
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/dashboard/Sidebar.vue
  packages/nc-gui/components/dashboard/Sidebar/Header.vue
  packages/nc-gui/components/dashboard/Sidebar/TopSection.vue
  packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
  packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
  packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
  packages/nc-gui/components/dashboard/TreeView/TableList.vue
  packages/nc-gui/components/dashboard/TreeView/TableNode.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsList.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue
  packages/nc-gui/components/dashboard/View.vue
  packages/nc-gui/components/dlg/ViewCreate.vue
  packages/nc-gui/components/general/EmojiPicker.vue
  packages/nc-gui/components/general/OpenLeftSidebarBtn.vue
  packages/nc-gui/components/general/ShareProject.vue
  packages/nc-gui/components/nc/Button.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/Pagination.vue
  packages/nc-gui/components/smartsheet/Toolbar.vue
  packages/nc-gui/components/smartsheet/Topbar.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/MappedBy.vue
  packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
  packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/StackedBy.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/composables/useTableNew.ts
  packages/nc-gui/layouts/base.vue
  packages/nc-gui/layouts/dashboard.vue
  packages/nc-gui/lib/constants.ts
  packages/nc-gui/pages/index/[typeOrId]/[projectId]/index/index/index.vue
  packages/nc-gui/store/config.ts
  packages/nc-gui/store/sidebar.ts
  packages/nc-gui/store/views.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/nc-gui/windi.config.ts
Labels: 🛑 Status: Do Not Merge

#6490 Mobile responsive followup
  packages/nc-gui/assets/nc-icons/comment_here.svg
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
  packages/nc-gui/components/dashboard/TreeView/TableNode.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue
  packages/nc-gui/components/dashboard/View.vue
  packages/nc-gui/components/general/OpenLeftSidebarBtn.vue
  packages/nc-gui/components/nc/Dropdown.vue
  packages/nc-gui/components/nc/MenuItem.vue
  packages/nc-gui/components/nc/Modal.vue
  packages/nc-gui/components/nc/Pagination.vue
  packages/nc-gui/components/smartsheet/Pagination.vue
  packages/nc-gui/components/smartsheet/Topbar.vue
  packages/nc-gui/components/smartsheet/expanded-form/Comments.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/components/smartsheet/grid/index.vue
  packages/nc-gui/composables/useViewData.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/plugins/font.ts
  packages/nc-gui/store/views.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/nc-gui/windi.config.ts
  tests/playwright/pages/Dashboard/Grid/index.ts
  tests/playwright/pages/Dashboard/common/Footbar/index.ts
  tests/playwright/playwright.config.ts
  tests/playwright/quickTests/commonTest.ts
  tests/playwright/tests/db/features/pagination.spec.ts
Labels: 🛑 Status: Do Not Merge

#6499 Test fix
  packages/nc-gui/components.d.ts
  packages/nc-gui/components/general/DeleteModal.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nocodb/package.json
  pnpm-lock.yaml
  tests/playwright/package.json
  tests/playwright/pages/Account/Users.ts
  tests/playwright/pages/Dashboard/ExpandedForm/index.ts
  tests/playwright/pages/Dashboard/Form/index.ts
  tests/playwright/pages/Dashboard/Grid/Group.ts
  tests/playwright/pages/Dashboard/Grid/index.ts
  tests/playwright/pages/Dashboard/TreeView.ts
  tests/playwright/pages/Dashboard/ViewSidebar/index.ts
  tests/playwright/pages/Dashboard/common/Cell/AttachmentCell.ts
  tests/playwright/pages/Dashboard/common/Cell/CheckboxCell.ts
  tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
  tests/playwright/pages/Dashboard/index.ts
  tests/playwright/tests/db/features/expandedFormUrl.spec.ts
  tests/playwright/tests/db/features/metaLTAR.spec.ts
  tests/playwright/tests/db/features/verticalFillHandle.spec.ts
  tests/playwright/tests/db/general/projectOperations.spec.ts
  tests/playwright/tests/db/usersAccounts/accountUserManagement.spec.ts
Labels: 🛑 Status: Do Not Merge

#6470 New data apis - followup
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/CustomKnex.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/data-table.service.ts
  packages/nocodb/src/utils/common/NcConnectionMgrv2.ts
  packages/nocodb/tests/unit/rest/tests/newDataApis.test.ts
  packages/nocodb/tests/unit/rest/tests/tableRow.test.ts
  tests/playwright/tests/db/features/verticalFillHandle.spec.ts
  tests/playwright/tests/db/features/webhook.spec.ts
  tests/playwright/tests/utils/general.ts
Labels: trigger-CI

#6489 feat: Add group by support on virtual columns
  packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue
  packages/nc-gui/composables/useViewGroupBy.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/generateBTLookupSelectQuery.ts
  packages/nocodb/tests/unit/factory/column.ts
  packages/nocodb/tests/unit/rest/tests/groupby.test.ts
  packages/nocodb/tests/unit/rest/tests/tableRow.test.ts
  packages/nocodb/tests/unit/rest/tests/viewRow.test.ts
  tests/playwright/startPlayWrightServer.sh
  tests/playwright/tests/db/general/groupCRUD.spec.ts
Labels: trigger-CI

#6498 Mobile UI fixes
  packages/nc-gui/assets/nc-icons/download.svg
  packages/nc-gui/components/dashboard/Sidebar.vue
  packages/nc-gui/components/dashboard/Sidebar/TopSection.vue
  packages/nc-gui/components/dashboard/TreeView/TableNode.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsList.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue
  packages/nc-gui/components/dashboard/View.vue
  packages/nc-gui/components/nc/MenuItem.vue
  packages/nc-gui/components/nc/Pagination.vue
  packages/nc-gui/components/project/AllTables.vue
  packages/nc-gui/components/smartsheet/Toolbar.vue
  packages/nc-gui/components/smartsheet/expanded-form/Comments.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/smartsheet/grid/index.vue
  packages/nc-gui/components/smartsheet/header/Cell.vue
  packages/nc-gui/components/smartsheet/toolbar/OpenViewSidebarBtn.vue
  packages/nc-gui/lang/en.json
  packages/nc-gui/store/sidebar.ts
  tests/playwright/pages/Dashboard/Form/index.ts
  tests/playwright/pages/Dashboard/Kanban/index.ts
  tests/playwright/pages/Dashboard/common/LeftSidebar/index.ts
  tests/playwright/pages/Dashboard/common/WorkspaceMenu/index.ts
  tests/playwright/pages/Dashboard/index.ts
  tests/playwright/tests/db/columns/columnAttachments.spec.ts
  tests/playwright/tests/db/features/baseShare.spec.ts
  tests/playwright/tests/db/features/verticalFillHandle.spec.ts
Labels: 🛑 Status: Do Not Merge

#6519 i18n followup
  packages/nc-gui/components/account/Profile.vue
  packages/nc-gui/components/api-client/Headers.vue
  packages/nc-gui/components/api-client/Params.vue
  packages/nc-gui/components/cell/Currency.vue
  packages/nc-gui/components/cell/DatePicker.vue
  packages/nc-gui/components/cell/DateTimePicker.vue
  packages/nc-gui/components/cell/Decimal.vue
  packages/nc-gui/components/cell/Duration.vue
  packages/nc-gui/components/cell/Email.vue
  packages/nc-gui/components/cell/Float.vue
  packages/nc-gui/components/cell/Integer.vue
  packages/nc-gui/components/cell/Json.vue
  packages/nc-gui/components/cell/MultiSelect.vue
  packages/nc-gui/components/cell/Percent.vue
  packages/nc-gui/components/cell/PhoneNumber.vue
  packages/nc-gui/components/cell/SingleSelect.vue
  packages/nc-gui/components/cell/Text.vue
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/cell/TimePicker.vue
  packages/nc-gui/components/cell/Url.vue
  packages/nc-gui/components/cell/YearPicker.vue
  packages/nc-gui/components/shared-view/AskPassword.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/column/BarcodeOptions.vue
  packages/nc-gui/components/smartsheet/column/CurrencyOptions.vue
  packages/nc-gui/components/smartsheet/column/DateOptions.vue
  packages/nc-gui/components/smartsheet/column/DateTimeOptions.vue
  packages/nc-gui/components/smartsheet/column/DecimalOptions.vue
  packages/nc-gui/components/smartsheet/column/DefaultValue.vue
  packages/nc-gui/components/smartsheet/column/DurationOptions.vue
  packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
  packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
  packages/nc-gui/components/smartsheet/column/LookupOptions.vue
  packages/nc-gui/components/smartsheet/column/PercentOptions.vue
  packages/nc-gui/components/smartsheet/column/PgBinaryOptions.vue
  packages/nc-gui/components/smartsheet/column/QrCodeOptions.vue
  packages/nc-gui/components/smartsheet/column/RatingOptions.vue
  packages/nc-gui/components/smartsheet/column/RollupOptions.vue
  packages/nc-gui/components/smartsheet/column/SelectOptions.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/components/smartsheet/grid/index.vue
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
  packages/nc-gui/components/virtual-cell/QrCode.vue
  packages/nc-gui/components/webhook/Editor.vue
  packages/nc-gui/lang/en.json
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId].vue
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue
  packages/nc-gui/pages/signup/[[token]].vue
Labels: 🛑 Status: Do Not Merge

#6524 PW Worker count for each dbtype in CI changed
  .github/workflows/ci-cd.yml
  tests/playwright/package.json
  tests/playwright/pages/Dashboard/Form/index.ts
  tests/playwright/pages/Dashboard/Grid/Row.ts
  tests/playwright/playwright.config.ts
  tests/playwright/tests/db/features/undo-redo.spec.ts
Labels: 🛑 Status: Do Not Merge
