Repository nocodb/nocodb, pull requests merged in 2023-06, with the labels that each got.

#5863 test: use meta-db project for non-sakila db
  packages/nocodb/src/controllers/test/TestResetService/resetMetaSakilaSqliteProject.ts
Labels: trigger-CI

#5884 fix: avoid adding undo if delete fails
  packages/nc-gui/composables/useViewData.ts
Labels: 👀 Status: In Review

#5874 refactor: MetaDB LTAR revamp
  packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
  packages/nc-gui/composables/useColumnCreateStore.ts
  packages/nc-gui/composables/useTable.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/sql-client/lib/sqlite/SqliteClient.ts
  packages/nocodb/src/db/sql-mgr/v2/ProjectMgrv2.ts
  packages/nocodb/src/db/sql-mgr/v2/SqlMgrv2.ts
  packages/nocodb/src/meta/meta.service.ts
  packages/nocodb/src/middlewares/extract-project-id/extract-project-id.middleware.ts
  packages/nocodb/src/models/Column.ts
  packages/nocodb/src/models/Model.ts
  packages/nocodb/src/models/Project.ts
  packages/nocodb/src/models/View.ts
  packages/nocodb/src/modules/global/init-meta-service.provider.ts
  packages/nocodb/src/services/columns.service.ts
  packages/nocodb/src/services/datas.service.ts
  packages/nocodb/src/services/tables.service.ts
  packages/nocodb/src/version-upgrader/NcUpgrader.ts
  packages/nocodb/src/version-upgrader/ncFilterUpgrader_0104004.ts
  packages/nocodb/src/version-upgrader/ncXcdbLTARUpgrader.ts
  packages/nocodb/tests/unit/rest/tests/tableRow.test.ts
  packages/nocodb/tests/unit/rest/tests/viewRow.test.ts
  tests/playwright/pages/Dashboard/Grid/index.ts
  tests/playwright/setup/xcdbProject.ts
  tests/playwright/tests/db/metaLTAR.spec.ts
  tests/playwright/tests/db/timezone.spec.ts
Labels: 🛑 Status: Do Not Merge

#5942 test: add demo table as sub routine
  tests/playwright/setup/demoTable.ts
  tests/playwright/tests/db/filters.spec.ts
Labels: trigger-CI

#5928 feat: bulk update records using UI
  packages/nc-gui/components/dlg/BulkUpdate.vue
  packages/nc-gui/components/smartsheet/Grid.vue
  packages/nc-gui/composables/useViewData.ts
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/schema/swagger.json
  tests/playwright/pages/Dashboard/BulkUpdate/index.ts
  tests/playwright/pages/Dashboard/Grid/index.ts
  tests/playwright/pages/Dashboard/common/Cell/SelectOptionCell.ts
  tests/playwright/pages/Dashboard/common/Cell/TimeCell.ts
  tests/playwright/pages/Dashboard/common/Cell/YearCell.ts
  tests/playwright/pages/Dashboard/common/Cell/index.ts
  tests/playwright/pages/Dashboard/index.ts
  tests/playwright/setup/demoTable.ts
  tests/playwright/tests/db/bulkUpdate.spec.ts
  tests/playwright/tests/db/projectOperations.spec.ts
Labels: 🛑 Status: Do Not Merge

#5896 feat: vertical fill using handle
  packages/nc-gui/components/cell/DatePicker.vue
  packages/nc-gui/components/cell/DateTimePicker.vue
  packages/nc-gui/components/cell/TimePicker.vue
  packages/nc-gui/components/cell/YearPicker.vue
  packages/nc-gui/components/smartsheet/Grid.vue
  packages/nc-gui/components/smartsheet/TableDataCell.vue
  packages/nc-gui/composables/useMultiSelect/cellRange.ts
  packages/nc-gui/composables/useMultiSelect/index.ts
  tests/playwright/pages/Dashboard/common/Cell/AttachmentCell.ts
  tests/playwright/pages/Dashboard/common/Cell/RatingCell.ts
  tests/playwright/pages/Dashboard/common/Cell/SelectOptionCell.ts
  tests/playwright/pages/Dashboard/common/Cell/TimeCell.ts
  tests/playwright/tests/db/verticalFillHandle.spec.ts
Labels: 🛑 Status: Do Not Merge
