Repository nocodb/nocodb, pull requests merged in 2024-10, with the labels that each got.

#9537 feat: add sqlite support in the upstall script
  docker-compose/1_Auto_Upstall/noco.sh
Labels: 🔦 Type: Feature, size:XXL, lgtm

#9575 fix: cmdk improvements
  packages/nc-gui/components/cmd-k/index.vue
  packages/nc-gui/composables/useCommandPalette/index.ts
  packages/nc-gui/utils/filterUtils.ts
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/src/helpers/commandPaletteHelpers.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
  packages/nocodb/src/services/api-docs/swaggerV2/swagger-base.json
  packages/nocodb/src/services/command-palette.service.ts
  tests/playwright/pages/Dashboard/Command/CmdKPage.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9573 Nc fix/duplicate name update
  packages/nc-gui/components/dashboard/TreeView/TableNode.vue
  packages/nc-gui/components/dlg/ViewCreate.vue
  packages/nc-gui/components/smartsheet/details/Fields.vue
  packages/nc-gui/composables/useTableNew.ts
  packages/nc-gui/store/webhooks.ts
  packages/nc-gui/utils/generateName.ts
  packages/nocodb/src/services/integrations.service.ts
  tests/playwright/tests/db/features/multiFieldEditor.spec.ts
  tests/playwright/tests/db/views/viewKanban.spec.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9323 Nc product feed
  packages/nc-gui/assets/nc-icons/discord.svg
  packages/nc-gui/assets/nc-icons/megaphone.svg
  packages/nc-gui/assets/nc-icons/nocodb.svg
  packages/nc-gui/assets/nc-icons/reddit.svg
  packages/nc-gui/assets/nc-icons/refresh-cw.svg
  packages/nc-gui/assets/nc-icons/star.svg
  packages/nc-gui/assets/nc-icons/twitter-x-line.svg
  packages/nc-gui/assets/nc-icons/youtube2.svg
  packages/nc-gui/components/dashboard/Sidebar.vue
  packages/nc-gui/components/dashboard/Sidebar/Feed.vue
  packages/nc-gui/components/feed/Changelog/Item.vue
  packages/nc-gui/components/feed/Changelog/index.vue
  packages/nc-gui/components/feed/Error.vue
  packages/nc-gui/components/feed/Header.vue
  packages/nc-gui/components/feed/Recents/Card.vue
  packages/nc-gui/components/feed/Recents/index.vue
  packages/nc-gui/components/feed/Roadmap.vue
  packages/nc-gui/components/feed/Social.vue
  packages/nc-gui/components/feed/Twitter.vue
  packages/nc-gui/components/feed/View.vue
  packages/nc-gui/components/feed/Youtube/Player.vue
  packages/nc-gui/components/feed/Youtube/index.vue
  packages/nc-gui/components/nc/Badge.vue
  packages/nc-gui/components/nc/Popover.vue
  packages/nc-gui/components/smartsheet/Toolbar.vue
  packages/nc-gui/components/smartsheet/Topbar.vue
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/composables/useProductFeed.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/layouts/shared-view.vue
  packages/nc-gui/lib/types.ts
  packages/nc-gui/package.json
  packages/nc-gui/pages/index/[typeOrId]/feed.vue
  packages/nc-gui/plugins/animation.ts
  packages/nc-gui/store/workspace.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/nc-gui/utils/urlUtils.ts
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/package.json
  packages/nocodb/src/controllers/utils.controller.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/utils.service.ts
  packages/nocodb/src/utils/globals.ts
  packages/nocodb/src/utils/tele.ts
  pnpm-lock.yaml
Labels: 🔦 Type: Feature, size:XXL, lgtm

#9579 fix: product feed fixes
  packages/nc-gui/components/dashboard/Sidebar/Feed.vue
  packages/nc-gui/components/feed/Error.vue
  packages/nc-gui/components/feed/Recents/index.vue
  packages/nc-gui/components/feed/Twitter.vue
  packages/nc-gui/composables/useProductFeed.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9585 Nc fix: add tab key to query params
  packages/nc-gui/components/feed/Social.vue
  packages/nc-gui/components/feed/View.vue
Labels: 🐛 Type: Bug, size:S, lgtm

#9580 ColumnFilter ToolBar Correctly Show I18n string and LanguageAlias for zh_Hans
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
  packages/nc-gui/lib/enums.ts
Labels: 🐛 Type: Bug, ✈️ Type: i18n translation, size:XS, lgtm

#9588 fix: events
  packages/nc-gui/components/dashboard/Sidebar/Feed.vue
  packages/nc-gui/components/feed/Recents/Card.vue
  packages/nc-gui/components/feed/Social.vue
  packages/nc-gui/components/feed/View.vue
  packages/nc-gui/components/feed/Youtube/Player.vue
  packages/nc-gui/components/feed/Youtube/index.vue
Labels: 🐛 Type: Bug, size:M, lgtm

#9591 feat: Postgres base as schema
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/nocodb/.npmignore
  packages/nocodb/src/helpers/initBaseBehaviour.ts
  packages/nocodb/src/providers/init-meta-service.provider.ts
  packages/nocodb/src/services/bases.service.ts
Labels: 🔦 Type: Feature, size:L, lgtm

#9586 Nc fix: skip confirmation modal for duplicate view
  packages/nc-gui/components/dashboard/TreeView/TableNode.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
  packages/nc-gui/store/views.ts
  tests/playwright/pages/Dashboard/ViewSidebar/index.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9592 Nc fix/add to fav bug
  packages/nocodb/src/models/BaseUser.ts
  packages/nocodb/src/services/base-users/base-users.service.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9599 Nc fix/add to fav bug followup
  packages/nocodb/src/models/BaseUser.ts
  packages/nocodb/src/services/base-users/base-users.service.ts
Labels: size:M, lgtm

#9594 refactor: nc-secret-mgr cli followup
  .github/workflows/release-secret-cli.yml
  packages/nc-secret-mgr/.eslintrc.js
  packages/nc-secret-mgr/.npmignore
  packages/nc-secret-mgr/.prettierrc
  packages/nc-secret-mgr/dist/cli.js
  packages/nc-secret-mgr/package.json
  packages/nc-secret-mgr/src/core/NcConfig.ts
  packages/nc-secret-mgr/src/core/NcError.ts
  packages/nc-secret-mgr/src/core/SecretManager.ts
  packages/nc-secret-mgr/src/core/logger.ts
  packages/nc-secret-mgr/src/nocodb/cli.js
  packages/noco-docs/docs/100.data-sources/050.updating-secret.md
  packages/nocodb/package.json
  packages/nocodb/src/db/sql-client/lib/ee/SqlClientFactoryEE.ts
  packages/nocodb/src/utils/getInstance.ts
  packages/nocodb/src/utils/globals.ts
  pnpm-lock.yaml
  scripts/pkg-executable/package.json
Labels: 🧱 Type: Refactoring, size:L, lgtm

#9600 fix(nc-gui): Prevent keyboard shortcuts if user is in cell edit mode or any other active input element
  packages/nc-gui/components/cell/Currency.vue
  packages/nc-gui/components/cell/Decimal.vue
  packages/nc-gui/components/cell/Duration.vue
  packages/nc-gui/components/cell/Email.vue
  packages/nc-gui/components/cell/Float.vue
  packages/nc-gui/components/cell/Integer.vue
  packages/nc-gui/components/cell/Json.vue
  packages/nc-gui/components/cell/Percent.vue
  packages/nc-gui/components/cell/PhoneNumber.vue
  packages/nc-gui/components/cell/RichText.vue
  packages/nc-gui/components/cell/Text.vue
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/cell/Url.vue
  packages/nc-gui/components/dashboard/TreeView/index.vue
  packages/nc-gui/components/general/FullScreen.vue
  packages/nc-gui/components/smartsheet/details/Fields.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/store/projectsShortcuts.ts
  packages/nc-gui/utils/browserUtils.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9528 refactor: GUI error handling
  packages/nc-gui/components/nc/ErrorBoundary.vue
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/nuxt-shim.d.ts
  packages/nc-gui/plugins/error-reporting.ts
  packages/nc-gui/plugins/sentry.ts
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/src/controllers/utils.controller.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/utils.service.ts
Labels: 🛑 Status: Do Not Merge, 🧱 Type: Refactoring, size:L, lgtm

#9601 refactor: Change Postgres as schema environment key
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/nocodb/src/helpers/initBaseBehaviour.ts
  packages/nocodb/src/services/bases.service.ts
  packages/nocodb/src/utils/getInstance.ts
Labels: 🧱 Type: Refactoring, size:M, lgtm

#9607 fix: Integration encryption bug
  packages/nocodb/src/helpers/initDataSourceEncryption.ts
Labels: 🐛 Type: Bug, 🌞 Scope : Data source, size:XS, lgtm

#9608 refactor: Add logs for encryption - upgrader and init logic
  packages/nocodb/src/Noco.ts
  packages/nocodb/src/helpers/initDataSourceEncryption.ts
  packages/nocodb/src/version-upgrader/upgraders/0225002_ncDatasourceDecrypt.ts
Labels: 🧱 Type: Refactoring, size:S, lgtm

#9610 fix: Integration encryption - handle stringified config value
  packages/nocodb/src/helpers/initDataSourceEncryption.ts
  packages/nocodb/src/utils/encryptDecrypt.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9604 fix(docs): broken fenced code blocks and indentation
  packages/nocodb/README.md
Labels: 📋 Scope : Docs, size:S, lgtm

#9609 Nc feat/enable conditional field in oss
  packages/nc-gui/components/cell/Currency.vue
  packages/nc-gui/components/cell/Decimal.vue
  packages/nc-gui/components/cell/Duration.vue
  packages/nc-gui/components/cell/Email.vue
  packages/nc-gui/components/cell/Float.vue
  packages/nc-gui/components/cell/Integer.vue
  packages/nc-gui/components/cell/Percent.vue
  packages/nc-gui/components/cell/PhoneNumber.vue
  packages/nc-gui/components/cell/Text.vue
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/cell/Url.vue
  packages/nc-gui/components/smartsheet/form/field-config-error.vue
  packages/nc-gui/components/smartsheet/form/field-settings/visibility.vue
  packages/nc-gui/composables/useFormViewStore.ts
  packages/nc-gui/lib/form.ts
  packages/nocodb/src/models/Filter.ts
  tests/playwright/tests/db/views/viewForm.spec.ts
Labels: 🔦 Type: Feature, size:XL, lgtm

#9612 Nc fix(nc-gui): form redirect url issue
  packages/nc-gui/composables/useSharedFormViewStore.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9614 chore: add AI mention to translations
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/en.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hant.json
Labels: size:M, lgtm

#9480 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/km.json
  packages/nc-gui/lang/kn.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/ml.json
  packages/nc-gui/lang/ne.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ro.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:XXL, lgtm

#9616 fix: encode primary key before sending PATCH request
  packages/nc-gui/composables/useData.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9618 fix: Encode id to handle special chars
  packages/nc-gui/composables/useCalendarViewStore.ts
  packages/nc-gui/composables/useKanbanViewStore.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9627 New Crowdin updates
  packages/nc-gui/lang/tr.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9628 fix: language support for kn, ml
  packages/nc-gui/lib/enums.ts
  tests/playwright/tests/db/features/language.spec.ts
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9617 chore: Upstall script test file path correction
  .github/workflows/bats-test.yml
Labels: size:XS, lgtm

#9632 test: fix upstall bats tests
  docker-compose/1_Auto_Upstall/tests/expects/install/redis.sh
  docker-compose/1_Auto_Upstall/tests/expects/install/scale.sh
  docker-compose/1_Auto_Upstall/tests/expects/install/watchtower.sh
Labels: size:XS, lgtm

#9605 refactor: pnpm
  .github/workflows/ci-cd.yml
  .github/workflows/jest-unit-test.yml
  .github/workflows/playwright-test-workflow.yml
  .github/workflows/pre-build-for-playwright.yml
  .github/workflows/release-docker.yml
  .github/workflows/release-npm.yml
  .github/workflows/release-secret-cli.yml
  .github/workflows/sync-to-develop.yml
  .github/workflows/unit-test.yml
  .github/workflows/update-sdk-path.yml
  packages/nc-gui/package.json
  packages/nc-lib-gui/package-lock.json
  packages/nc-mail-templates/package.json
  packages/nc-secret-mgr/package.json
  packages/nocodb-sdk/pnpm-lock.yaml
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 🧱 Type: Refactoring, size:XL, lgtm

#9640 fix(nc-gui): conditional fields, show field alias if configured instead of actual field name
  packages/nc-gui/components/smartsheet/form/field-settings/visibility.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue
  packages/nc-gui/context/index.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9613 feat: poll notifications from single tab
  packages/nc-gui/composables/useSharedExecutionFn.ts
  packages/nc-gui/store/notification.ts
Labels: 🔦 Type: Feature, size:L, lgtm

#9645 Chore/timely docker build
  .github/workflows/release-nightly-dev.yml
  .github/workflows/release-pr.yml
  .github/workflows/release-timely-docker.yml
  packages/nocodb/Dockerfile.timely
  packages/nocodb/src/run/timely.ts
  packages/nocodb/src/services/utils.service.ts
  packages/nocodb/src/utils/TeleBatchProcessor.ts
  packages/nocodb/src/utils/tele.ts
  packages/nocodb/webpack.timely.config.js
Labels: size:L, lgtm

#9631 Add service Label to NocoDB image for compatibility with Kamal
  .github/workflows/release-docker.yml
Labels: 🔦 Type: Feature, size:XS, lgtm

#9646 New Crowdin updates
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/vi.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9647 Nc include cloud release
  packages/nc-gui/components/feed/Recents/Card.vue
  packages/nc-gui/components/feed/Recents/index.vue
  packages/nc-gui/lib/types.ts
Labels: 🔦 Type: Feature, size:S, lgtm

#9629 Nc cloud/changelog
  packages/nc-gui/components/feed/Changelog/index.vue
  packages/nc-gui/components/feed/Error.vue
  packages/nc-gui/components/feed/View.vue
  packages/nc-gui/composables/useProductFeed.ts
  packages/nc-gui/lib/types.ts
  packages/nocodb/src/schema/swagger.json
Labels: size:M, lgtm

#7412 Added one-click deploy template for RepoCloud.io
  README.md
Labels: lgtm

#9648 chore: Optimize timely docker build time
  .github/workflows/release-timely-docker.yml
  packages/nocodb/Dockerfile.timely
  packages/nocodb/package.json
Labels: 🔭 Type: Optimization, size:M, lgtm

#9654 enhancement: increase file size limit to 25MB in QuickImport.vue (ref: #5858)
  packages/nc-gui/components/dlg/QuickImport.vue
Labels: ✨ Type: Enhancement, size:XS, lgtm

#9482 feat: Added Elestio as one-click deploy option
  README.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9642 AWS IAM Role support
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/nocodb/src/helpers/NcPluginMgrv2.ts
  packages/nocodb/src/plugins/GenericS3/GenericS3.ts
  packages/nocodb/src/plugins/s3/S3.ts
  packages/nocodb/src/plugins/s3/index.ts
Labels: 🐛 Type: Bug, 🔦 Type: Feature, size:L, lgtm

#9657 New Crowdin updates
  packages/nc-gui/lang/ko.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9659 fix: Single/Multi select filter GUI improvements
  packages/nc-gui/components/cell/MultiSelect.vue
  packages/nc-gui/components/cell/SingleSelect.vue
  packages/nc-gui/components/smartsheet/toolbar/FilterInput.vue
Labels: 👓 Scope : View, size:XS, lgtm

#9663 New Crowdin updates
  packages/nc-gui/lang/ko.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9662 fix: Resolve GUI hang issues in formula creation interface
  packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
Labels: size:M, lgtm

#9661 Add fallback mechanism in decrypt upgrader
  packages/noco-docs/docs/100.data-sources/050.updating-secret.md
  packages/nocodb/src/version-upgrader/upgraders/0225002_ncDatasourceDecrypt.ts
Labels: size:M, lgtm

#9660 Nc fix/api corrections
  packages/nc-gui/components/cell/Checkbox.vue
  packages/nc-gui/components/cell/Rating.vue
  packages/nc-gui/components/smartsheet/column/CheckboxOptions.vue
  packages/nc-gui/components/smartsheet/column/RatingOptions.vue
  packages/nc-gui/helpers/columnDefaultMeta.ts
  packages/nc-gui/utils/columnUtils.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.controller.ts
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/columns.service.ts
  packages/nocodb/src/services/tables.service.ts
  packages/nocodb/tests/unit/rest/tests/table.test.ts
Labels: size:L, lgtm

#9666 docs: README.md
  README.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9668 docs: README.md
  README.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9673 Update windows pwsh command to download the testing binary
  README.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9674 chore: remove fs package from root package.json
  package.json
  pnpm-lock.yaml
Labels: size:XS, lgtm

#9664 Nc fix/meta sync issue(cloud)
  packages/nocodb/src/version-upgrader/0227000_dupColMergeUpgrader.ts
  packages/nocodb/src/version-upgrader/NcUpgrader.ts
Labels: size:XS, lgtm

#9656 docs: move providers to other installation methods
  README.md
  packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation/100.other-installations.md
  packages/noco-docs/docusaurus.config.js
  packages/noco-docs/src/css/custom.scss
Labels: 📋 Scope : Docs, size:S, lgtm

#9682 New Crowdin updates
  packages/nc-gui/lang/ko.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9678 Nc fix/misc
  packages/nc-gui/components/dlg/share-and-collaborate/ShareBase.vue
  packages/nc-gui/helpers/parsers/CSVTemplateAdapter.ts
  packages/noco-docs/docs/070.fields/040.field-types/060.formula/030.string-functions.md
  packages/nocodb-sdk/src/lib/formulaHelpers.ts
  packages/nocodb/src/db/functionMappings/commonFns.ts
  packages/nocodb/src/helpers/NcPluginMgrv2.ts
  packages/nocodb/src/plugins/s3/S3.ts
  packages/nocodb/src/services/columns.service.ts
  packages/nocodb/src/services/shared-bases.service.ts
  packages/nocodb/src/services/tables.service.ts
  tests/playwright/tests/db/features/baseShare.spec.ts
Labels: size:L, lgtm

#9690 fix: upload file size limit
  packages/nc-gui/components/cell/attachment/utils.ts
  packages/nocodb/src/constants/index.ts
  packages/nocodb/src/modules/noco.module.ts
  packages/nocodb/src/services/utils.service.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9694 New Crowdin updates
  packages/nc-gui/lang/ko.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9687 docs/vietnamese: Add Vietnamese README docs
  markdown/readme/languages/README.md
  markdown/readme/languages/vietnamese.md
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9680 fix: changelog images
  packages/nc-gui/components/feed/Changelog/Item.vue
  packages/nc-gui/components/feed/Recents/Card.vue
  packages/nc-gui/lib/types.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9697 Attachment followup
  packages/nc-gui/components/cell/attachment/utils.ts
Labels: size:S, lgtm

#9683 fix: Handle primary key value with 3 or more consecutive underscore
  packages/nc-gui/composables/useData.ts
  packages/nc-gui/composables/useKanbanViewStore.ts
  packages/nc-gui/composables/useLTARStore.ts
  packages/nc-gui/utils/dataUtils.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/helpers/catchError.ts
  packages/nocodb/src/services/data-table.service.ts
Labels: 🐛 Type: Bug, 🛑 Status: Do Not Merge, size:L, lgtm

#9707 New Crowdin updates
  packages/nc-gui/lang/cs.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9709 New Crowdin updates
  packages/nc-gui/lang/ko.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9705 fix(nc-gui): allow user to submit form in locked view
  packages/nc-gui/components/general/FormBranding.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/details/Fields.vue
Labels: 🐛 Type: Bug, 👓 Scope : View, size:M, lgtm

#9714 fix(nc-gui): UI Error on toggle locked view
  packages/nc-gui/components/nc/MenuItem.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
Labels: 🐛 Type: Bug, size:S, lgtm

#9699 Miscellaneous fixes and improvements
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
  packages/nc-gui/components/dashboard/TreeView/index.vue
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/column/EditOrAddProvider.vue
  packages/nc-gui/components/smartsheet/details/Fields.vue
  packages/nc-gui/components/smartsheet/header/VirtualCell.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue
  packages/nc-gui/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui/components/workspace/Menu.vue
  packages/nc-gui/utils/cell.ts
Labels: size:L, lgtm

#9718 fix: Grid view expanded form next and prev button bug
  packages/nc-gui/utils/dataUtils.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9717 Test connection improvements
  packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue
  packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue
  packages/nc-gui/components/workspace/integrations/forms/EditOrAddDatabase.vue
  packages/nc-gui/utils/baseCreateUtils.ts
  packages/nocodb/src/db/util/Result.ts
  packages/nocodb/src/filters/global-exception/global-exception.filter.ts
  packages/nocodb/src/helpers/catchError.ts
Labels: size:L, lgtm

#9720 fix(nc-gui): prefill form decode query param issue
  packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
  packages/nc-gui/components/nc/MenuItem.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
  packages/nc-gui/composables/useSharedFormViewStore.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9726 feat: load pdf with browser by default
  packages/nc-gui/components/cell/attachment/Preview/Pdf.vue
Labels: 🐛 Type: Bug, size:M, lgtm

#9723 New Crowdin updates
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/sv.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9733 Nc refactor/bettter jn table name
  packages/nocodb/src/services/columns.service.ts
Labels: 🧱 Type: Refactoring, size:M, lgtm

#9736 fix: data in sidebar not getting updated
  packages/nc-gui/composables/useCalendarViewStore.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9734 fix: gcs uniform bucket_level access
  packages/nocodb/src/plugins/gcs/Gcs.ts
  packages/nocodb/src/plugins/gcs/index.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9738 fix: Handle duplicate column name issue in junction table
  packages/nocodb/src/services/columns.service.ts
Labels: 🐛 Type: Bug, 🍰 Scope : Column, size:S, lgtm

#9740 fix: Calendar current time cursor is in the wrong place
  packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
  packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
Labels: 🐛 Type: Bug, size:S, lgtm

#9721 Nc fix/extension follow-up changes
  packages/nc-gui/assets/img/placeholder/extension.png
  packages/nc-gui/components/extensions/Details.vue
  packages/nc-gui/components/extensions/Extension.vue
  packages/nc-gui/components/extensions/Extension/Header.vue
  packages/nc-gui/components/extensions/Extension/Wrapper.vue
  packages/nc-gui/components/extensions/Market.vue
  packages/nc-gui/components/extensions/Market/ExtensionsTab.vue
  packages/nc-gui/components/extensions/Pane.vue
  packages/nc-gui/components/nc/Button.vue
  packages/nc-gui/components/smartsheet/Topbar.vue
  packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/StackedBy.vue
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/extensions/data-exporter/assets/icon.svg
  packages/nc-gui/extensions/data-exporter/description.md
  packages/nc-gui/extensions/data-exporter/index.vue
  packages/nc-gui/extensions/data-exporter/manifest.json
  packages/nc-gui/extensions/json-exporter/index.vue
  packages/nc-gui/extensions/json-exporter/manifest.json
  packages/nc-gui/lib/enums.ts
  packages/nc-gui/utils/commonUtils.ts
Labels: 🐛 Type: Bug, 🛑 Status: Do Not Merge, size:XL, lgtm

#9742 New Crowdin updates
  packages/nc-gui/lang/sv.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9741 refactor: Additional informations added on Airtable Import feature th…
  packages/nocodb/src/services/columns.service.ts
Labels: 🧱 Type: Refactoring, ⛵ Type: AT Import, size:XS, lgtm
