Repository nocodb/nocodb, pull requests merged in 2024-12, with the labels that each got.

#9860 Nc org chart extension
  packages/nc-gui/components/cell/MultiSelect.vue
  packages/nc-gui/components/nc/Select.vue
  packages/nc-gui/composables/useExtensionHelper.ts
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/utils/dataUtils.ts
Labels: size:S, lgtm

#9927 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9943 fix: disable unsupported arg
  packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9936 fix(nc-gui): org role selector input display issue
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/account/UserList.vue
  packages/nc-gui/components/account/UsersModal.vue
Labels: 🐛 Type: Bug, size:L, lgtm

#9934 fix(nc-gui): hide `uncategorized` stack if grouping field is required field
  packages/nc-gui/components/smartsheet/Kanban.vue
  packages/nc-gui/composables/useKanbanViewStore.ts
Labels: 🐛 Type: Bug, 👓 Scope : View, size:S, lgtm

#9933 fix(nc-gui): user logo bg color is not same in all the places
  packages/nc-gui/components/cell/User.vue
  packages/nc-gui/components/dlg/ReAssign/UserItem.vue
  packages/nc-gui/components/general/UserIcon.vue
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nc-gui/components/smartsheet/expanded-form/Sidebar/Audits.vue
  packages/nc-gui/components/smartsheet/form/LimitOptions.vue
  packages/nc-gui/components/workspace/AuditLogs.vue
  packages/nc-gui/components/workspace/CollaboratorsList.vue
  packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
Labels: 🐛 Type: Bug, size:M, lgtm

#9940 New Crowdin updates
  packages/nc-gui/lang/de.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9919 chore: oos changes
  packages/nc-gui/components/dlg/ColumnUpdateConfirm.vue
  packages/nc-gui/components/smartsheet/header/Menu.vue
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/extensions/data-exporter/index.vue
  packages/nc-gui/extensions/data-exporter/manifest.json
  packages/nc-gui/extensions/json-exporter/manifest.json
  packages/nocodb-sdk/src/lib/import-export-data.ts
  packages/nocodb/src/cache/NocoCache.ts
  packages/nocodb/src/cache/RedisCacheMgr.ts
  packages/nocodb/src/cache/RedisMockCacheMgr.ts
  packages/nocodb/src/models/Integration.spec.ts
  packages/nocodb/src/modules/jobs/jobs.module.ts
  packages/nocodb/src/utils/globals.ts
  scripts/self-hosted-gh-runner/Dockerfile
  scripts/self-hosted-gh-runner/values.yaml
Labels: size:XL, lgtm

#9921 Nc fix: Update AI button config modal UI as per new design
  packages/nc-gui/lang/en.json
Labels: 👓 Scope : View, size:XS, lgtm

#9955 docs : updated Snapshots docs
  packages/noco-docs/docs/040.bases/065.snapshots.md
Labels: 📋 Scope : Docs, size:M, lgtm

#9949 feat(ui): persist extension sidebar state per base
  packages/nc-gui/.patches/splitpanes@3.1.5.patch
  packages/nc-gui/composables/useExtensions.ts
Labels: 🔦 Type: Feature, size:M, lgtm

#9932 fix(extensions): typings for KvStore
  packages/nc-gui/composables/useExtensions.ts
Labels: size:S, lgtm

#9839 chore: migrate to rspack 🦀
  .github/workflows/release-timely-docker.yml
  build-local-docker-image.sh
  packages/nocodb/docker/rspack.config.js
  packages/nocodb/docker/webpack.config.js
  packages/nocodb/package.json
  packages/nocodb/rspack.cli.config.js
  packages/nocodb/rspack.config.js
  packages/nocodb/rspack.dev.config.js
  packages/nocodb/rspack.timely.config.js
  packages/nocodb/src/Noco.ts
  packages/nocodb/src/controllers/integrations.controller.ts
  packages/nocodb/src/controllers/org-users.controller.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/sql-mgr/SqlMgr.ts
  packages/nocodb/src/db/sql-migrator/lib/templates/mssql.template.ts
  packages/nocodb/src/helpers/NcPluginMgrv2.ts
  packages/nocodb/src/interface/Jobs.ts
  packages/nocodb/src/models/Comment.ts
  packages/nocodb/src/models/Model.ts
  packages/nocodb/src/modules/jobs/jobs-map.service.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
  packages/nocodb/src/plugins/gcs/Gcs.ts
  packages/nocodb/src/services/command-palette.service.ts
  packages/nocodb/src/services/public-datas.service.ts
  packages/nocodb/src/services/sql-views.service.ts
  packages/nocodb/src/services/tables.service.ts
  packages/nocodb/src/services/views.service.ts
  packages/nocodb/tests/unit/tsconfig.ee.json
  packages/nocodb/tests/unit/tsconfig.json
  packages/nocodb/tsconfig.json
  packages/nocodb/webpack.cli.config.js
  packages/nocodb/webpack.config.js
  packages/nocodb/webpack.local.config.js
  packages/nocodb/webpack.timely.config.js
  pnpm-lock.yaml
Labels: size:XL, lgtm

#9964 Nc fix/grid view attachment cell icon size
  packages/nc-gui/components/cell/attachment/IconView.vue
  packages/nc-gui/components/cell/attachment/Modal.vue
  packages/nc-gui/components/cell/attachment/index.vue
  packages/nc-gui/components/smartsheet/expanded-form/Sidebar/Audits.vue
  packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
  packages/nc-gui/composables/useAttachmentIcon.ts
Labels: 👓 Scope : View, size:L, lgtm

#9968 Nc test/keyboard shortcuts
  tests/playwright/tests/db/features/keyboardShortcuts.spec.ts
  tests/playwright/tests/db/views/viewForm.spec.ts
Labels: Scope : Test [E2E], size:XS, lgtm

#9960 fix(rich-text): map `\n` to `<br/>`
  packages/nc-gui/components/cell/RichText.vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#9969 New Crowdin updates
  packages/nc-gui/lang/de.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9972 chore(extensions): eventing on extension
  packages/nc-gui/components/extensions/Extension/Header.vue
  packages/nc-gui/components/extensions/Market.vue
  packages/nc-gui/components/extensions/Market/ExtensionsTab.vue
  packages/nc-gui/components/extensions/Pane.vue
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/extensions/data-exporter/index.vue
Labels: size:M, lgtm

#9980 Nc fix/delete ws
  packages/nocodb/src/models/Base.ts
  packages/nocodb/src/models/Source.ts
Labels: size:M, lgtm

#9982 fix: hide calendar
  packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#9971 fix(nc-gui): trim whitespace while converting from string data type to user
  packages/nocodb/src/services/columns.service.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9976 New Crowdin updates
  packages/nc-gui/lang/fr.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9984 fix (nc-gui): resolve warnings when opening grid header dropdown
  packages/nc-gui/components/nc/MenuItem.vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#9961 chore: bump nuxt version
  packages/nc-gui/components/smartsheet/column/BarcodeOptions.vue
  packages/nc-gui/nuxt.config.ts
  packages/nc-gui/package.json
  pnpm-lock.yaml
Labels: size:M, lgtm

#9959 fix: delete all records
  packages/nc-gui/components/dlg/Record/DeleteAll.vue
  packages/nc-gui/components/dlg/Record/Upsert.vue
  packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
  packages/nc-gui/components/smartsheet/grid/index.vue
  packages/nc-gui/composables/useGridViewData.ts
  packages/nc-gui/composables/useInfiniteData.ts
  packages/nc-gui/lang/en.json
  packages/nocodb/src/controllers/bulk-data-alias.controller.ts
  packages/nocodb/src/schema/swagger.json
Labels: 🐛 Type: Bug, size:L, lgtm

#9988 fix: encoded primary key #9615
  packages/nc-gui/composables/useInfiniteData.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9952 feat(nc-gui): allow Monday to be the first column in date picker
  packages/nc-gui/components/nc/DatePicker.vue
Labels: 🔦 Type: Feature, size:XS, lgtm

#9987 chore: lint
  packages/nc-gui/components/cell/attachment/IconView.vue
  packages/nc-gui/components/cell/attachment/index.vue
  packages/nc-gui/components/dashboard/settings/base/index.vue
  packages/nc-gui/components/extensions/Extension/Header.vue
  packages/nc-gui/components/extensions/Market.vue
  packages/nc-gui/components/extensions/Market/ExtensionsTab.vue
  packages/nc-gui/components/feed/View.vue
  packages/nc-gui/components/nc/Tooltip.vue
  packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
  packages/nc-gui/components/smartsheet/calendar/MonthView.vue
  packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue
  packages/nc-gui/composables/useAttachmentIcon.ts
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/composables/useViewGroupBy.ts
  packages/nc-gui/nuxt.config.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
Labels: size:L, lgtm

#9958 fix(nocodb): Bug fixes
  packages/nc-gui/components/cell/SingleSelect.vue
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/column/FormulaInputHelper.vue
  packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
  packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
  packages/nc-gui/composables/useViewAggregate.ts
  packages/nocodb/src/models/Column.ts
Labels: 🐛 Type: Bug, 🛑 Status: Do Not Merge, size:L, lgtm

#9970 Nc fix/bug fix 5 dec
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/cell/RichText.vue
  packages/nc-gui/components/cell/RichText/SelectedBubbleMenu.vue
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/general/WorkspaceIcon.vue
  packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
Labels: 🐛 Type: Bug, 🛑 Status: Do Not Merge, size:L, lgtm

#9993 fix (nc-gui): use autocomplete attributes on non-ee auth components
  packages/nc-gui/pages/signin.vue
  packages/nc-gui/pages/signup/[[token]].vue
Labels: 🐛 Type: Bug, 👮 Scope : Auth, size:XS, lgtm

#9995 chore: hide beta
  packages/nc-gui/components/smartsheet/column/ButtonOptions.vue
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/column/LongTextOptions.vue
Labels: size:L, lgtm

#9996 Nc refactor: ui
  packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
  packages/nc-gui/composables/useBetaFeatureToggle.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
Labels: 🧱 Type: Refactoring, size:L, lgtm

#9998 New Crowdin updates
  packages/nc-gui/lang/nl.json
Labels: ✈️ Type: i18n translation, size:S, lgtm

#9997 Nc fix/prompt existing issues
  packages/nc-gui/components/ai/Settings.vue
  packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
  packages/nc-gui/components/smartsheet/column/AiButtonOptions.vue
  packages/nc-gui/components/smartsheet/column/ButtonOptions.vue
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/column/LongTextOptions.vue
  packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue
  packages/nc-gui/components/smartsheet/details/Fields.vue
  packages/nc-gui/components/smartsheet/topbar/ViewListDropdown.vue
Labels: 🐛 Type: Bug, size:L, lgtm

#9999 fix: Shared url and dashboard url corrections
  packages/nc-gui/components/dlg/share-and-collaborate/ShareBase.vue
  packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
  packages/nocodb/src/run/cloud.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#10000 Fix incorrect script path in build-local-docker-image.sh
  build-local-docker-image.sh
Labels: 🐛 Type: Bug, size:XS, lgtm

#9859 chore(release-pr): update `upload-artifact` action to v4
  .github/workflows/release-pr.yml
  .github/workflows/uffizzi-preview.yml
Labels: size:M, lgtm

#10002 fix: rich text and normal long text column not working
  packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#10003 ci(uffizzi-preview): use id of the workflow that triggered the workflow run
  .github/workflows/uffizzi-preview.yml
Labels: size:XS, lgtm

#10005 ci(uffizzi-preview): provide GitHub token to download artifacts
  .github/workflows/uffizzi-preview.yml
Labels: size:XS, lgtm

#10004 fix(nc-gui): on blur save cell value of date related fields
  packages/nc-gui/components/cell/DatePicker.vue
  packages/nc-gui/components/cell/DateTimePicker.vue
  packages/nc-gui/components/cell/TimePicker.vue
  packages/nc-gui/components/cell/YearPicker.vue
Labels: 🐛 Type: Bug, size:L, lgtm

#10007 New Crowdin updates
  packages/nc-gui/lang/fr.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9983 Nc fix: if cell is active and document.activeElement is different then prevent selectedCellKeyupListner event
  packages/nc-gui/components/cell/MultiSelect.vue
  packages/nc-gui/components/cell/User.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/tabs/auth/user-management/UsersModal.vue
  packages/nc-gui/composables/useSelectedCellKeyupListener/index.ts
  packages/nc-gui/utils/browserUtils.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#10014 Nc chore(nc-gui): new feature changes
  packages/nc-gui/components/dashboard/FeatureExperimentation.vue
  packages/nc-gui/composables/useBetaFeatureToggle.ts
Labels: size:XS, lgtm

#9986 Nc fix/limit display value col
  packages/nc-gui/components/nc/List/index.vue
  packages/nc-gui/components/smartsheet/column/ButtonOptions.vue
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/column/LongTextOptions.vue
  packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue
  packages/nc-gui/components/smartsheet/header/Menu.vue
  packages/nc-gui/components/smartsheet/header/UpdateDisplayValue.vue
  packages/nocodb-sdk/src/lib/UITypes.ts
  packages/nocodb-sdk/src/lib/helperFunctions.ts
  packages/nocodb-sdk/src/lib/index.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9992 fix(nc-gui): audit log ui changes
  packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
  packages/nc-gui/components/dashboard/settings/DataSources.vue
  packages/nc-gui/components/dashboard/settings/base/index.vue
  packages/nc-gui/components/workspace/AuditLogs.vue
  packages/nc-gui/pages/account/index.vue
  packages/nc-gui/pages/account/index/[page].vue
  packages/nc-gui/store/workspace.ts
  tests/playwright/pages/Dashboard/Settings/Miscellaneous.ts
  tests/playwright/tests/db/general/tableOperations.spec.ts
Labels: 👓 Scope : View, size:XL, lgtm

#10013 fix: metas sync
  packages/nocodb/src/services/meta-diffs.service.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#10015 fix(nc-gui): auto same duration cell value
  packages/nc-gui/components/cell/Duration.vue
  packages/nc-gui/components/nc/List/index.vue
Labels: 🐛 Type: Bug, size:S, lgtm

#10021 New Crowdin updates
  packages/nc-gui/lang/ko.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#10026 fix: expanded-form not triggering when grouped with number
  packages/nc-gui/components/smartsheet/grid/GroupByTable.vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#10022 Nc fix/create form option visibility issue
  packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
  packages/nc-gui/components/nc/List/index.vue
  packages/nc-gui/components/smartsheet/header/UpdateDisplayValue.vue
  packages/nc-gui/components/smartsheet/topbar/ViewListDropdown.vue
  packages/nc-gui/lang/en.json
Labels: 🐛 Type: Bug, 👓 Scope : View, size:M, lgtm

#10030 docs: readme update
  README.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#10029 chore(nc-gui): lint
  packages/nc-gui/components/cell/DatePicker.vue
  packages/nc-gui/components/cell/DateTimePicker.vue
  packages/nc-gui/components/cell/TimePicker.vue
  packages/nc-gui/components/cell/YearPicker.vue
  packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
  packages/nc-gui/store/workspace.ts
Labels: size:L, lgtm

#10033 Increase delay between npm publish and install
  .github/workflows/release-npm.yml
Labels: size:XS, lgtm

#10034 Chore/action delay
  .github/workflows/release-npm.yml
Labels: size:XS, lgtm

#10028 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/en.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/km.json
  packages/nc-gui/lang/kn.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/ml.json
  packages/nc-gui/lang/ne.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ro.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#10032 fix (nc-gui): restrict height of cells in short view
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/cell/attachment/index.vue
Labels: 🐛 Type: Bug, size:S, lgtm

#10037 Upstall script - Initialising default settings
  docker-compose/1_Auto_Upstall/noco.sh
Labels: size:XS, lgtm

#9918 feat(wip): order column
  packages/nc-gui/components/smartsheet/column/ButtonOptions.vue
  packages/nc-gui/components/smartsheet/column/UITypesOptionsWithSearch.vue
  packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
  packages/nc-gui/components/workspace/project/AiCreateProject.vue
  packages/nc-gui/composables/useMultiSelect/index.ts
  packages/nc-gui/composables/useNocoAi.ts
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb-sdk/src/lib/UITypes.ts
  packages/nocodb-sdk/src/lib/index.ts
  packages/nocodb-sdk/src/lib/sqlUi/DatabricksUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts
  packages/nocodb/docker/rspack.config.js
  packages/nocodb/rspack.config.js
  packages/nocodb/rspack.timely.config.js
  packages/nocodb/src/Upgrader.ts
  packages/nocodb/src/cache/NocoCache.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/helpers/getAst.ts
  packages/nocodb/src/helpers/migrationJobs.ts
  packages/nocodb/src/interface/Jobs.ts
  packages/nocodb/src/meta/meta.service.ts
  packages/nocodb/src/models/CalendarViewColumn.ts
  packages/nocodb/src/models/FormViewColumn.ts
  packages/nocodb/src/models/GalleryViewColumn.ts
  packages/nocodb/src/models/GridViewColumn.ts
  packages/nocodb/src/models/KanbanViewColumn.ts
  packages/nocodb/src/models/MapViewColumn.ts
  packages/nocodb/src/models/Source.ts
  packages/nocodb/src/models/View.ts
  packages/nocodb/src/modules/jobs/jobs.module.ts
  packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts
  packages/nocodb/src/modules/jobs/migration-jobs/nc_job_005_order_column.ts
  packages/nocodb/src/plugins/GenericS3/GenericS3.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/tables.service.ts
  packages/nocodb/src/utils/nc-config/constants.ts
  packages/nocodb/tests/unit/factory/row.ts
  packages/nocodb/tests/unit/rest/tests/columnTypeSpecific.test.ts
  packages/nocodb/tests/unit/rest/tests/newDataApis.test.ts
  tests/playwright/pages/Dashboard/ProjectView/Settings.ts
Labels: 🔦 Type: Feature, size:XXL, lgtm

#10039 chore: increase delay between publish and install
  .github/workflows/release-npm.yml
Labels: size:XS, lgtm

#10046 New Crowdin updates
  packages/nc-gui/lang/en.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/uk.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#10025 Nc feat/form mode template message
  packages/nc-gui/components/cell/RichText.vue
  packages/nc-gui/components/cell/RichText/SelectedBubbleMenu.vue
  packages/nc-gui/components/cell/RichText/SelectedBubbleMenuPopup.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/composables/useTemplatedMessage.ts
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue
Labels: size:M, lgtm

#10023 fix(nocodb): sql: preserve negative symbols
  packages/nocodb/src/db/sql-client/lib/pg/typeCast.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#10044 fix(nocodb): suppress invalid col validation while duplicating
  packages/nc-gui/composables/useColumnCreateStore.ts
  packages/nc-gui/lang/en.json
  packages/nocodb/src/models/Column.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
  packages/nocodb/src/services/columns.service.ts
Labels: 🐛 Type: Bug, size:M

#10045 fix: upgrader mode
  packages/nocodb-sdk/src/lib/sqlUi/DatabricksUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts
  packages/nocodb/src/Upgrader.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/sql-client/lib/mssql/MssqlClient.ts
  packages/nocodb/src/db/sql-client/lib/mysql/MysqlClient.ts
  packages/nocodb/src/db/sql-client/lib/oracle/OracleClient.ts
  packages/nocodb/src/db/sql-client/lib/sqlite/SqliteClient.ts
  packages/nocodb/src/interface/Jobs.ts
  packages/nocodb/src/meta/meta.service.ts
  packages/nocodb/src/modules/jobs/jobs.module.ts
  packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts
  packages/nocodb/src/modules/jobs/migration-jobs/nc_job_005_order_column.ts
  packages/nocodb/src/modules/jobs/migration-jobs/nc_job_no_op.ts
  packages/nocodb/src/providers/init-meta-service.provider.ts
  packages/nocodb/src/services/columns.service.ts
  packages/nocodb/src/services/meta-diffs.service.ts
Labels: 🐛 Type: Bug, size:L

#10065 chore: bump to node 22 wip
  .github/workflows/ci-cd.yml
  .github/workflows/jest-unit-test.yml
  .github/workflows/playwright-test-workflow.yml
  .github/workflows/pre-build-for-playwright.yml
  .github/workflows/publish-blog.yml
  .github/workflows/publish-dev-docs.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-noco-i18n.yml
  .github/workflows/publish-prev-docs.yml
  .github/workflows/release-docker.yml
  .github/workflows/release-draft.yml
  .github/workflows/release-executables.yml
  .github/workflows/release-npm.yml
  .github/workflows/release-secret-cli.yml
  .github/workflows/release-timely-docker.yml
  .github/workflows/release-timely-executables.yml
  .github/workflows/sync-to-develop.yml
  .github/workflows/unit-test.yml
  .github/workflows/update-sdk-path.yml
  .github/workflows/validate-docs-links.yml
  .npmrc
  package.json
  packages/nocodb/Dockerfile
  packages/nocodb/Dockerfile.local
  packages/nocodb/Dockerfile.timely
  packages/nocodb/package.json
  packages/nocodb/src/db/sql-client/lib/mssql/MssqlClient.ts
  packages/nocodb/src/db/sql-client/lib/mysql/MysqlClient.ts
  packages/nocodb/src/db/sql-client/lib/oracle/OracleClient.ts
  packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts
  packages/nocodb/src/helpers/deepClone.ts
  packages/nocodb/tests/unit/TestDbMngr.ts
  pnpm-lock.yaml
  scripts/pkg-executable/package.json
  scripts/self-hosted-gh-runner/Dockerfile
  scripts/self-hosted-gh-runner/node-pnpm-check.sh
Labels: trigger-CI

#10108 feat: snowflake animation
  packages/nc-gui/app.vue
  packages/nc-gui/assets/nc-icons/snow.svg
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
  packages/nc-gui/components/general/Snowfall.vue
  packages/nc-gui/components/project/View.vue
  packages/nc-gui/components/smartsheet/Topbar.vue
  packages/nc-gui/components/smartsheet/topbar/SnowfallTrigger.vue
  packages/nc-gui/components/workspace/View.vue
  packages/nc-gui/components/workspace/integrations/view.vue
  packages/nc-gui/lang/en.json
  packages/nc-gui/lib/enums.ts
  packages/nc-gui/utils/iconUtils.ts
Labels: 🛑 Status: Do Not Merge

#9811 fix: update auto upstall script
  docker-compose/1_Auto_Upstall/noco.sh
  docker-compose/1_Auto_Upstall/tests/configure/setup.sh
  docker-compose/1_Auto_Upstall/tests/configure/stop.bats
  docker-compose/1_Auto_Upstall/tests/expects/configure/stop.sh
  docker-compose/1_Auto_Upstall/tests/expects/configure/upgrade.sh
  docker-compose/1_Auto_Upstall/tests/expects/install/default.sh
  docker-compose/1_Auto_Upstall/tests/expects/install/ip.sh
  docker-compose/1_Auto_Upstall/tests/expects/install/redis.sh
  docker-compose/1_Auto_Upstall/tests/expects/install/scale.sh
  docker-compose/1_Auto_Upstall/tests/expects/install/ssl.sh
  docker-compose/1_Auto_Upstall/tests/expects/install/watchtower.sh
Labels: 🐛 Type: Bug, size:L

#10089 Nc feat/user profile icon
  packages/nc-gui/components/account/Profile.vue
  packages/nc-gui/components/cell/RichText.vue
  packages/nc-gui/components/cell/User.vue
  packages/nc-gui/components/cell/attachment/Preview/Image.vue
  packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
  packages/nc-gui/components/dlg/ReAssign/UserItem.vue
  packages/nc-gui/components/general/IconSelector.vue
  packages/nc-gui/components/general/ImageCropper.vue
  packages/nc-gui/components/general/UserIcon.vue
  packages/nc-gui/components/general/WorkspaceIcon.vue
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nc-gui/components/smartsheet/expanded-form/Sidebar/Audits.vue
  packages/nc-gui/components/smartsheet/expanded-form/Sidebar/Comments.vue
  packages/nc-gui/components/smartsheet/form/LimitOptions.vue
  packages/nc-gui/components/smartsheet/grid/GroupByTable.vue
  packages/nc-gui/components/workspace/CollaboratorsList.vue
  packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
  packages/nc-gui/composables/useExpandedFormStore.ts
  packages/nc-gui/composables/useRoles/index.ts
  packages/nc-gui/composables/useRowComments.ts
  packages/nc-gui/helpers/tiptapExtensions/mention/MentionList.vue
  packages/nc-gui/helpers/tiptapExtensions/mention/UserMentionList.vue
  packages/nc-gui/lib/enums.ts
  packages/nc-gui/lib/types.ts
  packages/nc-gui/store/users.ts
  packages/nc-gui/utils/dataUtils.ts
  packages/nc-gui/utils/is.ts
  packages/nc-gui/utils/parseUtils.ts
  packages/nocodb-sdk/src/lib/UITypes.ts
  packages/nocodb-sdk/src/lib/enums.ts
  packages/nocodb-sdk/src/lib/helperFunctions.ts
  packages/nocodb-sdk/src/lib/index.ts
  packages/nocodb-sdk/src/lib/is.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
  packages/nocodb/src/meta/migrations/v2/nc_071_add_meta_in_users.ts
  packages/nocodb/src/models/BaseUser.ts
  packages/nocodb/src/models/PresignedUrl.ts
  packages/nocodb/src/models/User.ts
  packages/nocodb/src/modules/auth/auth.controller.ts
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/base-users/base-users.service.ts
  packages/nocodb/src/services/notifications/notifications.service.ts
  packages/nocodb/src/services/org-users.service.ts
  packages/nocodb/src/services/public-metas.service.ts
  packages/nocodb/src/services/users/users.service.ts
  packages/nocodb/tests/unit/rest/tests/columnTypeSpecific.test.ts
  packages/nocodb/tests/unit/rest/tests/newDataApis.test.ts
Labels: 🛑 Status: Do Not Merge

#10134 Nc fix/User account pages related UI changes
  packages/nc-gui/assets/nc-icons-v2/webhook.svg
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/account/ResetPassword.vue
  packages/nc-gui/components/cell/User.vue
  packages/nc-gui/components/dashboard/settings/DataSources.vue
  packages/nc-gui/components/dashboard/settings/base/index.vue
  packages/nc-gui/components/general/IconSelector.vue
  packages/nc-gui/components/general/TableIcon.vue
  packages/nc-gui/components/nc/Badge.vue
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nc-gui/components/roles/Badge.vue
  packages/nc-gui/components/smartsheet/Details.vue
  packages/nc-gui/components/smartsheet/Topbar.vue
  packages/nc-gui/components/smartsheet/header/Menu.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/components/webhook/index.vue
  packages/nc-gui/components/workspace/CollaboratorsList.vue
  packages/nc-gui/pages/account/index.vue
  packages/nc-gui/utils/iconUtils.ts
  tests/playwright/disabledTests/docs/keybaordShortcutsAndDragDrop.spec.ts
  tests/playwright/pages/Dashboard/Grid/Column/index.ts
  tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
Labels: 🛑 Status: Do Not Merge
