Repository nocodb/nocodb, pull requests merged in 2024-02, with the labels that each got.

#7528 Nc feat: base reorder and fixed views reorder issue
  packages/nc-gui/components/dashboard/TreeView/TableList.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsList.vue
  packages/nc-gui/components/dashboard/TreeView/index.vue
  packages/nc-gui/lib/acl.ts
  packages/nc-gui/store/bases.ts
  packages/nocodb/src/models/Base.ts
  packages/nocodb/src/models/BaseUser.ts
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/bases.service.ts
Labels: trigger-CI

#7616 Nc fix: sort from field context menu
  packages/nocodb/src/cache/CacheMgr.ts
Labels: trigger-CI

#7558 Nc copy and and paste a linked record and date/dateTime field value from one cell to another
  packages/nc-gui/components/smartsheet/Row.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/composables/useData.ts
  packages/nc-gui/composables/useLTARStore.ts
  packages/nc-gui/composables/useMultiSelect/convertCellData.ts
  packages/nc-gui/composables/useMultiSelect/index.ts
  packages/nc-gui/composables/useSmartsheetRowStore.ts
  packages/nc-gui/composables/useViewSorts.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/utils/dataUtils.ts
  packages/nocodb/src/controllers/data-table.controller.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/data-table.service.ts
  packages/nocodb/src/utils/acl.ts
Labels: 🚥 Status: On Hold

#7653 Nc fix - DATABASE_URL bug
  packages/nc-gui/assets/nc-icons/phone-call.svg
  packages/nc-gui/components/dashboard/Sidebar.vue
  packages/nc-gui/components/dashboard/Sidebar/BeforeUserInfo.vue
  packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
  packages/nc-gui/composables/useGlobal/actions.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/nocodb/src/modules/global/global.module.ts
  packages/nocodb/src/modules/global/init-meta-service.provider.ts
  packages/nocodb/src/utils/nc-config/helpers.ts
Labels: trigger-CI

#7664 Nc feat/form view v2
  packages/nc-gui/assets/img/brand/nocodb-logo.svg
  packages/nc-gui/assets/img/form-banner-left.png
  packages/nc-gui/assets/img/form-banner-right.png
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/cell/Json.vue
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue
  packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
  packages/nc-gui/components/general/ColorPicker.vue
  packages/nc-gui/components/general/FormBanner.vue
  packages/nc-gui/components/general/FormBranding.vue
  packages/nc-gui/components/smartsheet/Cell.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/composables/useSharedFormViewStore.ts
  packages/nc-gui/composables/useViewColumns.ts
  packages/nc-gui/composables/useViewData.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/layouts/shared-view.vue
  packages/nc-gui/pages/index/[typeOrId]/[baseId]/index.vue
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index.vue
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue
  packages/nc-gui/pages/projects/index/list.vue
  packages/nc-gui/utils/iconUtils.ts
  packages/nc-gui/windi.config.ts
  tests/playwright/pages/Dashboard/Form/index.ts
  tests/playwright/tests/db/views/viewForm.spec.ts
Labels: 🛑 Status: Do Not Merge
