Repository nocodb/nocodb, pull requests merged in 2024-07, with the labels that each got.

#8936 chore: remove trailing space from docker command
  README.md
Labels: size:XS, lgtm

#8934 chore: upgrade pnpm install action
  .github/workflows/ci-cd.yml
  .github/workflows/playwright-test-workflow.yml
  .github/workflows/pre-build-for-playwright.yml
  .github/workflows/release-docker.yml
  .github/workflows/release-npm.yml
  .github/workflows/sync-to-develop.yml
  .github/workflows/unit-test.yml
  .github/workflows/update-sdk-path.yml
Labels: lgtm

#8935 New Crowdin updates
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/zh-Hans.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#8938 fix(nc-gui): translation merge issue
  packages/nc-gui/components/smartsheet/Kanban.vue
  packages/nc-gui/lang/en.json
Labels: 🐛 Type: Bug, ✈️ Type: i18n translation, size:S, lgtm

#8909 maintenance ui
  packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
  packages/nc-gui/components/general/MaintenanceAlert.vue
  packages/nc-gui/composables/useServerConfig.ts
  packages/nc-gui/plugins/a.dayjs.ts
Labels: size:S, lgtm

#8917 feat: Field list dropdown order should be same as view column order
  packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldListWithSearch.vue
  packages/nc-gui/composables/useViewColumns.ts
  packages/nocodb/src/models/View.ts
  packages/nocodb/tests/unit/rest/tests/viewRow.test.ts
Labels: size:M

#8944 feat: maintenance alert docs
  packages/noco-docs/docusaurus.config.js
  packages/noco-docs/src/css/custom.scss
  packages/noco-docs/src/modules/maintenance.js
Labels: 📋 Scope : Docs, size:L, lgtm

#8939 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: 🛑 Status: Do Not Merge, ✈️ Type: i18n translation, size:L, lgtm

#8946 fix: sync docs dependencies
  packages/noco-docs/package-lock.json
  packages/noco-docs/package.json
Labels: 🤖 Bot: Dependencies, size:XS, lgtm

#8931 Fix: Persist the left sidebar width and use pixels instead of percentage to configure the sidebar width
  packages/nc-gui/components/dashboard/View.vue
  packages/nc-gui/composables/useGlobal/actions.ts
  packages/nc-gui/composables/useGlobal/state.ts
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/lib/constants.ts
  packages/nc-gui/store/sidebar.ts
  tests/playwright/pages/Dashboard/Grid/Column/index.ts
  tests/playwright/quickTests/commonTest.ts
Labels: size:L, lgtm

#8921 feat: attachments by url, webcam
  packages/nc-gui/assets/nc-icons/camera.svg
  packages/nc-gui/assets/nc-icons/file.svg
  packages/nc-gui/components/cell/attachment/AttachFile.vue
  packages/nc-gui/components/cell/attachment/Modal.vue
  packages/nc-gui/components/cell/attachment/UploadProviders/Camera.vue
  packages/nc-gui/components/cell/attachment/UploadProviders/Local.vue
  packages/nc-gui/components/cell/attachment/UploadProviders/Url.vue
  packages/nc-gui/components/cell/attachment/index.vue
  packages/nc-gui/components/cell/attachment/utils.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/utils/aggregationUtils.ts
  packages/nc-gui/utils/attachmentUtils.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/nocodb/src/services/attachments.service.ts
  tests/playwright/pages/Dashboard/BulkUpdate/index.ts
  tests/playwright/pages/Dashboard/common/Cell/AttachmentCell.ts
Labels: size:XXL, lgtm

#8914 test: disable MFE tests for SQLite & MySQL
  tests/playwright/tests/db/features/multiFieldEditor.spec.ts
Labels: lgtm

#8933 feat: use text for SingleLineText & URL
  packages/nocodb-sdk/src/lib/sqlUi/DatabricksUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
Labels: trigger-CI, lgtm

#8951 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/en.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:XL, lgtm

#8950 fix: load expnaded form row on cliking on bt, ltar cell chip
  packages/nc-gui/components/virtual-cell/BelongsTo.vue
  packages/nc-gui/components/virtual-cell/HasMany.vue
  packages/nc-gui/components/virtual-cell/ManyToMany.vue
  packages/nc-gui/components/virtual-cell/OneToOne.vue
  packages/nc-gui/components/virtual-cell/components/ItemChip.vue
Labels: 🐛 Type: Bug, size:M, lgtm

#8915 Nc feature: Import CSV - skip field mapping during import
  packages/nc-gui/components/dlg/QuickImport.vue
  packages/nc-gui/components/template/Editor.vue
  packages/nc-gui/components/template/utils.ts
  packages/nc-gui/helpers/parsers/ExcelTemplateAdapter.ts
  packages/nc-gui/lang/en.json
  tests/playwright/tests/db/features/import.spec.ts
Labels: 🛑 Status: Do Not Merge, size:L, lgtm

#8952 docs: import csv
  packages/noco-docs/docs/050.tables/030.create-table-via-import.md
  packages/noco-docs/static/img/v2/table/import-csv-url.png
  packages/noco-docs/static/img/v2/table/import-csv.png
  packages/noco-docs/static/img/v2/table/import-stage-2.png
Labels: 📋 Scope : Docs, size:S, lgtm

#8953 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#8955 docs: remove EAN from supported barcode type
  packages/noco-docs/docs/070.fields/040.field-types/050.custom-types/050.barcode.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#8961 Nc chore/menu titles
  packages/nc-gui/components/dashboard/TreeView/TableNode.vue
  packages/nc-gui/components/smartsheet/Kanban.vue
  packages/nc-gui/components/smartsheet/details/Fields.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/components/smartsheet/header/Menu.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
  packages/nc-gui/lang/en.json
  tests/playwright/pages/Dashboard/ExpandedForm/index.ts
  tests/playwright/pages/Dashboard/Grid/Column/index.ts
Labels: 🧱 Type: Refactoring, size:L, lgtm

#8954 fix: avoid checking names cross-source
  packages/nocodb/src/models/Model.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#8967 fix: use update method for soft delete
  packages/nocodb/src/models/Source.ts
  packages/nocodb/src/services/sources.service.ts
  packages/nocodb/src/version-upgrader/ncProjectConfigUpgrader.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#8972 Nc fix: sidebar width issue if user hide sidebar & reload page
  packages/nc-gui/components/dashboard/View.vue
  packages/nc-gui/composables/useGlobal/actions.ts
  packages/nc-gui/composables/useGlobal/state.ts
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/store/sidebar.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#8977 chore : Group the env variables and remove the ones that are not nece…
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
Labels: size:L, lgtm

#8983 fix: enable toc in docs
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#8982 New Crowdin updates
  packages/nc-gui/lang/pt_BR.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#8981 fix: add telementry to cmd+j
  packages/nc-gui/plugins/tele.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#8971 Nc fix: prevent commentor/viewer from enabling hidden columns
  packages/nc-gui/components/nc/PaginationV2.vue
  packages/nc-gui/components/smartsheet/Toolbar.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldListWithSearch.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/RowHeight.vue
  packages/nc-gui/composables/useSharedView.ts
  packages/nc-gui/composables/useViewColumns.ts
  packages/nc-gui/lib/types.ts
  packages/nocodb/src/services/public-metas.service.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#8973 fix: missing pk for user junction table
  packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
  packages/nocodb/src/meta/migrations/v2/nc_055_junction_pk.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#8989 fix(nc-gui): add new row btn width issue
  packages/nc-gui/components/smartsheet/grid/Table.vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#8367 Nc feat/links from existing cols
  packages/nc-gui/components/general/DeleteModal.vue
  packages/nc-gui/components/nc/Select.vue
  packages/nc-gui/components/smartsheet/Cell.vue
  packages/nc-gui/components/smartsheet/PlainCell.vue
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/column/LinkAdvancedOptions.vue
  packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
  packages/nc-gui/components/smartsheet/column/LookupOptions.vue
  packages/nc-gui/components/smartsheet/details/Fields.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/smartsheet/grid/GroupBy.vue
  packages/nc-gui/components/smartsheet/grid/GroupByTable.vue
  packages/nc-gui/components/smartsheet/grid/useColumnDrag.ts
  packages/nc-gui/components/smartsheet/header/DeleteColumnModal.vue
  packages/nc-gui/components/smartsheet/header/Menu.vue
  packages/nc-gui/components/smartsheet/toolbar/FilterInput.vue
  packages/nc-gui/composables/useColumnCreateStore.ts
  packages/nc-gui/composables/useExpandedFormStore.ts
  packages/nc-gui/composables/useViewColumns.ts
  packages/nc-gui/store/sidebar.ts
  packages/nocodb-sdk/src/lib/globals.ts
  packages/nocodb-sdk/src/lib/sqlUi/DatabricksUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts
  packages/nocodb/src/controllers/notifications.controller.ts
  packages/nocodb/src/controllers/users/users.controller.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/genRollupSelectv2.ts
  packages/nocodb/src/db/generateLookupSelectQuery.ts
  packages/nocodb/src/helpers/catchError.ts
  packages/nocodb/src/helpers/columnHelpers.ts
  packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
  packages/nocodb/src/redis/pubsub-redis.ts
  packages/nocodb/src/services/columns.service.ts
  packages/nocodb/src/services/tables.service.ts
  packages/nocodb/tests/unit/factory/table.ts
  packages/nocodb/tests/unit/rest/index.test.ts
  packages/nocodb/tsconfig.json
  tests/playwright/pages/Dashboard/Details/FieldsPage.ts
  tests/playwright/pages/Dashboard/Grid/Column/index.ts
  tests/playwright/tests/db/columns/columnLinkToAnotherRecordAdvanceOptions.spec.ts
Labels: size:XL, lgtm

#8984 Nc fix: rename id column if exist in import table
  packages/nc-gui/components/dlg/QuickImport.vue
  packages/nc-gui/components/template/Editor.vue
  packages/nc-gui/helpers/parsers/CSVTemplateAdapter.ts
  packages/nc-gui/helpers/parsers/ExcelTemplateAdapter.ts
  packages/nc-gui/utils/validation.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#8992 feat(nc-gui): persist add new record mode (grid/form) in local storage
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/composables/useGlobal/actions.ts
  packages/nc-gui/composables/useGlobal/state.ts
  packages/nc-gui/composables/useGlobal/types.ts
Labels: 🔦 Type: Feature, size:S, lgtm

#8991 fix(nc-gui): json cell value visibility issue
  packages/nc-gui/components/cell/Json.vue
Labels: 🐛 Type: Bug, size:M, lgtm

#8995 feat(nc-gui): add form header in each slide of survey form
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue
Labels: 🔦 Type: Feature, size:XS, lgtm

#8986 fix: Extensions TBD work items
  packages/nc-gui/components/extensions/Details.vue
  packages/nc-gui/components/extensions/Extension.vue
  packages/nc-gui/components/extensions/Market.vue
  packages/nc-gui/components/extensions/Pane.vue
  packages/nc-gui/components/smartsheet/Toolbar.vue
  packages/nc-gui/components/smartsheet/Topbar.vue
  packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldsMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/GroupByMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/StackedBy.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/context/index.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#8994 Nc fix/links followup
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
  packages/nocodb/src/services/columns.service.ts
Labels: size:M, lgtm

#8996 fix: CSV Data Upload option not available for MySQL when Schema edit is disabled
  packages/nc-gui/composables/useRoles/index.ts
Labels: 🐛 Type: Bug, 🐬 DB : MySQL, size:XS, lgtm

#9000 docs: typo fix
  packages/noco-docs/docs/160.developer-resources/010.rest-APIs/050.upload-via-api.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9003 feat: fileCreateByStream for S3
  packages/nocodb/src/plugins/s3/S3.ts
Labels: 🔦 Type: Feature, size:M, lgtm

#9006 Nc fix/bulk api
  packages/nc-gui/composables/useViewGroupBy.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#8900 fix: rollup functions
  packages/nc-gui/components/virtual-cell/Rollup.vue
  packages/nocodb-sdk/src/lib/helperFunctions.ts
  packages/nocodb/src/db/genRollupSelectv2.ts
  packages/nocodb/src/models/RollupColumn.ts
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
Labels: size:L, lgtm

#9010 fix(nc-gui): fix download csv/xlsx error
  packages/nocodb/src/helpers/dataHelpers.ts
Labels: 🐛 Type: Bug, trigger-CI, size:XS, lgtm

#9005 Nc fix: data exporter extension UI changes
  packages/nc-gui/components/dashboard/View.vue
  packages/nc-gui/components/extensions/Details.vue
  packages/nc-gui/components/extensions/Extension.vue
  packages/nc-gui/components/extensions/ExtensionMenu.vue
  packages/nc-gui/components/extensions/Market.vue
  packages/nc-gui/components/extensions/Pane.vue
  packages/nc-gui/components/general/ViewIcon.vue
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/composables/useJobs.ts
  packages/nc-gui/extensions/data-exporter/index.vue
  packages/nc-gui/extensions/json-exporter/index.vue
  packages/nc-gui/lib/enums.ts
  packages/nc-gui/utils/urlUtils.ts
  packages/nocodb/src/interface/Jobs.ts
  packages/nocodb/src/modules/jobs/jobs-event.service.ts
  packages/nocodb/src/modules/jobs/jobs/data-export/data-export.processor.ts
Labels: 🐛 Type: Bug, 🛑 Status: Do Not Merge, size:XL, lgtm

#9007 chore: improve GitHub issue templates
  .github/ISSUE_TEMPLATE/--bug-report.yaml
  .github/ISSUE_TEMPLATE/--feature-request.yaml
Labels: size:M, lgtm

#9028 fix: add checkbox to toggle webhook parameter
  packages/nc-gui/components/api-client/Headers.vue
  packages/nc-gui/components/api-client/Params.vue
Labels: 🐛 Type: Bug, size:S, lgtm

#9030 fix: load aggregations only on grid view
  packages/nc-gui/composables/useViewAggregate.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9029 feat: add labels support for url
  packages/nc-gui/utils/urlUtils.ts
  packages/nocodb-sdk/src/lib/formulaHelpers.ts
  packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
Labels: 🔦 Type: Feature, size:M, lgtm

#9033 fix: handle when url is empty
  packages/nc-gui/utils/urlUtils.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9019 Corrections in setup script
  docker-compose/setup-script/noco.sh
Labels: size:S, lgtm

#9036 New Crowdin updates
  packages/nc-gui/lang/uk.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9037 Nc fix/at import issues
  packages/nc-gui/components/dlg/AirtableImport.vue
  packages/nocodb/src/modules/jobs/jobs/at-import/helpers/readAndProcessData.ts
Labels: ⛵ Type: AT Import, size:M, lgtm

#9031 fix: #8910 trim extra space during sign in & sign up
  packages/nc-gui/pages/signin.vue
  packages/nc-gui/pages/signup/[[token]].vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#9038 New Crowdin updates
  packages/nc-gui/lang/uk.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9039 New Crowdin updates
  packages/nc-gui/lang/hu.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#8886 feat: add S3 endpoint input
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/helpers/NcPluginMgrv2.ts
  packages/nocodb/src/models/FormView.ts
  packages/nocodb/src/models/PresignedUrl.ts
  packages/nocodb/src/modules/jobs/jobs/data-export/data-export.processor.ts
  packages/nocodb/src/plugins/s3/S3.ts
  packages/nocodb/src/plugins/s3/index.ts
  packages/nocodb/src/services/attachments.service.ts
Labels: size:L, lgtm

#9013 Nc fix/misc
  packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
  packages/nc-gui/components/smartsheet/toolbar/CreateGroupBy.vue
  packages/nc-gui/components/smartsheet/toolbar/CreateSort.vue
  packages/nc-gui/components/smartsheet/toolbar/FieldListAutoCompleteDropdown.vue
  packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
  packages/nc-gui/composables/useViewColumns.ts
  packages/nc-gui/composables/useViewGroupBy.ts
  packages/nocodb-sdk/src/lib/UITypes.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/conditionV2.ts
  packages/nocodb/src/helpers/dataHelpers.ts
  packages/nocodb/src/services/app-hooks-listener.service.ts
Labels: size:L, lgtm

#9042 New Crowdin updates
  packages/nc-gui/lang/fr.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9041 chore: bump xlsx package version
  package.json
  packages/nc-gui/package.json
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/package.json
  pnpm-lock.yaml
Labels: 🤖 Bot: Dependencies, size:XS, lgtm

#9045 fix: UI Acl & data sources
  packages/nc-gui/components/dashboard/settings/DataSources.vue
  packages/nc-gui/components/dashboard/settings/UIAcl.vue
  packages/nocodb-sdk/src/lib/formulaHelpers.ts
  packages/nocodb/src/models/Source.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9051 Nc fix/3368 links followup
  packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
  packages/nc-gui/composables/useMultiSelect/index.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
Labels: size:M, lgtm

#9056 fix(nc-gui): view page title udpate issue
  packages/nc-gui/store/views.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9062 fix: use original url if signed url not available
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/models/FormView.ts
  packages/nocodb/src/models/PresignedUrl.ts
  packages/nocodb/src/modules/jobs/jobs/data-export/data-export.processor.ts
  packages/nocodb/src/services/attachments.service.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9052 feat: allow preview for media types
  packages/nc-gui/components/cell/attachment/Carousel.vue
  packages/nc-gui/components/cell/attachment/Modal.vue
  packages/nc-gui/components/cell/attachment/index.vue
  packages/nc-gui/components/cell/attachment/utils.ts
  packages/nc-gui/composables/useAttachment.ts
  packages/nc-gui/composables/useSharedView.ts
  packages/nocodb/src/controllers/attachments-secure.controller.ts
  packages/nocodb/src/controllers/attachments.controller.ts
  packages/nocodb/src/controllers/public-datas.controller.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/helpers/attachmentHelpers.ts
  packages/nocodb/src/models/PresignedUrl.ts
  packages/nocodb/src/modules/jobs/jobs/data-export/data-export.processor.ts
  packages/nocodb/src/plugins/s3/S3.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/attachments.service.ts
  packages/nocodb/src/services/public-datas.service.ts
Labels: 🔦 Type: Feature, size:XL, lgtm

#9066 fix: remove extra slash from path
  packages/nocodb/src/models/PresignedUrl.ts
Labels: 🔦 Type: Feature, size:XS, lgtm

#9048 feat: formula formatting support
  packages/nc-gui/components/smartsheet/FormulaWrapperCell.vue
  packages/nc-gui/components/smartsheet/PlainCell.vue
  packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
  packages/nc-gui/components/virtual-cell/Formula.vue
  packages/nc-gui/lang/en.json
  packages/nocodb-sdk/src/lib/UITypes.ts
  packages/nocodb-sdk/src/lib/index.ts
Labels: 🔦 Type: Feature, 🛑 Status: Do Not Merge, size:XL, lgtm

#9058 fix: 'Create View' button appearing through sharing link of Base #9055
  packages/nc-gui/components/dashboard/TreeView/ViewsList.vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#9067 fix: attachment related issues
  packages/nc-gui/components/cell/attachment/UploadProviders/Url.vue
  packages/nocodb/src/services/attachments.service.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9065 Nc feat: audit logs pagination keyboard shortcuts support
  packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/components/workspace/AuditLogs.vue
  packages/nc-gui/composables/usePaginationShortcuts.ts
  packages/nc-gui/store/workspace.ts
Labels: 🔦 Type: Feature, size:M, lgtm

#8990 feat: attachments in browser
  packages/nc-gui/assets/nc-icons/globe.svg
  packages/nc-gui/assets/nc-icons/google-docs.svg
  packages/nc-gui/assets/nc-icons/play.svg
  packages/nc-gui/components/cell/attachment/AttachFile.vue
  packages/nc-gui/components/cell/attachment/Carousel.vue
  packages/nc-gui/components/cell/attachment/Modal.vue
  packages/nc-gui/components/cell/attachment/Preview/Image.vue
  packages/nc-gui/components/cell/attachment/Preview/MiscOffice.vue
  packages/nc-gui/components/cell/attachment/Preview/Pdf.vue
  packages/nc-gui/components/cell/attachment/Preview/Video.vue
  packages/nc-gui/components/cell/attachment/UploadProviders/Local.vue
  packages/nc-gui/components/cell/attachment/UploadProviders/Url.vue
  packages/nc-gui/components/cell/attachment/index.vue
  packages/nc-gui/components/cell/attachment/utils.ts
  packages/nc-gui/components/dashboard/View.vue
  packages/nc-gui/components/general/DeleteModal.vue
  packages/nc-gui/components/general/FormBanner.vue
  packages/nc-gui/components/general/Overlay.vue
  packages/nc-gui/components/nc/Carousel/Content.vue
  packages/nc-gui/components/nc/Carousel/Item.vue
  packages/nc-gui/components/nc/Carousel/Next.vue
  packages/nc-gui/components/nc/Carousel/Previous.vue
  packages/nc-gui/components/nc/Carousel/index.vue
  packages/nc-gui/components/nc/Carousel/interface.ts
  packages/nc-gui/components/nc/Carousel/useCarousel.ts
  packages/nc-gui/components/nc/Tooltip.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/Gallery.vue
  packages/nc-gui/components/smartsheet/Kanban.vue
  packages/nc-gui/components/smartsheet/calendar/MonthView.vue
  packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
  packages/nc-gui/components/smartsheet/expanded-form/Comments.vue
  packages/nc-gui/components/smartsheet/expanded-form/Sidebar/Audits.vue
  packages/nc-gui/components/smartsheet/expanded-form/Sidebar/Comments.vue
  packages/nc-gui/components/smartsheet/expanded-form/Sidebar/index.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/components/virtual-cell/components/ListItem.vue
  packages/nc-gui/composables/useExpandedFormStore.ts
  packages/nc-gui/composables/useRowComments.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/package.json
  packages/nc-gui/plugins/pdf-object.ts
  packages/nc-gui/utils/fileUtils.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/nocodb-sdk/src/lib/Api.ts
  pnpm-lock.yaml
  tests/playwright/pages/Dashboard/common/Cell/AttachmentCell.ts
  tests/playwright/tests/db/columns/columnAttachments.spec.ts
  tests/playwright/tests/db/views/viewForm.spec.ts
Labels: 🔦 Type: Feature, size:XXL, lgtm

#9040 feat: groupby bulk apis
  packages/nc-gui/components/smartsheet/grid/GroupBy.vue
  packages/nc-gui/components/smartsheet/grid/GroupByTable.vue
  packages/nc-gui/components/smartsheet/grid/PaginationV2.vue
  packages/nc-gui/composables/useSharedView.ts
  packages/nc-gui/composables/useViewGroupBy.ts
  packages/nc-gui/store/views.ts
  packages/nocodb/src/controllers/data-table.controller.ts
  packages/nocodb/src/controllers/public-datas.controller.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/sql-data-mapper/lib/BaseModel.ts
  packages/nocodb/src/helpers/extractLimitAndOffset.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/data-table.service.ts
  packages/nocodb/src/services/public-datas.service.ts
  tests/playwright/pages/Dashboard/Grid/Group.ts
  tests/playwright/pages/Dashboard/common/Toolbar/Groupby.ts
Labels: 🔦 Type: Feature, size:XXL

#9069 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9071 Nc fix/ssl prop related
  packages/nc-gui/components/dashboard/TreeView/ViewsList.vue
  packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue
  packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/components/workspace/AuditLogs.vue
  packages/nc-gui/composables/usePaginationShortcuts.ts
  packages/nc-gui/store/views.ts
  packages/nc-gui/utils/baseCreateUtils.ts
  packages/nocodb-sdk/src/lib/connectionConfigUtils.ts
  packages/nocodb-sdk/src/lib/enums.ts
  packages/nocodb-sdk/src/lib/index.ts
  packages/nocodb/src/controllers/utils.controller.ts
  packages/nocodb/src/services/sources.service.ts
Labels: size:L, lgtm

#9070 fix[build-local-docker-image.sh]: pnpm i -> pnpm bootstrap.
  build-local-docker-image.sh
Labels: size:XS, lgtm

#8974 feat: thumbnail generator
  packages/nc-gui/components/cell/attachment/Carousel.vue
  packages/nc-gui/components/cell/attachment/Modal.vue
  packages/nc-gui/components/cell/attachment/Preview/Image.vue
  packages/nc-gui/components/cell/attachment/index.vue
  packages/nc-gui/components/smartsheet/Gallery.vue
  packages/nc-gui/components/smartsheet/Kanban.vue
  packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
  packages/nc-gui/components/virtual-cell/components/ListItem.vue
  packages/nc-gui/composables/useAttachment.ts
  packages/nocodb/.gitignore
  packages/nocodb/src/controllers/attachments-secure.controller.ts
  packages/nocodb/src/controllers/attachments.controller.spec.ts
  packages/nocodb/src/controllers/attachments.controller.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/interface/Jobs.ts
  packages/nocodb/src/modules/jobs/fallback/fallback-queue.service.ts
  packages/nocodb/src/modules/jobs/jobs.module.ts
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
  packages/nocodb/src/modules/noco.module.ts
  packages/nocodb/src/plugins/backblaze/Backblaze.ts
  packages/nocodb/src/plugins/gcs/Gcs.ts
  packages/nocodb/src/plugins/linode/LinodeObjectStorage.ts
  packages/nocodb/src/plugins/mino/Minio.ts
  packages/nocodb/src/plugins/ovhCloud/OvhCloud.ts
  packages/nocodb/src/plugins/s3/S3.ts
  packages/nocodb/src/plugins/scaleway/ScalewayObjectStorage.ts
  packages/nocodb/src/plugins/spaces/Spaces.ts
  packages/nocodb/src/plugins/storage/Local.ts
  packages/nocodb/src/plugins/upcloud/UpoCloud.ts
  packages/nocodb/src/plugins/vultr/Vultr.ts
  packages/nocodb/src/services/attachments.service.ts
  packages/nocodb/src/services/public-datas.service.ts
Labels: 🔦 Type: Feature, size:XXL, lgtm

#9075 chore: sync dependencies
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/package.json
  pnpm-lock.yaml
Labels: 🤖 Bot: Dependencies, size:L, lgtm

#9077 Nc feat/3424 prefill links
  packages/nc-gui/composables/useSharedFormViewStore.ts
Labels: size:L, lgtm

#9086 Executable build action changes for supporting sharp library
  .github/workflows/release-executables.yml
Labels: size:M, lgtm

#9090 New Crowdin updates
  packages/nc-gui/lang/uk.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9085 feat: Add lookups from Link field context menu
  packages/nc-gui/components/smartsheet/header/AddLookups.vue
  packages/nc-gui/components/smartsheet/header/Menu.vue
  packages/nc-gui/components/smartsheet/header/UpdateDisplayValue.vue
  packages/nc-gui/lang/en.json
Labels: 🔦 Type: Feature, size:L, lgtm

#9092 fix: non-ascii characters on attachment names
  packages/nocodb/package.json
  packages/nocodb/src/controllers/attachments.controller.ts
  packages/nocodb/src/models/PresignedUrl.ts
  pnpm-lock.yaml
Labels: 🐛 Type: Bug, size:S, lgtm

#9088 fix: thumbnail generation failing in Other S3 providers
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9096 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9097 fix: use same key while grouping insert records
  packages/nocodb/src/models/Column.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9100 fix(nc-gui): if focus is on submit btn then only form should submit
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#9095 fix: improve & unify attachment handling
  packages/nocodb/src/controllers/attachments-secure.controller.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/helpers/attachmentHelpers.ts
  packages/nocodb/src/models/FormView.ts
  packages/nocodb/src/models/PresignedUrl.ts
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
  packages/nocodb/src/plugins/s3/S3.ts
  packages/nocodb/src/plugins/storage/Local.ts
  packages/nocodb/src/services/attachments.service.ts
  packages/nocodb/src/services/public-datas.service.ts
Labels: 🐛 Type: Bug, size:XL, lgtm

#9091 Nc fix/duplicate default view
  packages/nc-gui/components/dashboard/TreeView/TableNode.vue
  packages/nc-gui/composables/useTableNew.ts
Labels: size:M

#9105 docs: fix roles table
  packages/noco-docs/docs/110.roles-and-permissions/010.roles-permissions-overview.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9107 fix: add fetch-options
  packages/nc-plugin/src/lib/IStorageAdapterV2.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9101 fix: thumbnail errors & path
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
  packages/nocodb/src/plugins/s3/S3.ts
  packages/nocodb/src/services/attachments.service.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9072 feat: Formula colouring and improved suggestions
  packages/nc-gui/components/cell/ClampedText.vue
  packages/nc-gui/components/monaco/Editor.vue
  packages/nc-gui/components/monaco/formula.ts
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
  packages/nc-gui/components/virtual-cell/Formula.vue
  packages/nc-gui/package.json
  packages/nc-gui/plugins/monaco.ts
  packages/nc-gui/utils/urlUtils.ts
  pnpm-lock.yaml
  tests/playwright/pages/Dashboard/Grid/Column/index.ts
  tests/playwright/tests/db/columns/columnFormula.spec.ts
Labels: 🔦 Type: Feature, size:XL, lgtm

#9093 chore: remove unused dependencies
  packages/nc-gui/package.json
  packages/nocodb/package.json
  pnpm-lock.yaml
Labels: size:S, lgtm

#9112 Nc fix/sentry errors
  packages/nc-gui/app.vue
  packages/nc-gui/components/smartsheet/Kanban.vue
  packages/nc-gui/components/smartsheet/expanded-form/RichComment.vue
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/composables/useKanbanViewStore.ts
  packages/nc-gui/composables/useSmartsheetStore.ts
  packages/nc-gui/composables/useViewColumns.ts
  packages/nc-gui/composables/useViewData.ts
  packages/nc-gui/store/bases.ts
Labels: size:L, lgtm

#9123 chore: wrap options & allow extending storage adapter
  packages/nc-plugin/src/lib/IStorageAdapterV2.ts
Labels: size:S, lgtm

#9119 fix(nc-gui): Linked item fields show wrong order in popup
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/smartsheet/grid/useColumnDrag.ts
  packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
  packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
  packages/nc-gui/composables/useViewColumns.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9124 fix(nc-gui): Fields are missing in details if directly navigated
  packages/nc-gui/components/smartsheet/details/Fields.vue
Labels: 🐛 Type: Bug, size:XS, lgtm
