Repository nocodb/nocodb, pull requests merged in 2024-01, with the labels that each got.

#7355 fix: Avoid resetting input field when using Links in expanded form
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/composables/useExpandedFormStore.ts
Labels: 🛑 Status: Do Not Merge

#7376 Multifield editor bug fixes ( Sync EE to OSS )
  packages/nc-gui/components/smartsheet/VirtualCell.vue
  packages/nc-gui/components/smartsheet/details/Fields.vue
  packages/nc-gui/components/smartsheet/grid/GroupByLabel.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/components/virtual-cell/components/ListChildItems.vue
  packages/nc-gui/components/virtual-cell/components/ListItems.vue
  packages/nc-gui/composables/useLTARStore.ts
  packages/nocodb/src/services/columns.service.ts
Labels: trigger-CI

#7389 Feat: bulk delete records ( Sync EE to OSS )
  packages/nc-gui/composables/useData.ts
  packages/nc-gui/utils/dataUtils.ts
  packages/nocodb-sdk/src/lib/UITypes.ts
Labels: trigger-CI

#7466 Nc: Expanded form and cell fields bug fixes
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/cell/Checkbox.vue
  packages/nc-gui/components/cell/Currency.vue
  packages/nc-gui/components/cell/DatePicker.vue
  packages/nc-gui/components/cell/DateTimePicker.vue
  packages/nc-gui/components/cell/Decimal.vue
  packages/nc-gui/components/cell/Duration.vue
  packages/nc-gui/components/cell/Email.vue
  packages/nc-gui/components/cell/Float.vue
  packages/nc-gui/components/cell/GeoData.vue
  packages/nc-gui/components/cell/Integer.vue
  packages/nc-gui/components/cell/Json.vue
  packages/nc-gui/components/cell/MultiSelect.vue
  packages/nc-gui/components/cell/Percent.vue
  packages/nc-gui/components/cell/PhoneNumber.vue
  packages/nc-gui/components/cell/Rating.vue
  packages/nc-gui/components/cell/RichText.vue
  packages/nc-gui/components/cell/SingleSelect.vue
  packages/nc-gui/components/cell/Text.vue
  packages/nc-gui/components/cell/TimePicker.vue
  packages/nc-gui/components/cell/Url.vue
  packages/nc-gui/components/cell/User.vue
  packages/nc-gui/components/cell/YearPicker.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue
  packages/nc-gui/components/smartsheet/Cell.vue
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/column/LinkOptions.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/smartsheet/header/CellIcon.ts
  packages/nc-gui/components/smartsheet/header/VirtualCellIcon.ts
  packages/nc-gui/components/smartsheet/toolbar/SortListMenu.vue
  packages/nc-gui/components/virtual-cell/BelongsTo.vue
  packages/nc-gui/components/virtual-cell/Formula.vue
  packages/nc-gui/components/virtual-cell/Links.vue
  packages/nc-gui/components/virtual-cell/Lookup.vue
  packages/nc-gui/components/virtual-cell/Rollup.vue
  packages/nc-gui/components/virtual-cell/barcode/Barcode.vue
  packages/nc-gui/components/virtual-cell/components/ListChildItems.vue
  packages/nc-gui/components/virtual-cell/components/ListItem.vue
  packages/nc-gui/composables/useColumnCreateStore.ts
Labels: trigger-CI

#7403 Nc fix: Skip getting column list from database on table/column create
  packages/nocodb/src/services/columns.service.ts
  packages/nocodb/src/services/tables.service.ts
Labels: trigger-CI

#7490 Nc: Enable command palette for oss
  packages/nc-gui/app.vue
  packages/nc-gui/assets/css/typesense-docsearch.css
  packages/nc-gui/components/cmd-footer/index.vue
  packages/nc-gui/components/cmd-j/index.vue
  packages/nc-gui/components/cmd-k/command-score.ts
  packages/nc-gui/components/cmd-k/index.vue
  packages/nc-gui/components/cmd-l/index.vue
  packages/nc-gui/components/dashboard/Sidebar/TopSection/Header.vue
  packages/nc-gui/components/workspace/CreateProjectDlg.vue
  packages/nc-gui/composables/useCommandPalette/commands.ts
  packages/nc-gui/composables/useCommandPalette/index.ts
  packages/nc-gui/lib/types.ts
  packages/nc-gui/nuxt.config.ts
  packages/nc-gui/plugins/tele.ts
  packages/nc-gui/public/js/typesense-docsearch.js
  packages/nocodb/src/controllers/command-palette.controller.spec.ts
  packages/nocodb/src/controllers/command-palette.controller.ts
  packages/nocodb/src/modules/metas/metas.module.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/command-palette.service.spec.ts
  packages/nocodb/src/services/command-palette.service.ts
Labels: trigger-CI

#7500 Nc fix: Groupby doesn't work if formula field dataType is numeric
  packages/nc-gui/components/smartsheet/grid/GroupBy.vue
  packages/nocodb/src/db/conditionV2.ts
Labels: trigger-CI

#7478 Nc fix/UI bug fixes
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/grid/GroupByLabel.vue
  packages/nc-gui/components/virtual-cell/BelongsTo.vue
  packages/nocodb-sdk/src/lib/helperFunctions.ts
  packages/nocodb/src/models/Column.ts
  packages/nocodb/src/models/View.ts
  tests/playwright/pages/Dashboard/Grid/Column/index.ts
  tests/playwright/pages/Dashboard/common/Toolbar/Fields.ts
  tests/playwright/tests/db/columns/columnLinkToAnotherRecord.spec.ts
  tests/playwright/tests/db/columns/columnMenuOperations.spec.ts
  tests/playwright/tests/db/columns/columnRelationalExtendedTests.spec.ts
  tests/playwright/tests/db/features/metaLTAR.spec.ts
  tests/playwright/tests/db/views/viewGridShare.spec.ts
Labels: trigger-CI

#7491 feat: add attachments from clipboard
  packages/nc-gui/composables/useMultiSelect/convertCellData.ts
  packages/nc-gui/composables/useMultiSelect/index.ts
  packages/nocodb-sdk/src/lib/helperFunctions.ts
Labels: 🚥 Status: On Hold
