Repository nocodb/nocodb, pull requests merged in 2024-08, with the labels that each got.

#9130 fix: aggregtaion not getting updated
  packages/nc-gui/composables/useViewGroupBy.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9131 fix: One-to-one meta sync issue
  packages/nocodb/src/services/meta-diffs.service.ts
Labels: size:XS, lgtm

#9113 Nc fix: replace ant design table
  packages/nc-gui/components/account/UserList.vue
  packages/nc-gui/components/dashboard/settings/Metadata.vue
  packages/nc-gui/components/dashboard/settings/UIAcl.vue
  packages/nc-gui/components/general/MaintenanceAlert.vue
  packages/nc-gui/components/nc/Table.vue
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nc-gui/components/project/AllTables.vue
  packages/nc-gui/components/template/Editor.vue
  packages/nc-gui/components/template/utils.ts
  packages/nc-gui/components/workspace/AuditLogs.vue
  packages/nc-gui/components/workspace/CollaboratorsList.vue
  packages/nc-gui/lib/types.ts
  tests/playwright/pages/Account/Users.ts
  tests/playwright/pages/Dashboard/Import/ImportTemplate.ts
  tests/playwright/pages/Dashboard/ProjectView/Metadata.ts
Labels: 🐛 Type: Bug, size:XXL, lgtm

#9136 New Crowdin updates
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9139 i18n: update chinese
  packages/nc-gui/lang/zh-Hans.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9142 fix: Sub-group loading issue
  packages/nc-gui/components/smartsheet/grid/GroupBy.vue
  packages/nc-gui/components/workspace/CollaboratorsList.vue
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/services/meta-diffs.service.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9134 Nc fix/show inherited role in project members table
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nc-gui/components/roles/Selector.vue
  packages/nc-gui/lang/en.json
Labels: 🐛 Type: Bug, size:M, lgtm

#9152 fix: replace body with merged config while validation connection - so…
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
Labels: size:XS, lgtm

#9154 Nc fix/throttler logging
  packages/nocodb/src/filters/global-exception/global-exception.filter.ts
Labels: size:M, lgtm

#9151 fix: properly export looked up attachments
  packages/nocodb/src/helpers/dataHelpers.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9141 Nc feat/webhook UI
  packages/nc-gui/assets/nc-icons/mail.svg
  packages/nc-gui/assets/nc-icons/mattermost.svg
  packages/nc-gui/assets/nc-icons/microsoft-teams.svg
  packages/nc-gui/assets/nc-icons/slack.svg
  packages/nc-gui/assets/nc-icons/twilio.svg
  packages/nc-gui/assets/nc-icons/whatsapp.svg
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/api-client/Headers.vue
  packages/nc-gui/components/api-client/Params.vue
  packages/nc-gui/components/monaco/Editor.vue
  packages/nc-gui/components/nc/Modal.vue
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nc-gui/components/smartsheet/details/Webhooks.vue
  packages/nc-gui/components/smartsheet/sidebar/toolbar/Webhook.vue
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
  packages/nc-gui/components/smartsheet/toolbar/MoreActions.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewActions.vue
  packages/nc-gui/components/webhook/Drawer.vue
  packages/nc-gui/components/webhook/Editor.vue
  packages/nc-gui/components/webhook/List.vue
  packages/nc-gui/components/webhook/Modal.vue
  packages/nc-gui/components/webhook/Test.vue
  packages/nc-gui/components/webhook/index.vue
  packages/nc-gui/components/workspace/CollaboratorsList.vue
  packages/nc-gui/composables/useUserSorts.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/lib/types.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/noco-docs/docs/130.automation/020.webhook/020.create-webhook.md
  packages/noco-docs/static/img/v2/automations/webhooks/create-webhook-2.png
  packages/noco-docs/static/img/v2/webhook/webhook-list-2.png
  packages/noco-docs/static/img/v2/webhook/webhook-list-3.png
  tests/playwright/pages/Dashboard/Details/WebhookPage.ts
  tests/playwright/pages/Dashboard/WebhookForm/index.ts
  tests/playwright/tests/db/features/webhook.spec.ts
Labels: 🔦 Type: Feature, size:XXL, lgtm

#9164 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/en.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9166 fix: external source with project create
  packages/nocodb/src/services/bases.service.ts
Labels: size:S, lgtm

#9149 fix: Miscellaneous bugs
  packages/nc-gui/components/dlg/ViewDelete.vue
  packages/nc-gui/components/dlg/share-and-collaborate/View.vue
  packages/nc-gui/components/nc/ErrorBoundary.vue
  packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
  packages/nc-gui/composables/useGlobal/state.ts
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/package.json
  packages/nc-gui/plugins/error-handler.ts
  packages/nc-gui/plugins/sentry.ts
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/noco-docs/versioned_docs/version-0.109.7/020.getting-started/020.environment-variables.md
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/package.json
  packages/nocodb/src/helpers/webhookHelpers.ts
  packages/nocodb/src/models/Model.ts
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/utils.service.ts
  pnpm-lock.yaml
Labels: 🐛 Type: Bug, size:XL, lgtm

#9167 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9169 Nc fix/integration followup
  packages/nc-gui/assets/nc-icons/whatsapp-solid.svg
  packages/nc-gui/components/dashboard/settings/DataSources.vue
  packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue
  packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
  packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
  packages/nc-gui/utils/iconUtils.ts
  packages/nc-gui/utils/syncDataUtils.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9161 Nc fix/integration corrections
  packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue
  packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue
  packages/nc-gui/components/dashboard/settings/data-sources/SourceRestrictions.vue
  packages/nc-gui/components/project/AllTables.vue
  packages/nc-gui/components/project/SyncDataModal.vue
  packages/nc-gui/components/workspace/integrations/List.vue
  packages/nc-gui/components/workspace/integrations/newAvailableList.vue
  packages/nc-gui/lang/en.json
Labels: 🐛 Type: Bug, size:XL, lgtm

#9170 fix(nc-gui): integration pr merge conflicts
  packages/nc-gui/components/workspace/integrations/List.vue
  packages/nc-gui/components/workspace/integrations/newAvailableList.vue
Labels: 🐛 Type: Bug, size:XXL, lgtm

#9125 fix(nc-gui): enable Limit record selection to a view in oss
  packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
  packages/nocodb/src/db/BaseModelSqlv2.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9163 fix: Load sharp package dynamically to handle loading error gracefully
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
  packages/nocodb/src/services/attachments.service.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9171 docs: integrations
  packages/nc-gui/components/dashboard/settings/data-sources/SupportedDocs.vue
  packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
  packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
  packages/nc-gui/components/workspace/integrations/SupportedDocs.vue
  packages/nc-gui/components/workspace/integrations/forms/EditOrAddDatabase.vue
  packages/nc-gui/utils/syncDataUtils.ts
  packages/noco-docs/docs/095.integrations/010.overview.md
  packages/noco-docs/docs/095.integrations/020.create-connection.md
  packages/noco-docs/docs/095.integrations/030.actions-on-connection.md
  packages/noco-docs/docs/095.integrations/_category_.json
  packages/noco-docs/docs/100.data-sources/010.data-source-overview.md
  packages/noco-docs/docs/100.data-sources/020.connect-to-data-source.md
  packages/noco-docs/docs/100.data-sources/030.sync-with-data-source.md
  packages/noco-docs/docs/100.data-sources/040.actions-on-data-sources.md
  packages/noco-docs/static/img/v2/data-source/data-source-1.png
  packages/noco-docs/static/img/v2/data-source/data-source-2.png
  packages/noco-docs/static/img/v2/data-source/data-source-3.png
  packages/noco-docs/static/img/v2/data-source/data-source-audit.png
  packages/noco-docs/static/img/v2/data-source/data-source-edit.png
  packages/noco-docs/static/img/v2/data-source/data-source-erd.png
  packages/noco-docs/static/img/v2/data-source/data-source-list.png
  packages/noco-docs/static/img/v2/data-source/data-source-meta-sync-1.png
  packages/noco-docs/static/img/v2/data-source/data-source-meta-sync-2.png
  packages/noco-docs/static/img/v2/data-source/data-source-permissions.png
  packages/noco-docs/static/img/v2/data-source/data-source-remove-2.png
  packages/noco-docs/static/img/v2/data-source/data-source-remove.png
  packages/noco-docs/static/img/v2/data-source/data-source-uiacl.png
  packages/noco-docs/static/img/v2/data-source/data-source-visibility.png
  packages/noco-docs/static/img/v2/integrations/connection-list-actions.png
  packages/noco-docs/static/img/v2/integrations/connection-url-2.png
  packages/noco-docs/static/img/v2/integrations/connection-url.png
  packages/noco-docs/static/img/v2/integrations/connections-delete-confirmation.png
  packages/noco-docs/static/img/v2/integrations/connections-list.png
  packages/noco-docs/static/img/v2/integrations/integrations-1.png
  packages/noco-docs/static/img/v2/integrations/integrations-2.png
  packages/noco-docs/static/img/v2/integrations/mysql-connection.png
  packages/noco-docs/static/img/v2/integrations/postgres-connection.png
Labels: 📋 Scope : Docs, size:L, lgtm

#9174 Nc fix/minor bug fixes1
  packages/nc-gui/components/project/AllTables.vue
  packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
Labels: size:L, lgtm

#9173 fix: pw test fail issue
  packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
  packages/nocodb-sdk/src/lib/Api.ts
  tests/playwright/pages/Dashboard/ProjectView/DataSourcePage.ts
Labels: Scope : Test [E2E], size:XS, lgtm

#9175 Nc fix/minor bug fixes1 merge conflict
  packages/nc-gui/components/dashboard/settings/DataSources.vue
  packages/nc-gui/components/project/AllTables.vue
  packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
Labels: 🐛 Type: Bug, size:M, lgtm

#9177 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/en.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:XXL, lgtm

#9132 🖱 Add `title` attribute to `AdvancedOptions.vue` on mouse hover
  packages/nc-gui/components/smartsheet/column/AdvancedOptions.vue
Labels: 🔦 Type: Feature, size:S, lgtm

#9176 Miscellaneous bug fixes and improvements
  packages/nc-gui/assets/img/giftCard.svg
  packages/nc-gui/assets/nc-icons/gift.svg
  packages/nc-gui/components/dashboard/Sidebar.vue
  packages/nc-gui/components/general/Gift.vue
  packages/nc-gui/composables/useGlobal/state.ts
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/nocodb/src/controllers/integrations.controller.ts
  packages/nocodb/src/models/Integration.ts
  packages/nocodb/src/modules/auth/auth.controller.ts
  packages/nocodb/src/services/integrations.service.ts
  packages/nocodb/src/services/users/users.service.ts
  packages/nocodb/src/services/utils.service.ts
Labels: size:L, lgtm

#9180 test: fix user management flaky test
  tests/playwright/pages/Account/Users.ts
Labels: 🛑 Status: Do Not Merge, Scope : Test [E2E], size:XS, lgtm

#9178 fix(nc-gui): show empty state if integration search list is empty
  packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
Labels: 🐛 Type: Bug, size:S, lgtm

#9181 Sidebar banner ui corrections
  packages/nc-gui/components/dashboard/Sidebar.vue
  packages/nc-gui/components/general/Gift.vue
Labels: 👓 Scope : View, size:M, lgtm

#9137 fix: s3 add forcePathStyle config
  packages/nocodb/src/helpers/NcPluginMgrv2.ts
  packages/nocodb/src/plugins/GenericS3/GenericS3.ts
  packages/nocodb/src/plugins/backblaze/Backblaze.ts
  packages/nocodb/src/plugins/s3/S3.ts
  packages/nocodb/src/plugins/s3/index.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9182 Nc fix(nc-gui): Hide pre-filled fields form submit issue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/composables/useFormViewStore.ts
  packages/nc-gui/composables/useSharedFormViewStore.ts
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue
Labels: 🐛 Type: Bug, 👓 Scope : View, size:M, lgtm

#9183 fix: docs link
  packages/noco-docs/docs/095.integrations/010.overview.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9189 fix: Integration delete related bugs
  packages/nocodb-sdk/src/lib/globals.ts
  packages/nocodb/src/meta/meta.service.ts
  packages/nocodb/src/models/Integration.ts
  packages/nocodb/src/services/integrations.service.ts
  packages/nocodb/src/utils/globals.ts
  packages/nocodb/tests/unit/rest/index.test.ts
  packages/nocodb/tests/unit/rest/tests/integration.test.ts
Labels: 🐛 Type: Bug, trigger-CI, size:L, lgtm

#9184 Nc fix/integration minor changes
  packages/nc-gui/assets/nc-icons/claude.svg
  packages/nc-gui/assets/nc-icons/groq.svg
  packages/nc-gui/assets/nc-icons/ollama.svg
  packages/nc-gui/assets/nc-icons/openai.svg
  packages/nc-gui/components/dashboard/Sidebar.vue
  packages/nc-gui/components/dashboard/settings/DataSources.vue
  packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue
  packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue
  packages/nc-gui/components/general/Gift.vue
  packages/nc-gui/components/general/Overlay.vue
  packages/nc-gui/components/project/SyncDataModal.vue
  packages/nc-gui/components/project/View.vue
  packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
  packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
  packages/nc-gui/components/workspace/integrations/forms/EditOrAddDatabase.vue
  packages/nc-gui/composables/useIntegrationsStore.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/lib/enums.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/nc-gui/utils/syncDataUtils.ts
  packages/nocodb-sdk/src/lib/enums.ts
  tests/playwright/pages/Dashboard/ProjectView/DataSourcePage.ts
  tests/playwright/pages/Dashboard/ProjectView/SourcePage.ts
Labels: 🐛 Type: Bug, 🌞 Scope : Data source, size:L, lgtm

#9194 fix: Formula order by issue with constant value
  packages/nocodb/src/db/sortV2.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9192 feat: configure S3 acl from envs
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/nocodb/src/helpers/NcPluginMgrv2.ts
  packages/nocodb/src/plugins/s3/S3.ts
  packages/nocodb/src/plugins/s3/index.ts
  packages/nocodb/src/utils/cloud/populateCloudPlugins.ts
Labels: 🔦 Type: Feature, size:M, lgtm

#9197 New Crowdin updates
  packages/nc-gui/lang/ja.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9199 Nc fix(nc-gui): grid view issues
  packages/nc-gui/components/smartsheet/Gallery.vue
  packages/nc-gui/components/smartsheet/Kanban.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/components/smartsheet/grid/index.vue
  packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
  packages/nc-gui/composables/useViewGroupBy.ts
Labels: 👓 Scope : View, size:S, lgtm

#9200 fix: multiple troggering of expanded-record
  packages/nc-gui/components/smartsheet/grid/GroupByTable.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/composables/useViewGroupBy.ts
Labels: 🐛 Type: Bug, 👓 Scope : View, size:S, lgtm

#9216 fix: extension items
  packages/nc-gui/components/extensions/Details.vue
  packages/nc-gui/composables/useExtensionHelper.ts
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/extensions/json-exporter/icon.png
  packages/nc-gui/extensions/json-exporter/manifest.json
  packages/nc-gui/package.json
  pnpm-lock.yaml
Labels: 🔭 Scope : Project, size:M, lgtm

#9221 misc: reorder integrations
  packages/nc-gui/utils/syncDataUtils.ts
Labels: size:S, lgtm

#9205 fix: minio related issues
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
  packages/nocodb/src/plugins/mino/Minio.ts
  packages/nocodb/src/plugins/mino/index.ts
  packages/nocodb/src/services/attachments.service.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9213 feat: allow self-signed certificate for Minio
  packages/nocodb/src/plugins/mino/Minio.ts
  packages/nocodb/src/plugins/mino/index.ts
Labels: 🔦 Type: Feature, size:S, lgtm

#9210 chore: use local nc-plugin
  .github/workflows/release-docker.yml
  .github/workflows/release-npm.yml
  .github/workflows/sync-to-develop.yml
  package.json
  packages/nc-plugin/package.json
  packages/nocodb-sdk/package.json
  packages/nocodb/Dockerfile
  packages/nocodb/Dockerfile.local
  packages/nocodb/docker/webpack.config.js
  packages/nocodb/package.json
  packages/nocodb/src/db/sql-migrator/lib/KnexMigratorv2.ts
  packages/nocodb/webpack.config.js
  packages/nocodb/webpack.local.config.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size:M, lgtm

#9226 misc: add spreadsheet category
  packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
  packages/nc-gui/lang/en.json
  packages/nc-gui/utils/syncDataUtils.ts
  packages/nocodb-sdk/src/lib/enums.ts
Labels: size:M, lgtm

#9215 feat: attachment references
  packages/nc-gui/components/dlg/AirtableImport.vue
  packages/nc-gui/composables/useData.ts
  packages/nc-plugin/src/lib/IStorageAdapterV2.ts
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/helpers/attachmentHelpers.ts
  packages/nocodb/src/helpers/migrationJobs.ts
  packages/nocodb/src/interface/Jobs.ts
  packages/nocodb/src/meta/meta.service.ts
  packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
  packages/nocodb/src/meta/migrations/v2/nc_057_file_references.ts
  packages/nocodb/src/models/Column.ts
  packages/nocodb/src/models/FileReference.ts
  packages/nocodb/src/models/Model.ts
  packages/nocodb/src/models/PresignedUrl.ts
  packages/nocodb/src/models/index.ts
  packages/nocodb/src/modules/jobs/fallback/fallback-queue.service.ts
  packages/nocodb/src/modules/jobs/fallback/jobs.service.ts
  packages/nocodb/src/modules/jobs/helpers.ts
  packages/nocodb/src/modules/jobs/jobs.module.ts
  packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
  packages/nocodb/src/modules/jobs/jobs/at-import/helpers/readAndProcessData.ts
  packages/nocodb/src/modules/jobs/jobs/attachment-clean-up/attachment-clean-up.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
  packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts
  packages/nocodb/src/modules/jobs/migration-jobs/nc_job_001_attachment.ts
  packages/nocodb/src/modules/jobs/migration-jobs/nc_job_002_thumbnail.ts
  packages/nocodb/src/modules/jobs/redis/jobs-redis.ts
  packages/nocodb/src/modules/jobs/redis/jobs.service.ts
  packages/nocodb/src/plugins/GenericS3/GenericS3.ts
  packages/nocodb/src/plugins/backblaze/Backblaze.ts
  packages/nocodb/src/plugins/gcs/Gcs.ts
  packages/nocodb/src/plugins/linode/LinodeObjectStorage.ts
  packages/nocodb/src/plugins/mino/Minio.ts
  packages/nocodb/src/plugins/ovhCloud/OvhCloud.ts
  packages/nocodb/src/plugins/r2/R2.ts
  packages/nocodb/src/plugins/s3/S3.ts
  packages/nocodb/src/plugins/scaleway/ScalewayObjectStorage.ts
  packages/nocodb/src/plugins/spaces/Spaces.ts
  packages/nocodb/src/plugins/storage/Local.ts
  packages/nocodb/src/plugins/upcloud/UpoCloud.ts
  packages/nocodb/src/plugins/vultr/Vultr.ts
  packages/nocodb/src/providers/init-meta-service.provider.ts
  packages/nocodb/src/services/attachments.service.ts
  packages/nocodb/src/utils/globals.ts
Labels: 🔦 Type: Feature, size:XXL, lgtm

#9204 Nc feat: header revamp
  packages/nc-gui/assets/nc-icons/chevron-down-small.svg
  packages/nc-gui/assets/nc-icons/chevron-up-down-small.svg
  packages/nc-gui/assets/nc-icons/chevron-up-small.svg
  packages/nc-gui/assets/nc-icons/home1.svg
  packages/nc-gui/assets/nc-icons/slash1.svg
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/account/AppStore.vue
  packages/nc-gui/components/account/Breadcrumb.vue
  packages/nc-gui/components/account/Integration.vue
  packages/nc-gui/components/account/Profile.vue
  packages/nc-gui/components/account/ResetPassword.vue
  packages/nc-gui/components/account/SignupSettings.vue
  packages/nc-gui/components/account/Token.vue
  packages/nc-gui/components/account/UserList.vue
  packages/nc-gui/components/dashboard/Sidebar.vue
  packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
  packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue
  packages/nc-gui/components/dashboard/settings/AppStore.vue
  packages/nc-gui/components/dashboard/settings/DataSources.vue
  packages/nc-gui/components/general/ApiLoader.vue
  packages/nc-gui/components/general/OpenLeftSidebarBtn.vue
  packages/nc-gui/components/general/ShareProject.vue
  packages/nc-gui/components/general/language/index.vue
  packages/nc-gui/components/nc/List.vue
  packages/nc-gui/components/nc/PageHeader.vue
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nc-gui/components/project/AllTables.vue
  packages/nc-gui/components/project/View.vue
  packages/nc-gui/components/smartsheet/Details.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/Toolbar.vue
  packages/nc-gui/components/smartsheet/Topbar.vue
  packages/nc-gui/components/smartsheet/grid/index.vue
  packages/nc-gui/components/smartsheet/header/VirtualCell.vue
  packages/nc-gui/components/smartsheet/toolbar/LockType.vue
  packages/nc-gui/components/smartsheet/toolbar/OpenedViewAction.vue
  packages/nc-gui/components/smartsheet/toolbar/Reload.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewInfo.vue
  packages/nc-gui/components/smartsheet/topbar/ProjectListDropdown.vue
  packages/nc-gui/components/smartsheet/topbar/SelectMode.vue
  packages/nc-gui/components/smartsheet/topbar/TableListDropdown.vue
  packages/nc-gui/components/smartsheet/topbar/ViewListDropdown.vue
  packages/nc-gui/components/workspace/AuditLogs.vue
  packages/nc-gui/components/workspace/CollaboratorsList.vue
  packages/nc-gui/components/workspace/View.vue
  packages/nc-gui/components/workspace/integrations/view.vue
  packages/nc-gui/pages/account/index.vue
  packages/nc-gui/pages/account/index/[page].vue
  packages/nc-gui/pages/account/index/users/[[nestedPage]].vue
  packages/nc-gui/store/config.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/nc-gui/utils/syncDataUtils.ts
Labels: 🔦 Type: Feature, 🛑 Status: Do Not Merge, 👓 Scope : View, size:XXL, lgtm

#9222 docs: move `NC_ATTACHMENT_EXPIRE_SECONDS` to storage block
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9219 Nc feat/user management
  packages/nc-gui/components/dashboard/Sidebar/TopSection.vue
  packages/nc-gui/components/dlg/InviteDlg.vue
  packages/nc-gui/components/general/Gift.vue
  packages/nc-gui/components/nc/Badge.vue
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nc-gui/components/project/View.vue
  packages/nc-gui/components/roles/Badge.vue
  packages/nc-gui/components/roles/Selector.vue
  packages/nc-gui/components/workspace/CollaboratorsList.vue
  packages/nc-gui/components/workspace/View.vue
  packages/nc-gui/lib/acl.ts
  packages/nc-gui/store/bases.ts
  packages/nocodb-sdk/src/lib/enums.ts
  packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
  packages/nocodb/src/meta/migrations/v2/nc_059_invited_by.ts
  packages/nocodb/src/models/BaseUser.ts
  packages/nocodb/src/models/Integration.ts
  packages/nocodb/src/models/PresignedUrl.ts
  packages/nocodb/src/services/app-hooks/app-hooks.service.ts
  packages/nocodb/src/services/base-users/base-users.service.ts
  packages/nocodb/src/services/integrations.service.ts
  tests/playwright/pages/Dashboard/ProjectView/index.ts
Labels: 🔦 Type: Feature, size:L, lgtm

#9231 chore: skip sdk and lib-gui publish from action (TEMP)
  .github/workflows/release-npm.yml
Labels: size:XS, lgtm

#9232 chore: lint
  .github/workflows/release-npm.yml
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nocodb-sdk/src/lib/Api.ts
Labels: size:L, lgtm

#9239 chore: master action temp fix
  .github/workflows/release-npm.yml
Labels: size:XS, lgtm

#9240 chore: comment remove & target local nocodb-sdk
  .github/workflows/release-npm.yml
  packages/nc-gui/package.json
  packages/nocodb/package.json
  packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
  pnpm-lock.yaml
Labels: size:S, lgtm

#9243 chore: revert action changes master
  .github/workflows/release-npm.yml
Labels: size:XS, lgtm

#9242 chore: revert temp action change
  .github/workflows/release-npm.yml
  README.md
  markdown/readme/languages/chinese.md
  markdown/readme/languages/indonesian.md
  markdown/readme/languages/ukrainian.md
  packages/nocodb/README.md
  packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
Labels: size:S, lgtm

#9246 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/en.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:XL, lgtm

#9244 Nc docs/user management
  packages/noco-docs/docs/020.getting-started/020.quick-start.md
  packages/noco-docs/docs/030.workspaces/020.create-workspace.md
  packages/noco-docs/docs/030.workspaces/030.workspace-collaboration.md
  packages/noco-docs/docs/040.bases/010.base-overview.md
  packages/noco-docs/docs/040.bases/020.create-base.md
  packages/noco-docs/docs/040.bases/050.base-collaboration.md
  packages/noco-docs/docs/040.bases/060.share-base.md
  packages/noco-docs/docs/050.tables/060.actions-on-table.md
  packages/noco-docs/docs/110.roles-and-permissions/010.roles-permissions-overview.md
  packages/noco-docs/docs/120.collaboration/010.workspace-collaboration.md
  packages/noco-docs/docs/120.collaboration/020.base-collaboration.md
  packages/noco-docs/docs/120.collaboration/030.share-base.md
  packages/noco-docs/docs/120.collaboration/050.oss-specific-details.md
  packages/noco-docs/docs/150.engineering/010.architecture.md
  packages/noco-docs/docs/990.FAQs.md
  packages/noco-docs/static/img/v2/workspace/workspace-members-assign-owner.png
Labels: 📋 Scope : Docs, size:L, lgtm

#9260 fix(docs): incorrect github link
  packages/noco-docs/docusaurus.config.js
Labels: 📋 Scope : Docs, size:XS, lgtm

#9266 fix: added missing logo assets for email
  packages/nc-mail-templates/src/assets/discord.png
  packages/nc-mail-templates/src/assets/github.png
  packages/nc-mail-templates/src/assets/linkedin.png
  packages/nc-mail-templates/src/assets/logo.png
  packages/nc-mail-templates/src/assets/x.png
  packages/nc-mail-templates/src/assets/youtube.png
  packages/nc-mail-templates/src/templates/assets/DiscordIcon.ts
  packages/nc-mail-templates/src/templates/assets/GithubIcon.ts
  packages/nc-mail-templates/src/templates/assets/LinkedIcon.ts
  packages/nc-mail-templates/src/templates/assets/TwitterIcon.ts
  packages/nc-mail-templates/src/templates/assets/YoutubeIcon.ts
  packages/nc-mail-templates/src/templates/components/Footer.ts
  packages/nc-mail-templates/src/templates/components/Header.ts
  packages/nc-mail-templates/src/templates/components/HtmlWrapper.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9255 feat: improve queue logic
  packages/nocodb/src/interface/Jobs.ts
  packages/nocodb/src/meta/meta.service.ts
  packages/nocodb/src/modules/jobs/fallback/fallback-queue.service.ts
  packages/nocodb/src/modules/jobs/fallback/jobs.service.ts
  packages/nocodb/src/modules/jobs/jobs-event.service.ts
  packages/nocodb/src/modules/jobs/jobs-map.service.ts
  packages/nocodb/src/modules/jobs/jobs-service.interface.ts
  packages/nocodb/src/modules/jobs/jobs.controller.ts
  packages/nocodb/src/modules/jobs/jobs.module.ts
  packages/nocodb/src/modules/jobs/jobs.processor.ts
  packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
  packages/nocodb/src/modules/jobs/jobs/attachment-clean-up/attachment-clean-up.ts
  packages/nocodb/src/modules/jobs/jobs/data-export/data-export.processor.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts
  packages/nocodb/src/modules/jobs/jobs/meta-sync/meta-sync.processor.ts
  packages/nocodb/src/modules/jobs/jobs/source-create/source-create.processor.ts
  packages/nocodb/src/modules/jobs/jobs/source-delete/source-delete.processor.ts
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
  packages/nocodb/src/modules/jobs/jobs/webhook-handler/webhook-handler.processor.ts
  packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts
  packages/nocodb/src/modules/jobs/migration-jobs/nc_job_002_thumbnail.ts
  packages/nocodb/src/modules/jobs/redis/jobs.service.ts
Labels: 🔦 Type: Feature, size:XL, lgtm

#9268 New Crowdin updates
  packages/nc-gui/lang/zh-Hans.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9254 Nc feat: Prefill links using form builder
  packages/nc-gui/components/nc/List.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/virtual-cell/components/ListItem.vue
  packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
  packages/nc-gui/composables/useSharedFormViewStore.ts
Labels: 🔦 Type: Feature, size:L, lgtm

#9252 Nc feat/api snippets revamp
  packages/nc-gui/assets/nc-icons/lang-c.svg
  packages/nc-gui/assets/nc-icons/lang-java.svg
  packages/nc-gui/assets/nc-icons/lang-js.svg
  packages/nc-gui/assets/nc-icons/lang-nocodb-sdk.svg
  packages/nc-gui/assets/nc-icons/lang-node.svg
  packages/nc-gui/assets/nc-icons/lang-php.svg
  packages/nc-gui/assets/nc-icons/lang-python.svg
  packages/nc-gui/assets/nc-icons/lang-ruby.svg
  packages/nc-gui/assets/nc-icons/lang-shell.svg
  packages/nc-gui/components/smartsheet/Details.vue
  packages/nc-gui/components/smartsheet/details/Api.vue
  packages/nc-gui/lang/en.json
  packages/nc-gui/utils/iconUtils.ts
Labels: 🔦 Type: Feature, ☎ Scope : API, size:L, lgtm

#9273 fix: Button url open not working in gallery and kanban
  packages/nc-gui/components/smartsheet/Gallery.vue
  packages/nc-gui/components/smartsheet/Kanban.vue
Labels: 🐛 Type: Bug, 👓 Scope : View, size:XS, lgtm

#9274 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9256 feat: field, table and view descriptions
  packages/nc-gui/assets/nc-icons/align-left.svg
  packages/nc-gui/assets/nc-icons/calendar.svg
  packages/nc-gui/assets/nc-icons/form.svg
  packages/nc-gui/assets/nc-icons/gallery.svg
  packages/nc-gui/assets/nc-icons/grid.svg
  packages/nc-gui/assets/nc-icons/kanban.svg
  packages/nc-gui/components/dashboard/TreeView/TableNode.vue
  packages/nc-gui/components/dashboard/TreeView/ViewsNode.vue
  packages/nc-gui/components/dashboard/TreeView/index.vue
  packages/nc-gui/components/dlg/TableCreate.vue
  packages/nc-gui/components/dlg/TableDescriptionUpdate.vue
  packages/nc-gui/components/dlg/ViewCreate.vue
  packages/nc-gui/components/dlg/ViewDescriptionUpdate.vue
  packages/nc-gui/components/nc/Button.vue
  packages/nc-gui/components/nc/Tooltip.vue
  packages/nc-gui/components/smartsheet/column/DefaultValue.vue
  packages/nc-gui/components/smartsheet/column/EditOrAdd.vue
  packages/nc-gui/components/smartsheet/column/EditOrAddProvider.vue
  packages/nc-gui/components/smartsheet/column/RichLongTextDefaultValue.vue
  packages/nc-gui/components/smartsheet/header/Cell.vue
  packages/nc-gui/components/smartsheet/header/Menu.vue
  packages/nc-gui/components/smartsheet/header/VirtualCell.vue
  packages/nc-gui/components/smartsheet/toolbar/OpenedViewAction.vue
  packages/nc-gui/components/smartsheet/toolbar/ViewActionMenu.vue
  packages/nc-gui/composables/useColumnCreateStore.ts
  packages/nc-gui/composables/useTableNew.ts
  packages/nc-gui/composables/useViewAggregate.ts
  packages/nc-gui/context/index.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/layouts/shared-view.vue
  packages/nc-gui/lib/acl.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
  packages/nocodb/src/meta/migrations/v2/nc_060_descriptions.ts
  packages/nocodb/src/models/Column.ts
  packages/nocodb/src/models/Model.ts
  packages/nocodb/src/models/View.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/columns.service.ts
  packages/nocodb/src/services/tables.service.ts
  packages/nocodb/tests/unit/rest/tests/typeCasts.test.ts
  tests/playwright/tests/db/general/sourceRestrictions.spec.ts
Labels: 🔦 Type: Feature, size:XXL, lgtm

#9284 fix: avoid setting ttl to 0
  packages/nocodb/src/filters/global-exception/global-exception.filter.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9279 Nc Fix: header ui changes
  packages/nc-gui/components/account/AppStore.vue
  packages/nc-gui/components/account/Profile.vue
  packages/nc-gui/components/account/ResetPassword.vue
  packages/nc-gui/components/account/SignupSettings.vue
  packages/nc-gui/components/account/Token.vue
  packages/nc-gui/components/account/UserList.vue
  packages/nc-gui/components/nc/PageHeader.vue
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nc-gui/components/project/View.vue
  packages/nc-gui/components/workspace/AuditLogs.vue
  packages/nc-gui/components/workspace/View.vue
  packages/nc-gui/components/workspace/integrations/view.vue
  packages/nc-gui/pages/account/index.vue
  packages/nc-gui/windi.config.ts
Labels: 👓 Scope : View, size:L, lgtm

#9277 Nc fix/3616 formula related bugs
  packages/nc-gui/components/monaco/formula.ts
  packages/nc-gui/components/smartsheet/column/FormulaInputHelper.vue
  packages/nocodb-sdk/src/lib/formulaHelpers.ts
Labels: size:S, lgtm

#9280 feat: move button trigger to workers
  packages/nocodb/src/services/hooks.service.ts
Labels: 🔦 Type: Feature, size:S, lgtm

#9285 fix: avoid using clashing name for icon
  packages/nc-gui/assets/nc-icons/lang-nc-sdk.svg
  packages/nc-gui/utils/iconUtils.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9286 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9283 Env variable update
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/nocodb/src/helpers/extractLimitAndOffset.ts
Labels: 📋 Scope : Docs, size:M, lgtm

#9287 test: update according to minimum limit
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/tests/unit/rest/tests/newDataApis.test.ts
  tests/playwright/tests/db/features/verticalFillHandle.spec.ts
Labels: Scope : Test [E2E], size:M, lgtm

#9290 fix: base home page table name font as normal
  packages/nc-gui/components/project/AllTables.vue
Labels: 👓 Scope : View, size:XS, lgtm

#9292 fix: wrong logic for throtller counter
  packages/nocodb/src/filters/global-exception/global-exception.filter.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9259 Nc feat/date field current date as def
  packages/nc-gui/components/cell/DatePicker.vue
  packages/nc-gui/components/cell/DateTimePicker.vue
  packages/nc-gui/components/nc/DatePicker.vue
  packages/nc-gui/components/nc/DateWeekSelector.vue
  packages/nc-gui/components/nc/MonthYearSelector.vue
  packages/nc-gui/components/nc/TimeSelector.vue
  packages/nc-gui/components/smartsheet/Cell.vue
  packages/nc-gui/components/smartsheet/column/DefaultValue.vue
  packages/nc-gui/lang/en.json
  packages/nocodb-sdk/src/lib/sqlUi/DatabricksUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/MssqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/MysqlUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/OracleUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/SnowflakeUi.ts
  packages/nocodb-sdk/src/lib/sqlUi/SqliteUi.ts
  tests/playwright/pages/Dashboard/Grid/Column/UserOptionColumn.ts
Labels: 🔦 Type: Feature, size:L, lgtm

#9293 Nc feat/user mgmt followup
  packages/nc-gui/components/cell/User.vue
  packages/nc-gui/components/general/UserIcon.vue
  packages/nc-gui/components/workspace/CollaboratorsList.vue
  packages/nc-gui/store/base.ts
Labels: 👓 Scope : View, size:M, lgtm

#9295 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9294 Nc fix/login redirect bug
  packages/nc-gui/middleware/02.auth.global.ts
  packages/nc-gui/pages/index.vue
  packages/nc-gui/plugins/redirect.ts
Labels: 👮 Scope : Auth, size:M, lgtm

#9225 fix: apply filter on aggregation in shared views and send local aggre…
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
  packages/nc-gui/composables/useViewAggregate.ts
  packages/nc-gui/composables/useViewGroupBy.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
Labels: 🐛 Type: Bug, 🛑 Status: Do Not Merge, size:M, lgtm

#9267 feat: thumbnail generation migration
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
  packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts
  packages/nocodb/src/modules/jobs/migration-jobs/nc_job_002_thumbnail.ts
  packages/nocodb/src/providers/init-meta-service.provider.ts
Labels: size:L, lgtm

#9265 Nc feat/enable sql integration in oss
  packages/nc-gui/components/dashboard/settings/data-sources/CreateBase.vue
  packages/nc-gui/components/dashboard/settings/data-sources/EditBase.vue
  packages/nc-gui/components/general/IntegrationIcon.vue
  packages/nc-gui/components/smartsheet/details/Api.vue
  packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
  packages/nc-gui/components/workspace/integrations/EditOrAdd.vue
  packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
  packages/nc-gui/components/workspace/integrations/forms/EditOrAddDatabase.vue
  packages/nc-gui/composables/useIntegrationsStore.ts
  packages/nc-gui/composables/useViewAggregate.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/store/workspace.ts
  packages/nc-gui/utils/syncDataUtils.ts
  packages/nocodb/src/models/Integration.ts
  packages/nocodb/src/services/integrations.service.ts
Labels: 🌞 Scope : Data source, size:L, lgtm

#9276 Nc Feature: Redirect URL
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/form/field-settings.vue
  packages/nc-gui/composables/useFormViewStore.ts
  packages/nc-gui/composables/useSharedFormViewStore.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/index.vue
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue
  packages/nc-gui/utils/urlUtils.ts
  packages/nc-gui/utils/validation.ts
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/noco-docs/docs/090.views/040.view-types/030.form.md
  packages/noco-docs/static/img/v2/views/form-view/form-redirect-url.png
Labels: size:L, lgtm

#9301 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/en.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9297 docs: add Notifications documentation
  packages/noco-docs/docs/120.collaboration/050.notifications.md
  packages/noco-docs/docs/120.collaboration/060.oss-specific-details.md
  packages/noco-docs/static/img/v2/notifications/notifications.png
Labels: 📋 Scope : Docs, size:M, lgtm

#9300 Nc feat/form builder
  packages/nc-gui/components/nc/form-builder/SampleModal.vue
  packages/nc-gui/components/nc/form-builder/index.vue
  packages/nc-gui/composables/useFormBuilder/index.ts
  packages/nc-gui/lib/formBuilder.ts
Labels: 🔦 Type: Feature, size:XL, lgtm

#9302 Fix: aggregation filter sync
  packages/nc-gui/composables/useViewAggregate.ts
  packages/nc-gui/composables/useViewGroupBy.ts
Labels: 🐛 Type: Bug, 👓 Scope : View, size:S, lgtm

#9306 Nc Fix: Update extension UI as per new design
  packages/nc-gui/assets/nc-icons/puzzle-outline.svg
  packages/nc-gui/assets/nc-icons/puzzle-solid.svg
  packages/nc-gui/components/dashboard/Sidebar/TopSection.vue
  packages/nc-gui/components/extensions/Details.vue
  packages/nc-gui/components/extensions/Extension.vue
  packages/nc-gui/components/extensions/ExtensionMenu.vue
  packages/nc-gui/components/extensions/Market.vue
  packages/nc-gui/components/extensions/Pane.vue
  packages/nc-gui/components/project/View.vue
  packages/nc-gui/components/smartsheet/Kanban.vue
  packages/nc-gui/components/smartsheet/Topbar.vue
  packages/nc-gui/components/smartsheet/toolbar/SearchData.vue
  packages/nc-gui/components/smartsheet/topbar/CmdK.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/components/workspace/View.vue
  packages/nc-gui/components/workspace/integrations/ConnectionsTab.vue
  packages/nc-gui/components/workspace/integrations/view.vue
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/extensions/data-exporter/assets/fullscreen-modal-screenshot.png
  packages/nc-gui/extensions/data-exporter/assets/icon.png
  packages/nc-gui/extensions/data-exporter/assets/icon.svg
  packages/nc-gui/extensions/data-exporter/description.md
  packages/nc-gui/extensions/data-exporter/index.vue
  packages/nc-gui/extensions/data-exporter/manifest.json
  packages/nc-gui/extensions/json-exporter/assets/icon.png
  packages/nc-gui/extensions/json-exporter/description.md
  packages/nc-gui/extensions/json-exporter/manifest.json
  packages/nc-gui/utils/iconUtils.ts
  tests/playwright/pages/Dashboard/Sidebar/index.ts
  tests/playwright/pages/Dashboard/common/LeftSidebar/index.ts
  tests/playwright/pages/Dashboard/common/Topbar/index.ts
Labels: 🐛 Type: Bug, 🔦 Type: Feature, size:XXL, lgtm

#9322 Nc Style: Add new light theme config in windicss config file
  packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
  packages/nc-gui/utils/colorsUtils.ts
  packages/nc-gui/windi.config.ts
Labels: size:L, lgtm

#9320 fix: hide description in expanded-view menu options
  packages/nc-gui/components/smartsheet/header/Menu.vue
Labels: 👓 Scope : View, size:XS, lgtm

#9324 Nc chore/add Light Theme Configuration docs
  packages/nc-gui/utils/colorsUtils.ts
Labels: size:M, lgtm

#9319 fix: Row delete bug
  packages/nocodb/src/db/BaseModelSqlv2.ts
Labels: 🐛 Type: Bug, 🏎 Scope : Row, size:XS, lgtm

#9305 Docs/description
  packages/noco-docs/docs/050.tables/020.create-table.md
  packages/noco-docs/docs/050.tables/060.actions-on-table.md
  packages/noco-docs/docs/070.fields/060.actions-on-field.md
  packages/noco-docs/docs/090.views/090.actions-on-view.md
  packages/noco-docs/static/img/v2/fields/add-field-description.png
  packages/noco-docs/static/img/v2/fields/edit-field-description.png
  packages/noco-docs/static/img/v2/fields/fields-description.png
  packages/noco-docs/static/img/v2/table/table-create-1.png
  packages/noco-docs/static/img/v2/table/table-create-2.png
  packages/noco-docs/static/img/v2/table/table-description-2.png
  packages/noco-docs/static/img/v2/views/add-view-description.png
  packages/noco-docs/static/img/v2/views/edit-view-description.png
  packages/noco-docs/static/img/v2/views/view-description.png
Labels: 📋 Scope : Docs, size:M, lgtm

#9303 Docs/auth tokens cleanup
  packages/noco-docs/docs/140.account-settings/020.api-tokens.md
  packages/noco-docs/docs/990.FAQs.md
  packages/nocodb/src/schema/swagger-v2.json
Labels: 📋 Scope : Docs, size:M, lgtm

#9330 New Crowdin updates
  packages/nc-gui/lang/sv.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9343 fix: load other aggregations even formula Column is error
  packages/nocodb/src/db/aggregation.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9314 Nc fix/3643 setup page
  packages/nc-gui/components/account/Breadcrumb.vue
  packages/nc-gui/components/account/Setup.vue
  packages/nc-gui/components/account/setup/AppIcon.vue
  packages/nc-gui/components/account/setup/Config.vue
  packages/nc-gui/components/account/setup/List.vue
  packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
  packages/nc-gui/components/dashboard/settings/AppStore.vue
  packages/nc-gui/components/nc/Modal.vue
  packages/nc-gui/components/nc/form-builder/index.vue
  packages/nc-gui/components/smartsheet/details/Api.vue
  packages/nc-gui/composables/useAccountSetupStore.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/lib/formBuilder.ts
  packages/nc-gui/pages/account/index.vue
  packages/nc-gui/pages/account/index/[page].vue
  packages/nc-gui/pages/account/index/setup/[[nestedPage]].vue
  packages/nc-gui/pages/account/index/setup/[[nestedPage]]/[[app]].vue
  packages/nc-gui/public/plugins/aws.png
  packages/nc-gui/public/plugins/scaleway.png
  packages/nc-gui/utils/colorsUtils.ts
  packages/nocodb/src/plugins/backblaze/index.ts
  packages/nocodb/src/plugins/gcs/index.ts
  packages/nocodb/src/plugins/linode/index.ts
  packages/nocodb/src/plugins/mailerSend/index.ts
  packages/nocodb/src/plugins/mino/index.ts
  packages/nocodb/src/plugins/ovhCloud/index.ts
  packages/nocodb/src/plugins/r2/index.ts
  packages/nocodb/src/plugins/s3/index.ts
  packages/nocodb/src/plugins/scaleway/index.ts
  packages/nocodb/src/plugins/ses/index.ts
  packages/nocodb/src/plugins/smtp/index.ts
  packages/nocodb/src/plugins/spaces/index.ts
  packages/nocodb/src/plugins/upcloud/index.ts
  packages/nocodb/src/plugins/vultr/index.ts
  packages/nocodb/src/services/utils.service.ts
  packages/nocodb/src/types/nc-plugin/common/XcUIBuilder.ts
  tests/playwright/pages/Account/Setup.ts
  tests/playwright/pages/Account/SetupConfig.ts
  tests/playwright/pages/Account/SetupList.ts
  tests/playwright/pages/Account/index.ts
  tests/playwright/setup/index.ts
  tests/playwright/tests/db/usersAccounts/accounSetup.spec.ts
Labels: size:XXL, lgtm

#9328 fix: handle attachment issues for windows
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/models/PresignedUrl.ts
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
  packages/nocodb/src/plugins/mino/Minio.ts
  packages/nocodb/src/plugins/storage/Local.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9353 fix: remove deprecated apis from swagger
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
Labels: 🐛 Type: Bug, size:L, lgtm

#9349 fix(nc-gui): hide formula field in new record expanded form
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#9355 Nc fix(nc-gui): add more integrations in ticketing category
  packages/nc-gui/assets/nc-icons/freshdesk.svg
  packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
  packages/nc-gui/lang/en.json
  packages/nc-gui/utils/iconUtils.ts
  packages/nc-gui/utils/syncDataUtils.ts
  packages/nocodb-sdk/src/lib/enums.ts
Labels: size:M, lgtm

#9354 Nc fix/UI misc changes
  packages/nc-gui/assets/nc-icons/cell-duration.svg
  packages/nc-gui/assets/nc-icons/cell-select.svg
  packages/nc-gui/assets/nc-icons/cell-year.svg
  packages/nc-gui/components/smartsheet/details/Fields.vue
  packages/nc-gui/components/smartsheet/header/Cell.vue
  packages/nc-gui/components/smartsheet/header/CellIcon.ts
  packages/nc-gui/components/smartsheet/header/Menu.vue
  packages/nc-gui/lang/en.json
  packages/nc-gui/utils/columnUtils.ts
  packages/nc-gui/utils/iconUtils.ts
  tests/playwright/pages/Dashboard/Details/FieldsPage.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9352 fix(nc-gui): append reload_attempt query param after hash url
  packages/nc-gui/plugins/error-handler.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9348 Nc fix: Miscellaneous bugs
  packages/nc-gui/components/dlg/SharedBaseDuplicate.vue
  packages/nc-gui/lang/en.json
  packages/nc-gui/store/bases.ts
  packages/nocodb-sdk/src/lib/globals.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/helpers/catchError.ts
  packages/nocodb/src/middlewares/extract-ids/extract-ids.middleware.ts
  packages/nocodb/src/utils/acl.ts
Labels: 🛑 Status: Do Not Merge, size:L, lgtm

#9363 Nc misc fixes
  packages/nc-gui/components/dlg/ViewCreate.vue
  packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
  packages/nc-gui/components/smartsheet/calendar/MonthView.vue
  packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
  packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue
  packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
  packages/nc-gui/composables/useCalendarViewStore.ts
  packages/nc-gui/lang/en.json
  packages/nocodb/src/helpers/catchError.ts
Labels: 🐛 Type: Bug, 👓 Scope : View, size:L, lgtm

#9299 fix: load table even if formula error is present
  packages/nc-gui/composables/useViewData.ts
  packages/nc-gui/store/tables.ts
  packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
  packages/nocodb/src/helpers/catchError.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9368 Nc fix: Allow base invite for all user roles
  packages/nocodb/src/utils/acl.ts
Labels: size:XS, lgtm

#9329 Fix/redis password enc
  docker-compose/setup-script/noco.sh
  packages/nc-gui/components/smartsheet/header/Cell.vue
  packages/nc-gui/components/smartsheet/header/Menu.vue
Labels: 🐛 Type: Bug, size:S, lgtm

#9379 fix: Test connection related bugs
  packages/nc-gui/components/workspace/integrations/forms/EditOrAddDatabase.vue
  packages/nocodb-sdk/src/lib/connectionConfigUtils.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9380 fix: password encoding
  docker-compose/setup-script/noco.sh
Labels: 🐛 Type: Bug, size:XS, lgtm

#9377 Nc fix(nc-gui): rename light theme colors shortcuts
  packages/nc-gui/utils/colorsUtils.ts
  packages/nc-gui/windi.config.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9390 docs: improve french doc
  markdown/readme/languages/french.md
Labels: 📋 Scope : Docs, size:S, lgtm

#9388 chore: update KnexClient.ts
  packages/nocodb/src/db/sql-client/lib/KnexClient.ts
Labels: size:XS, lgtm

#9395 fix: add some docs to calendar code
  packages/nc-gui/components/smartsheet/calendar/index.vue
Labels: 📋 Scope : Docs, size:S, lgtm

#9370 Docs/fixes portuguese typos
  markdown/readme/languages/portuguese.md
Labels: 📋 Scope : Docs, size:M, lgtm

#9396 fix: add additional docs to calendar code
  packages/nc-gui/composables/useCalendarViewStore.ts
Labels: size:S, lgtm

#7925 Add one click deploy on sealos
  packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation.md
Labels: lgtm

#7587 Full install
  docker-compose/aio/.env
  docker-compose/aio/.gitignore
  docker-compose/aio/README.md
  docker-compose/aio/advanced.md
  docker-compose/aio/bin/gen_letsencrypt_cert.sh
  docker-compose/aio/bin/nginx_reload.sh
  docker-compose/aio/bin/nginx_start.sh
  docker-compose/aio/bin/renew_certs.sh
  docker-compose/aio/bin/restart.sh
  docker-compose/aio/bin/start.sh
  docker-compose/aio/conf/nc_properties.env
  docker-compose/aio/docker-compose.yml
  docker-compose/aio/install.sh
  docker-compose/aio/nginx/conf-templates/certbot_conf.template
  docker-compose/aio/nginx/conf-templates/ssl_server_name_conf.template
  docker-compose/aio/nginx/conf.d/backends.conf
  docker-compose/aio/nginx/conf.d/default.conf
  docker-compose/aio/nginx/conf.d/fe_artf.conf
  docker-compose/aio/nginx/conf/nginx.conf
  docker-compose/aio/pre-req-check.sh
  docker-compose/aio/prepare_env.sh
  docker-compose/aio/sbin/install_vars.sh
  docker-compose/aio/sbin/ubuntu-setup.sh
  docker-compose/aio/sbin/util.sh
Labels: lgtm

#9359 Update 030.rollup.md
  packages/noco-docs/docs/070.fields/040.field-types/040.links-based/030.rollup.md
Labels: 📋 Scope : Docs, size:XS, lgtm
