Repository nocodb/nocodb, pull requests merged in 2024-09, with the labels that each got.

#9366 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9411 Nc chore/docs link corrections
  .github/workflows/validate-docs-links.yml
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/noco-docs/docs/030.workspaces/010.workspace-overview.md
  packages/noco-docs/docs/040.bases/010.base-overview.md
  packages/noco-docs/docs/060.table-operations/010.overview.md
  packages/noco-docs/docs/080.records/010.records-overview.md
  packages/noco-docs/docs/090.views/010.views-overview.md
  packages/noco-docs/docs/090.views/040.view-types/010.grid.md
  packages/noco-docs/docs/090.views/040.view-types/020.gallery.md
  packages/noco-docs/docs/090.views/040.view-types/030.form.md
  packages/noco-docs/docs/090.views/040.view-types/040.kanban.md
  packages/noco-docs/docs/090.views/040.view-types/050.calendar.md
  packages/noco-docs/docs/100.data-sources/010.data-source-overview.md
  packages/noco-docs/docs/120.collaboration/010.collaboration-overview.md
  packages/noco-docs/docs/130.automation/020.webhook/010.webhook-overview.md
  packages/noco-docs/docs/140.account-settings/030.authentication/010.overview.md
  packages/noco-docs/docs/160.developer-resources/010.rest-APIs/010.accessing-apis.md
  packages/noco-docs/docs/160.developer-resources/020.webhook/010.webhook-overview.md
  packages/noco-docs/package-lock.json
  packages/noco-docs/package.json
Labels: 📋 Scope : Docs, size:L, lgtm

#9413 chore: Missing dependency in GUI
  packages/nocodb/package.json
  pnpm-lock.yaml
Labels: 🤖 Bot: Dependencies, size:XS, lgtm

#9351 Nc revamp/csv import extension
  packages/nc-gui/assets/nc-icons/file-big.svg
  packages/nc-gui/assets/nc-icons/info-solid.svg
  packages/nc-gui/assets/nc-icons/placeholder-icon.svg
  packages/nc-gui/assets/nc-icons/script.svg
  packages/nc-gui/assets/nc-icons/spanner.svg
  packages/nc-gui/components/extensions/Details.vue
  packages/nc-gui/components/extensions/Extension.vue
  packages/nc-gui/components/extensions/Extension/Header.vue
  packages/nc-gui/components/extensions/Extension/HeaderMenu.vue
  packages/nc-gui/components/extensions/Extension/Wrapper.vue
  packages/nc-gui/components/extensions/Market.vue
  packages/nc-gui/components/extensions/Pane.vue
  packages/nc-gui/components/nc/Modal.vue
  packages/nc-gui/components/smartsheet/Topbar.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/components/workspace/integrations/IntegrationsTab.vue
  packages/nc-gui/composables/useExtensionHelper.ts
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/extensions/data-exporter/assets/fullscreen-modal-screenshot.png
  packages/nc-gui/extensions/data-exporter/assets/icon.png
  packages/nc-gui/extensions/data-exporter/assets/publisher-icon.svg
  packages/nc-gui/extensions/data-exporter/assets/recent-exports-modal.png
  packages/nc-gui/extensions/data-exporter/assets/recent-exports.png
  packages/nc-gui/extensions/data-exporter/description.md
  packages/nc-gui/extensions/data-exporter/index.vue
  packages/nc-gui/extensions/data-exporter/manifest.json
  packages/nc-gui/extensions/json-exporter/assets/publisher-icon.svg
  packages/nc-gui/extensions/json-exporter/description.md
  packages/nc-gui/extensions/json-exporter/index.vue
  packages/nc-gui/extensions/json-exporter/manifest.json
  packages/nc-gui/lang/en.json
  packages/nc-gui/store/bases.ts
  packages/nc-gui/utils/commonUtils.ts
  packages/nc-gui/utils/iconUtils.ts
  packages/nc-gui/windi.config.ts
Labels: 🐛 Type: Bug, size:XXL, lgtm

#9419 Nc fix: showing wrong date joined time from now in project members tab & for editor and below role it showing current date as date joined
  packages/nc-gui/utils/datetimeUtils.ts
  packages/nocodb/src/models/BaseUser.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9421 fix: form submission email attachments
  packages/nocodb/src/helpers/webhookHelpers.ts
  packages/nocodb/src/utils/common/formSubmissionEmailTemplate.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9420 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/en.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9412 fix: Clear store values only after redirecting to SignIn page
  packages/nc-gui/components/account/ResetPassword.vue
  packages/nc-gui/components/account/Setup.vue
  packages/nc-gui/components/dashboard/Sidebar/UserInfo.vue
  packages/nc-gui/components/general/MiniSidebar.vue
  packages/nc-gui/composables/useApi/interceptors.ts
  packages/nc-gui/composables/useGlobal/actions.ts
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/layouts/base.vue
  packages/nc-gui/layouts/new.vue
  packages/nc-gui/middleware/02.auth.global.ts
  packages/nc-gui/pages/account/index.vue
Labels: 🐛 Type: Bug, 👮 Scope : Auth, size:M, lgtm

#9422 fix: user fields filters not working in webhook
  packages/nocodb/src/helpers/webhookHelpers.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9415 fix: Refresh-token based token generation issues
  packages/nc-gui/components/dlg/TableDescriptionUpdate.vue
  packages/nc-gui/composables/useApi/interceptors.ts
  packages/nc-gui/composables/useGlobal/actions.ts
  packages/nc-gui/composables/useGlobal/index.ts
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/store/notification.ts
  packages/nc-gui/utils/ncUtils.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9428 fix: Missing id param in i18n language file
  packages/nc-gui/components/smartsheet/details/Fields.vue
  packages/nc-gui/components/smartsheet/header/Menu.vue
  packages/nc-gui/composables/useApi/interceptors.ts
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/en.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9430 fix: update auto-upstall url
  packages/noco-docs/docs/020.getting-started/020.quick-start.md
  packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation/010.auto-upstall.md
  packages/noco-docs/docs/020.getting-started/050.self-hosted/030.upgrading.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9432 update : refactor auto-upstall and installation methods
  README.md
  packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation/010.auto-upstall.md
Labels: 🧱 Type: Refactoring, size:XS, lgtm

#9425 feat: add today shortcut for Date related fields
  packages/nc-gui/components/cell/DatePicker.vue
  packages/nc-gui/components/cell/DateTimePicker.vue
  packages/nc-gui/components/cell/TimePicker.vue
  packages/nc-gui/components/cell/YearPicker.vue
  packages/noco-docs/docs/020.getting-started/040.keyboard-shortcuts.md
Labels: 🔦 Type: Feature, size:L, lgtm

#9426 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:XL, lgtm

#9435 fix: default options overriding ssl config
  docker-compose/1_Auto_Upstall/noco.sh
Labels: 🐛 Type: Bug, size:XS, lgtm

#9441 fix: Handle date object as value and avoid treating it as nested condition
  packages/nocodb/src/db/CustomKnex.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9448 Auto upstall docs
  packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation/010.auto-upstall.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9447 Nc fix/miscellaneous
  packages/nc-gui/components/cell/Json.vue
  packages/nc-gui/composables/useApi/interceptors.ts
  packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaPg.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9443 New Crowdin updates
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/fr.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9456 refactor: nocoExecute
  packages/nocodb/src/controllers/old-datas/old-datas.service.ts
  packages/nocodb/src/controllers/public-datas-export.controller.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/helpers/dataHelpers.ts
  packages/nocodb/src/services/data-table.service.ts
  packages/nocodb/src/services/datas.service.ts
  packages/nocodb/src/services/public-datas.service.ts
  packages/nocodb/src/utils/index.ts
  packages/nocodb/src/utils/nocoExecute.ts
Labels: 🧱 Type: Refactoring, size:L, lgtm

#9455 feat: integrations follow-up migration
  packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
  packages/nocodb/src/meta/migrations/v2/nc_061_integration_is_default.ts
  packages/nocodb/src/meta/migrations/v2/nc_062_integration_store.ts
  packages/nocodb/src/utils/globals.ts
Labels: 🔦 Type: Feature, size:M, lgtm

#9459 refactor: Event related modules
  packages/nocodb/src/Noco.ts
  packages/nocodb/src/db/CustomKnex.ts
  packages/nocodb/src/db/aggregation.ts
  packages/nocodb/src/db/sql-client/lib/KnexClient.ts
  packages/nocodb/src/db/sql-mgr/SqlMgr.ts
  packages/nocodb/src/gateways/socket.gateway.ts
  packages/nocodb/src/helpers/apiMetrics.ts
  packages/nocodb/src/helpers/initAdminFromEnv.ts
  packages/nocodb/src/providers/init-meta-service.provider.ts
  packages/nocodb/src/services/app-hooks-listener.service.ts
  packages/nocodb/src/services/telemetry.service.ts
  packages/nocodb/src/services/users/users.service.ts
  packages/nocodb/src/utils/TeleBatchProcessor.ts
  packages/nocodb/src/utils/feedbackForm.ts
  packages/nocodb/src/utils/index.ts
  packages/nocodb/src/utils/tele.ts
  packages/nocodb/src/version-upgrader/NcUpgrader.ts
Labels: 🧱 Type: Refactoring, size:L, lgtm

#9457 fix: aggregation queries
  packages/nocodb/src/db/aggregations/mysql2.ts
  packages/nocodb/src/db/aggregations/pg.ts
  packages/nocodb/src/db/aggregations/sqlite3.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9452 fix: Proper column meta null value handling
  packages/nc-gui/components/smartsheet/PlainCell.vue
Labels: 🐛 Type: Bug, 🍰 Scope : Column, size:XS, lgtm

#9458 refactor: Pagination limit min value restriction
  packages/nocodb/src/helpers/extractLimitAndOffset.ts
Labels: 🧱 Type: Refactoring, size:XS, lgtm

#9464 fix(nc-gui): show decimal cell value with trailing zeros
  packages/nocodb-sdk/src/lib/helperFunctions.ts
Labels: 🐛 Type: Bug, 🛑 Status: Do Not Merge, size:XS, lgtm

#9462 fix: aggregation not working in mariadb
  packages/nocodb/src/db/BaseModelSqlv2.ts
Labels: 🐛 Type: Bug, 🦭 DB : MariaDB, size:S, lgtm

#9468 Nc docs/v2 meta api reorg
  packages/nocodb/src/schema/swagger-v2.json
Labels: 📋 Scope : Docs, size:XL, lgtm

#9466 New Crowdin updates
  packages/nc-gui/lang/ru.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9469 fix: handle missing col options for button
  packages/nc-gui/components/smartsheet/column/ButtonOptions.vue
  packages/nocodb/src/models/Column.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9453 fix: Post update extract new id since composite key can be changed in update
  packages/nocodb/src/db/BaseModelSqlv2.ts
Labels: 🐛 Type: Bug, 🛑 Status: Do Not Merge, size:M, lgtm

#9467 fix: add default value for rollup
  packages/nocodb/src/db/genRollupSelectv2.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9475 fix: swagger UI blank page
  packages/nc-gui/plugins/redirect.ts
  packages/nocodb/src/controllers/api-docs/api-docs.controller.ts
  packages/nocodb/src/controllers/api-docs/template/redocHtml.ts
  packages/nocodb/src/controllers/api-docs/template/swaggerHtml.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9454 Nc feat/missing api v2
  packages/nocodb/src/controllers/users/users.controller.ts
  packages/nocodb/src/modules/auth/auth.controller.ts
  packages/nocodb/src/schema/swagger-v2.json
Labels: ☎ Scope : API, size:XXL, lgtm

#9477 Nc fix/email template
  packages/nc-mail-templates/src/templates/Mention.vue
  packages/nocodb/src/modules/auth/ui/auth/emailVerify.ts
  packages/nocodb/src/modules/auth/ui/auth/resetPassword.ts
  packages/nocodb/src/modules/auth/ui/emailTemplates/forgotPassword.ts
  packages/nocodb/src/modules/auth/ui/emailTemplates/invite.ts
  packages/nocodb/src/modules/auth/ui/emailTemplates/verify.ts
  packages/nocodb/src/services/base-users/ui/auth/emailVerify.ts
  packages/nocodb/src/services/base-users/ui/auth/resetPassword.ts
  packages/nocodb/src/services/base-users/ui/emailTemplates/forgotPassword.ts
  packages/nocodb/src/services/base-users/ui/emailTemplates/invite.ts
  packages/nocodb/src/services/base-users/ui/emailTemplates/verify.ts
  packages/nocodb/src/utils/common/formSubmissionEmailTemplate.ts
Labels: 👮 Scope : Auth, size:L, lgtm

#9476 docs: meta api v2 label and order
  packages/nocodb/src/schema/swagger-v2.json
Labels: 📋 Scope : Docs, size:XL, lgtm

#9486 refactor: Sanitise method
  packages/nocodb/src/db/BaseModelSqlv2.ts
Labels: 🧱 Type: Refactoring, size:S, lgtm

#9485 docs: meta apis for base
  packages/nocodb/src/schema/swagger-v2.json
Labels: 📋 Scope : Docs, size:L, lgtm

#9487 fix: Disable form view creation only for data readonly source
  packages/nc-gui/components/dashboard/TreeView/CreateViewBtn.vue
Labels: size:XS, lgtm

#9463 feat: Implement scanFiles for gcs and Minio
  packages/nocodb/src/plugins/gcs/Gcs.ts
  packages/nocodb/src/plugins/mino/Minio.ts
Labels: 🔦 Type: Feature, size:L, lgtm

#9460 docs: embed Tutorial Videos in documentation
  packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation/010.auto-upstall.md
  packages/noco-docs/docs/060.table-operations/010.overview.md
  packages/noco-docs/docs/070.fields/030.display-value.md
  packages/noco-docs/docs/070.fields/040.field-types/050.custom-types/020.button.md
  packages/noco-docs/docs/070.fields/055.field-summary-footer.md
  packages/noco-docs/docs/080.records/030.expand-record.md
  packages/noco-docs/docs/090.views/010.views-overview.md
  packages/noco-docs/docs/090.views/040.view-types/030.form.md
  packages/noco-docs/docs/120.collaboration/050.notifications.md
  packages/noco-docs/static/img/v2/engineering/service-mgmt-menu.png
Labels: 📋 Scope : Docs, size:M, lgtm

#9500 fix: Apply view based filter if linkColumnId present in list api
  packages/nocodb/src/controllers/old-datas/old-datas.service.ts
  packages/nocodb/src/controllers/public-datas-export.controller.ts
  packages/nocodb/src/helpers/dataHelpers.ts
  packages/nocodb/src/modules/auth/auth.controller.ts
  packages/nocodb/src/services/data-table.service.ts
  packages/nocodb/src/services/datas.service.ts
  packages/nocodb/src/services/public-datas.service.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9433 Nc feat: form view conditional fields
  packages/nc-gui/components/cell/Currency.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/form/field-config-error.vue
  packages/nc-gui/components/smartsheet/form/field-settings.vue
  packages/nc-gui/components/smartsheet/form/field-settings/visibility.vue
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilter.vue
  packages/nc-gui/components/smartsheet/toolbar/FilterInput.vue
  packages/nc-gui/composables/useApi/interceptors.ts
  packages/nc-gui/composables/useFormViewStore.ts
  packages/nc-gui/composables/useSharedFormViewStore.ts
  packages/nc-gui/composables/useSmartsheetStore.ts
  packages/nc-gui/composables/useViewData.ts
  packages/nc-gui/composables/useViewFilters.ts
  packages/nc-gui/context/index.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/lib/form.ts
  packages/nc-gui/utils/dataUtils.ts
  packages/nc-gui/utils/is.ts
  packages/noco-docs/docs/090.views/040.view-types/030.form.md
  packages/noco-docs/static/img/v2/views/form-view/show-on-conditions.png
  packages/nocodb/src/controllers/filters.controller.ts
  packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
  packages/nocodb/src/meta/migrations/v2/nc_063_form_field_filter.ts
  packages/nocodb/src/models/Column.ts
  packages/nocodb/src/models/Filter.ts
  packages/nocodb/src/models/HookFilter.ts
  packages/nocodb/src/models/View.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/filters.service.ts
  tests/playwright/pages/Dashboard/Form/formConditionalFields.ts
  tests/playwright/pages/Dashboard/Form/index.ts
  tests/playwright/pages/Dashboard/common/Toolbar/Filter.ts
  tests/playwright/pages/SharedForm/index.ts
  tests/playwright/tests/db/views/viewForm.spec.ts
Labels: 🔦 Type: Feature, 🛑 Status: Do Not Merge, size:XXL, lgtm

#9502 docs: meta v2 fields description
  packages/nocodb/src/schema/swagger-v2.json
Labels: 📋 Scope : Docs, size:XXL, lgtm

#9493 fix: barcode on formula
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/models/Column.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9506 fix: Query cache on source update
  packages/nocodb/src/controllers/sources.controller.ts
  packages/nocodb/src/models/Source.ts
  packages/nocodb/src/services/sources.service.ts
Labels: 🐛 Type: Bug, 🌞 Scope : Data source, size:M, lgtm

#9494 fix: handle type diff while comparing pks
  packages/nocodb/src/db/BaseModelSqlv2.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9508 docs: view & webhook APIs
  packages/nocodb/src/schema/swagger-v2.json
Labels: 📋 Scope : Docs, size:L, lgtm

#9509 feat: restrict concurrent operations
  packages/nocodb/src/helpers/populateMeta.ts
  packages/nocodb/src/utils/NcHelp.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9522 feat: single query command palette & dedicated cache
  packages/nc-gui/app.vue
  packages/nc-gui/components/cmd-k/index.vue
  packages/nc-gui/components/general/Loader.vue
  packages/nc-gui/composables/useCommandPalette/index.ts
  packages/nocodb/src/helpers/commandPaletteHelpers.ts
  packages/nocodb/src/models/Base.ts
  packages/nocodb/src/models/BaseUser.ts
  packages/nocodb/src/models/Model.ts
  packages/nocodb/src/models/View.ts
  packages/nocodb/src/services/command-palette.service.ts
  packages/nocodb/src/utils/globals.ts
Labels: 🔦 Type: Feature, size:L, lgtm

#9519 Fix $(pwd) invocation in readme example
  README.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9517 fix: at import stall issue
  packages/nocodb/src/models/Column.ts
  packages/nocodb/src/modules/jobs/jobs.module.ts
  packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
  packages/nocodb/src/modules/jobs/jobs/at-import/helpers/fetchAT.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9535 fix(nc-gui): show mfe save changes field error
  packages/nc-gui/components/smartsheet/details/Fields.vue
Labels: 🐛 Type: Bug, size:M, lgtm

#9542 fix: skip trimming options while applying filter
  packages/nocodb/src/db/conditionV2.ts
Labels: 🐛 Type: Bug, 🐬 DB : MySQL, size:XS, lgtm

#9540 Nc fix/9501 redirection issue
  packages/nc-gui/composables/useGlobal/actions.ts
  packages/nc-gui/plugins/redirect.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9541 Nc fix/dev warnings
  packages/nc-gui/components/dashboard/settings/app-store/AppInstall.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
Labels: 🐛 Type: Bug, size:M, lgtm

#9544 Nc docs/meta apis cleanup 2
  packages/nocodb/src/schema/swagger-v2.json
Labels: 📋 Scope : Docs, size:L, lgtm

#9526 Nc refactor/api token
  packages/nc-gui/components/account/Token.vue
  packages/nc-gui/components/tabs/auth/ApiTokenManagement.vue
  packages/nocodb/src/controllers/api-tokens.controller.ts
  packages/nocodb/src/controllers/org-tokens.controller.ts
  packages/nocodb/src/models/ApiToken.ts
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/api-tokens.service.ts
  packages/nocodb/src/services/app-hooks/interfaces.ts
  packages/nocodb/src/services/org-tokens.service.ts
Labels: 🧱 Type: Refactoring, 👮 Scope : Auth, size:M, lgtm

#9536 fix: compose configuration generation
  docker-compose/1_Auto_Upstall/noco.sh
Labels: 🐛 Type: Bug, size:M, lgtm

#9530 feat: Decide base creation behaviour on app load based on permission
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/nocodb/src/controllers/filters.controller.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts
  packages/nocodb/src/helpers/initBaseBehaviour.ts
  packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
  packages/nocodb/src/meta/migrations/v2/nc_064_pg_minimal_dbs.ts
  packages/nocodb/src/models/Model.ts
  packages/nocodb/src/models/Source.ts
  packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts
  packages/nocodb/src/modules/jobs/jobs/at-import/helpers/fetchAT.ts
  packages/nocodb/src/providers/init-meta-service.provider.ts
  packages/nocodb/src/services/bases.service.ts
  packages/nocodb/src/services/data-alias-nested.service.ts
  packages/nocodb/src/services/data-table.service.ts
  packages/nocodb/src/services/datas.service.ts
  packages/nocodb/src/services/public-datas.service.ts
  packages/nocodb/src/utils/common/NcConnectionMgrv2.ts
Labels: 🔦 Type: Feature, 🛑 Status: Do Not Merge, trigger-CI, size:XL, lgtm

#9543 Nc fix/swagger base pw
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/api-docs/swagger/swagger-base.json
  packages/nocodb/src/services/api-docs/swaggerV2/swagger-base.json
  tests/playwright/setup/demoTable.ts
  tests/playwright/setup/index.ts
  tests/playwright/tests/db/features/swagger.spec.ts
  tests/playwright/tests/db/usersAccounts/accountTokenManagement.spec.ts
Labels: Scope : Test [E2E], size:M, lgtm

#9534 chore[charts/nocodb/values.yaml]: Typo `https:/` -> `https://`.
  charts/nocodb/values.yaml
Labels: size:XS, lgtm

#9557 Nc fix(nc-gui): grid column resize error
  packages/nc-gui/components/smartsheet/grid/Table.vue
Labels: 🐛 Type: Bug, 👓 Scope : View, size:XS, lgtm

#9561 Nc fix(nc-gui): MFE show newly added column in same view and hide it in other views
  packages/nc-gui/components/smartsheet/details/Fields.vue
Labels: 🛑 Status: Do Not Merge, 👓 Scope : View, size:XS, lgtm

#9566 [docs] Fix docker compose setup path
  packages/noco-docs/docs/020.getting-started/050.self-hosted/010.installation/030.docker-compose.md
  packages/nocodb/README.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9555 fix: optimizations to potential blockers
  packages/nocodb/src/Noco.ts
  packages/nocodb/src/controllers/attachments-secure.controller.ts
  packages/nocodb/src/controllers/attachments.controller.ts
  packages/nocodb/src/helpers/attachmentHelpers.ts
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
  packages/nocodb/src/modules/jobs/migration-jobs/nc_job_002_thumbnail.ts
  packages/nocodb/src/services/attachments.service.ts
Labels: 🐛 Type: Bug, 🔭 Type: Optimization, size:M, lgtm
