Repository nocodb/nocodb, pull requests merged in 2024-03, with the labels that each got.

#7799 fix: Remove invalid character from swagger json
  .github/workflows/ci-cd.yml
  packages/nocodb/src/schema/swagger-v2.json
Labels: trigger-CI

#7753 feat(nc-gui): refined ranges support & end Date for Date Field
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/dlg/ViewCreate.vue
  packages/nc-gui/components/nc/DateWeekSelector.vue
  packages/nc-gui/components/nc/MonthYearSelector.vue
  packages/nc-gui/components/smartsheet/calendar/Cell.vue
  packages/nc-gui/components/smartsheet/calendar/DayView/DateField.vue
  packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
  packages/nc-gui/components/smartsheet/calendar/MonthView.vue
  packages/nc-gui/components/smartsheet/calendar/RecordCard.vue
  packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
  packages/nc-gui/components/smartsheet/calendar/SideRecordCard.vue
  packages/nc-gui/components/smartsheet/calendar/VRecordCard.vue
  packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue
  packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
  packages/nc-gui/components/smartsheet/calendar/index.vue
  packages/nc-gui/components/smartsheet/toolbar/CalendarRange.vue
  packages/nc-gui/composables/useCalendarViewStore.ts
  packages/nc-gui/lib/types.ts
  packages/nocodb/src/db/conditionV2.ts
  packages/nocodb/src/services/calendar-datas.service.ts
Labels: ✨ Type: Enhancement

#7820 Nc fix/auto collapse sidebar base table
  packages/nc-gui/components/dashboard/TreeView/TableNode.vue
Labels: 🛑 Status: Do Not Merge

#6831 Add support for `URLENCODE` function
  packages/noco-docs/docs/070.fields/040.field-types/060.formula/030.string-functions.md
  packages/nocodb-sdk/src/lib/formulaHelpers.ts
  packages/nocodb/src/db/functionMappings/commonFns.ts
  tests/playwright/tests/db/columns/columnFormula.spec.ts
Labels: 👀 Status: In Review

#7833 feat: base level share
  packages/nc-gui/components/nc/Modal.vue
  packages/nc-gui/components/project/AccessSettings.vue
  packages/nc-gui/components/project/ShareBaseDlg.vue
  packages/nc-gui/components/project/View.vue
  packages/nc-gui/components/roles/Selector.vue
  packages/nc-gui/components/workspace/InviteSection.vue
  packages/nc-gui/composables/useRoles/index.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/lib/acl.ts
  packages/nocodb-sdk/src/lib/enums.ts
  packages/nocodb/src/middlewares/extract-ids/extract-ids.middleware.ts
  packages/nocodb/src/models/BaseUser.ts
  packages/nocodb/src/schema/swagger.json
Labels: ✨ Type: Enhancement

#7938 Post-release sync
  packages/nc-gui/package.json
  packages/nc-lib-gui/package.json
  packages/nocodb-sdk/package.json
  packages/nocodb/package.json
  pnpm-lock.yaml
Labels: 🛑 Status: Do Not Merge

#7974 Nc Feat: Allow inline edit rich text field in form view
  packages/nc-gui/components/cell/RichText.vue
  packages/nc-gui/components/cell/RichText/LinkOptions.vue
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index.vue
Labels: trigger-CI

#7987 Nc fix: add missing formula docs and link
  packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
  packages/noco-docs/docs/070.fields/040.field-types/060.formula/040.date-functions.md
  packages/noco-docs/docs/070.fields/040.field-types/060.formula/060.generic-functions.md
  packages/nocodb-sdk/src/lib/formulaHelpers.ts
Labels: 🛑 Status: Do Not Merge
