Repository nocodb/nocodb, pull requests merged in 2024-11, with the labels that each got.

#9748 fix:submit button blocking issue in survey form
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index/survey.vue
Labels: 🐛 Type: Bug, size:S, lgtm

#9746 New Crowdin updates
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/sv.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9684 fix: Avoid deleting meta on LTAR description update - WIP
  packages/nocodb/src/models/Column.ts
  packages/nocodb/src/version-upgrader/NcUpgrader.ts
  packages/nocodb/src/version-upgrader/upgraders/0227000_dupColMergeUpgrader.ts
  packages/nocodb/src/version-upgrader/upgraders/0227002_ncBrokenLinkRecovery.ts
Labels: 🐛 Type: Bug, 🏗️ Status: In Resolution, size:L, lgtm

#9755 New Crowdin updates
  packages/nc-gui/lang/ja.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9739 fix: reload row if the attachments are expired
  packages/nc-gui/components/cell/attachment/Carousel.vue
  packages/nc-gui/components/cell/attachment/Preview/Image.vue
  packages/nc-gui/components/cell/attachment/Preview/MiscOffice.vue
  packages/nc-gui/components/cell/attachment/Preview/Pdf.vue
  packages/nc-gui/components/cell/attachment/Preview/Video.vue
  packages/nc-gui/utils/attachmentUtils.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9759 fix: handle blank and notblank for formulas
  packages/nocodb/src/db/conditionV2.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9762 fix: Populate index name to avoid duplicate index names for long table names
  packages/nocodb/src/services/columns.service.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9764 fix: simplify alias generation for groupby
  packages/nc-gui/composables/useViewGroupBy.ts
  packages/nc-gui/utils/aliasUtils.ts
Labels: 🧱 Type: Refactoring, size:L, lgtm

#9770 refactor: Move link recover and duplicate remove upgrader to migration jobs
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/interface/Jobs.ts
  packages/nocodb/src/modules/jobs/jobs.module.ts
  packages/nocodb/src/modules/jobs/migration-jobs/init-migration-jobs.ts
  packages/nocodb/src/modules/jobs/migration-jobs/nc_job_003_recover_links.ts
  packages/nocodb/src/modules/jobs/migration-jobs/nc_job_004_cleanup_duplicate_column.ts
  packages/nocodb/src/services/columns.service.ts
  packages/nocodb/src/version-upgrader/NcUpgrader.ts
  packages/nocodb/src/version-upgrader/upgraders/0227000_dupColMergeUpgrader.ts
  packages/nocodb/src/version-upgrader/upgraders/0227002_ncBrokenLinkRecovery.ts
Labels: 🧱 Type: Refactoring, size:XL, lgtm

#9771 docs: operator list mentioend explicitly
  packages/noco-docs/docs/070.fields/040.field-types/060.formula/050.conditional-expressions.md
Labels: 📋 Scope : Docs, size:XS, lgtm

#9775 fix: Formula - special character in identifier bug
  packages/nc-gui/components/monaco/formula.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9772 Nc fix/misc
  packages/nc-gui/components/extensions/Market.vue
  packages/nc-gui/components/extensions/Market/ExtensionsTab.vue
  packages/nc-gui/components/virtual-cell/Button.vue
  packages/nocodb/src/db/sql-client/lib/pg/PgClient.ts
  packages/nocodb/src/modules/auth/auth.controller.ts
  packages/nocodb/src/modules/auth/ui/auth/emailVerify.ts
  packages/nocodb/src/modules/auth/ui/auth/resetPassword.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.controller.ts
  packages/nocodb/src/schema/swagger.json
Labels: size:L, lgtm

#9779 New Crowdin updates
  packages/nc-gui/lang/ko.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9781 fix: copy rows is broken in infinite scroll
  packages/nc-gui/composables/useMultiSelect/index.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9782 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/km.json
  packages/nc-gui/lang/kn.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/ml.json
  packages/nc-gui/lang/ne.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ro.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:M, lgtm

#9783 New Crowdin updates
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/sv.json
Labels: ✈️ Type: i18n translation, size:S, lgtm

#9766 Nc feat/long-text-mentions
  packages/nc-gui/components.d.ts
  packages/nc-gui/components/cell/RichText.vue
  packages/nc-gui/components/cell/RichText/SelectedBubbleMenu.vue
  packages/nc-gui/components/cell/TextArea.vue
  packages/nc-gui/components/notification/Item.vue
  packages/nc-gui/components/notification/Item/MentionEvent.vue
  packages/nc-gui/components/notification/Item/RowMentionEvent.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/helpers/tiptapExtensions/mention/MentionList.vue
  packages/nc-gui/helpers/tiptapExtensions/mention/index.ts
  packages/nc-gui/helpers/tiptapExtensions/mention/suggestion.ts
  packages/nc-gui/package.json
  packages/nc-mail-templates/src/templates/MentionRow.vue
  packages/nocodb-sdk/src/lib/enums.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/services/app-hooks/app-hooks.service.ts
  packages/nocodb/src/services/app-hooks/interfaces.ts
  pnpm-lock.yaml
Labels: 🔦 Type: Feature, size:XL, lgtm

#9788 feat: row expansion
  packages/nc-gui/components/dlg/ExpandTable.vue
  packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/components/smartsheet/grid/index.vue
  packages/nc-gui/composables/useGridViewData.ts
  packages/nc-gui/composables/useInfiniteData.ts
  packages/nc-gui/composables/useMultiSelect/index.ts
  packages/nc-gui/lang/en.json
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/src/controllers/bulk-data-alias.controller.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/bulk-data-alias.service.ts
  packages/nocodb/src/utils/tsUtils.ts
  tests/playwright/pages/Dashboard/Grid/ExpandTable.ts
  tests/playwright/pages/Dashboard/Grid/index.ts
  tests/playwright/tests/db/features/keyboardShortcuts.spec.ts
Labels: 🔦 Type: Feature, size:XXL, lgtm

#9789 Nc extension url preview
  packages/nc-gui/components/smartsheet/Topbar.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/composables/useExtensionHelper.ts
  packages/nc-gui/composables/useExtensions.ts
  packages/nc-gui/lib/enums.ts
Labels: size:S, lgtm

#9791 fix: remove selection
  packages/nc-gui/composables/useMultiSelect/index.ts
Labels: size:XS, lgtm

#9793 fix(extensions): url-preview: emit event from `<InfiniteTable/>`
  packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
Labels: 🐛 Type: Bug, size:S, lgtm

#9801 fix: update mail template for row mentions
  packages/nc-mail-templates/src/assets/discord.png
  packages/nc-mail-templates/src/assets/github.png
  packages/nc-mail-templates/src/assets/linkedin.png
  packages/nc-mail-templates/src/assets/youtube.png
  packages/nc-mail-templates/src/templates/assets/TwitterIcon.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9800 New Crowdin updates
  packages/nc-gui/lang/nl.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9799 feat: gallery view infinite scroll
  packages/nc-gui/components/cell/attachment/Carousel.vue
  packages/nc-gui/components/smartsheet/Gallery.vue
  packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
  packages/nc-gui/components/smartsheet/grid/Table.vue
  packages/nc-gui/composables/useBetaFeatureToggle.ts
  packages/nc-gui/composables/useGalleryViewData.ts
  packages/nc-gui/composables/useGridViewData.ts
  packages/nc-gui/composables/useInfiniteData.ts
  packages/nc-gui/lib/types.ts
  packages/nocodb/src/controllers/bulk-data-alias.controller.ts
Labels: 🔦 Type: Feature, 👓 Scope : View, size:XXL, lgtm

#9806 New Crowdin updates
  packages/nc-gui/lang/zh-Hans.json
Labels: ✈️ Type: i18n translation, size:XS, lgtm

#9813 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/en.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/km.json
  packages/nc-gui/lang/kn.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/ml.json
  packages/nc-gui/lang/ne.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ro.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9784 refactor: Token generation improvements and corrections
  packages/nc-gui/composables/useApi/interceptors.ts
  packages/nc-gui/composables/useGlobal/actions.ts
  packages/nc-gui/composables/useGlobal/index.ts
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/middleware/02.auth.global.ts
  packages/nc-gui/store/notification.ts
  packages/nc-gui/utils/ncUtils.ts
  packages/nocodb/src/constants/index.ts
  packages/nocodb/src/db/CustomKnex.ts
  packages/nocodb/src/models/UserRefreshToken.ts
  packages/nocodb/src/services/users/helpers.ts
  packages/nocodb/src/services/users/users.service.ts
Labels: 🧱 Type: Refactoring, size:L, lgtm

#9819 fix: Resolve bug in computed tooltip extraction logic
  packages/nc-gui/components/smartsheet/header/VirtualCell.vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#9827 Nc fix/miscellaneous bug fixes
  packages/nc-gui/components/general/Gift.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/smartsheet/column/FormulaOptions.vue
  packages/nc-gui/components/smartsheet/grid/InfiniteTable.vue
  packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
  packages/nc-gui/composables/useApi/interceptors.ts
  packages/nc-gui/composables/useGlobal/types.ts
  packages/nc-gui/utils/dataUtils.ts
  packages/nocodb-sdk/src/lib/Api.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/helpers/populateSamplePayload.ts
  packages/nocodb/src/models/Column.ts
  packages/nocodb/src/services/hooks.service.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9829 Nc fix/misc UI changes
  packages/nc-gui/components/dashboard/settings/DataSources.vue
  packages/nc-gui/components/dashboard/settings/UIAcl.vue
  packages/nc-gui/lang/en.json
Labels: 🐛 Type: Bug, size:S, lgtm

#9835 fix: Default base creation bug
  packages/nocodb/src/services/calendars.service.ts
  packages/nocodb/src/services/forms.service.ts
  packages/nocodb/src/services/galleries.service.ts
  packages/nocodb/src/services/maps.service.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9730 docs/hindi: Add Hindi README docs
  markdown/readme/languages/README.md
  markdown/readme/languages/hindi.md
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9754 chore: update Node.js builder image
  packages/nocodb/Dockerfile
  packages/nocodb/Dockerfile.local
  packages/nocodb/Dockerfile.timely
Labels: size:XS, lgtm

#9838 fix: update installation instructions
  README.md
  markdown/readme/languages/chinese.md
  markdown/readme/languages/dutch.md
  markdown/readme/languages/french.md
  markdown/readme/languages/german.md
  markdown/readme/languages/hindi.md
  markdown/readme/languages/indonesian.md
  markdown/readme/languages/italian.md
  markdown/readme/languages/japanese.md
  markdown/readme/languages/korean.md
  markdown/readme/languages/portuguese.md
  markdown/readme/languages/russian.md
  markdown/readme/languages/spanish.md
  markdown/readme/languages/ukrainian.md
  markdown/readme/languages/vietnamese.md
Labels: 📋 Scope : Docs, size:L, lgtm

#9842 chore: button text changed
  packages/nc-gui/assets/img/giftCard.svg
  packages/nc-gui/components/general/Gift.vue
  packages/nc-gui/components/workspace/integrations/forms/EditOrAddCommon.vue
  packages/nc-gui/components/workspace/integrations/forms/EditOrAddDatabase.vue
Labels: size:L, lgtm

#9852 chore: Add `py3-setuptools` for sqlite3 binary build
  packages/nocodb/Dockerfile
Labels: size:XS, lgtm

#9822 fix(nc-gui): show meaningful error to user if import url is not accessible
  packages/nc-gui/components/dlg/QuickImport.vue
  packages/nc-gui/utils/errorUtils.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9863 docs/faq base-info
  packages/noco-docs/docs/990.FAQs.md
  packages/noco-docs/static/img/content/copy-proj-info.png
Labels: 📋 Scope : Docs, size:S, lgtm

#9843 feat: account delete migration
  packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
  packages/nocodb/src/meta/migrations/v2/nc_068_user_delete.ts
Labels: 🔦 Type: Feature, size:S, lgtm

#9862 New Crowdin updates
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/ko.json
Labels: ✈️ Type: i18n translation, size:XL, lgtm

#9722 feat(nc-gui): workspace icon
  packages/nc-gui/components/cmd-k/index.vue
  packages/nc-gui/components/dlg/InviteDlg.vue
  packages/nc-gui/components/general/EmojiPicker.vue
  packages/nc-gui/components/general/ImageCropper.vue
  packages/nc-gui/components/general/UserIcon.vue
  packages/nc-gui/components/general/WorkspaceIcon.vue
  packages/nc-gui/components/general/WorkspaceIconSelector.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/components/workspace/View.vue
  packages/nc-gui/composables/useCommandPalette/index.ts
  packages/nc-gui/lib/enums.ts
  packages/nc-gui/lib/types.ts
  packages/nc-gui/utils/commonUtils.ts
  packages/nocodb-sdk/src/lib/enums.ts
  packages/nocodb-sdk/src/lib/globals.ts
  packages/nocodb/src/controllers/attachments-secure.controller.ts
  packages/nocodb/src/controllers/attachments.controller.ts
  packages/nocodb/src/helpers/attachmentHelpers.ts
  packages/nocodb/src/helpers/catchError.ts
  packages/nocodb/src/interface/Jobs.ts
  packages/nocodb/src/modules/jobs/jobs/thumbnail-generator/thumbnail-generator.processor.ts
  packages/nocodb/src/plugins/GenericS3/GenericS3.ts
  packages/nocodb/src/plugins/storage/Local.ts
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/attachments.service.ts
  packages/nocodb/src/types/nc-plugin/lib/IStorageAdapterV2.ts
  tests/playwright/pages/Dashboard/WorkspaceSettings/index.ts
Labels: 🔦 Type: Feature, 🛑 Status: Do Not Merge, size:XXL, lgtm

#9831 Nc calendar end date
  packages/nc-gui/components/dlg/ViewCreate.vue
  packages/nc-gui/components/smartsheet/PlainCell.vue
  packages/nc-gui/components/smartsheet/calendar/DateTimeSpanningContainer.vue
  packages/nc-gui/components/smartsheet/calendar/DayView/DateField.vue
  packages/nc-gui/components/smartsheet/calendar/DayView/DateTimeField.vue
  packages/nc-gui/components/smartsheet/calendar/MonthView.vue
  packages/nc-gui/components/smartsheet/calendar/RecordCard.vue
  packages/nc-gui/components/smartsheet/calendar/SideMenu.vue
  packages/nc-gui/components/smartsheet/calendar/SideRecordCard.vue
  packages/nc-gui/components/smartsheet/calendar/VRecordCard.vue
  packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue
  packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
  packages/nc-gui/components/smartsheet/toolbar/Calendar/Mode.vue
  packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue
  packages/nc-gui/composables/useBetaFeatureToggle.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/lib/types.ts
  tests/playwright/pages/Dashboard/Calendar/CalendarMonth.ts
  tests/playwright/tests/db/views/viewCalendar.spec.ts
Labels: 🔦 Type: Feature, size:XXL, lgtm

#9867 fix(nc-gui): form view elements over the attachment/pdf viewer
  packages/nc-gui/components/smartsheet/Form.vue
Labels: 🐛 Type: Bug, 👓 Scope : View, size:XS, lgtm

#9868 New Crowdin updates
  packages/nc-gui/lang/ar.json
  packages/nc-gui/lang/bn_IN.json
  packages/nc-gui/lang/cs.json
  packages/nc-gui/lang/da.json
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/es.json
  packages/nc-gui/lang/eu.json
  packages/nc-gui/lang/fa.json
  packages/nc-gui/lang/fi.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/he.json
  packages/nc-gui/lang/hi.json
  packages/nc-gui/lang/hr.json
  packages/nc-gui/lang/hu.json
  packages/nc-gui/lang/id.json
  packages/nc-gui/lang/it.json
  packages/nc-gui/lang/ja.json
  packages/nc-gui/lang/km.json
  packages/nc-gui/lang/kn.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/lv.json
  packages/nc-gui/lang/ml.json
  packages/nc-gui/lang/ne.json
  packages/nc-gui/lang/nl.json
  packages/nc-gui/lang/no.json
  packages/nc-gui/lang/pl.json
  packages/nc-gui/lang/pt.json
  packages/nc-gui/lang/pt_BR.json
  packages/nc-gui/lang/ro.json
  packages/nc-gui/lang/ru.json
  packages/nc-gui/lang/sk.json
  packages/nc-gui/lang/sl.json
  packages/nc-gui/lang/sv.json
  packages/nc-gui/lang/th.json
  packages/nc-gui/lang/tr.json
  packages/nc-gui/lang/uk.json
  packages/nc-gui/lang/vi.json
  packages/nc-gui/lang/zh-Hans.json
  packages/nc-gui/lang/zh-Hant.json
Labels: ✈️ Type: i18n translation, size:XXL, lgtm

#9872 docs: Nested list and commented lines corrections
  packages/noco-docs/docs/140.account-settings/030.authentication/030.SAML-SSO/040.azure-ad.md
Labels: 📋 Scope : Docs, size:M, lgtm

#9870 New Crowdin updates
  packages/nc-gui/lang/de.json
  packages/nc-gui/lang/fr.json
  packages/nc-gui/lang/ko.json
  packages/nc-gui/lang/zh-Hans.json
Labels: ✈️ Type: i18n translation, size:L, lgtm

#9873 fix: Handle sharedExecution timeout error in interceptor
  packages/nc-gui/composables/useApi/interceptors.ts
  packages/nc-gui/composables/useSharedExecutionFn.ts
Labels: 🐛 Type: Bug, size:M, lgtm

#9877 fix: missing await for jobid generation
  packages/nocodb/src/modules/jobs/fallback/jobs.service.ts
  packages/nocodb/src/modules/jobs/redis/jobs.service.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9885 fix: hide twitter feed
  packages/nc-gui/components/feed/View.vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#9830 Nc feat: add delimiters and encoding option in csv export and import extension
  packages/nc-gui/extensions/data-exporter/index.vue
  packages/nocodb-sdk/src/lib/import-export-data.ts
  packages/nocodb-sdk/src/lib/index.ts
  packages/nocodb/package.json
  packages/nocodb/src/controllers/attachments.controller.ts
  packages/nocodb/src/interface/Jobs.ts
  packages/nocodb/src/models/PresignedUrl.ts
  packages/nocodb/src/modules/jobs/jobs/data-export/data-export.processor.ts
  pnpm-lock.yaml
Labels: 🔦 Type: Feature, size:L, lgtm

#9899 fix: use alias when constructing hm filter query to avoid self-reference issue
  packages/nocodb/src/db/conditionV2.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9889 Nc feat/user delete
  packages/noco-docs/docs/140.account-settings/010.profile-page.md
  packages/noco-docs/static/img/v2/account-settings/account-delete-1.png
  packages/noco-docs/static/img/v2/account-settings/account-delete-2.png
  packages/noco-docs/static/img/v2/account-settings/account-delete-3.png
  packages/nocodb/src/models/ApiToken.ts
  packages/nocodb/src/models/Integration.spec.ts
  packages/nocodb/src/models/Integration.ts
  packages/nocodb/src/models/User.ts
  packages/nocodb/src/services/integrations.service.ts
  packages/nocodb/src/services/sources.service.ts
Labels: size:L, lgtm

#9903 fix: One-to-one excluded list filter bug
  packages/nocodb/src/db/BaseModelSqlv2.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9901 fix: calendar followups
  packages/nc-gui/components/dlg/ViewCreate.vue
  packages/nc-gui/components/smartsheet/PlainCell.vue
  packages/nc-gui/components/smartsheet/calendar/DayView/DateField.vue
  packages/nc-gui/components/smartsheet/calendar/MonthView.vue
  packages/nc-gui/components/smartsheet/calendar/RecordCard.vue
  packages/nc-gui/components/smartsheet/calendar/VRecordCard.vue
  packages/nc-gui/components/smartsheet/calendar/WeekView/DateField.vue
  packages/nc-gui/components/smartsheet/calendar/WeekView/DateTimeField.vue
  packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue
  packages/nc-gui/composables/useBetaFeatureToggle.ts
  packages/nc-gui/composables/useCalendarViewStore.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/lib/types.ts
  packages/noco-docs/docs/090.views/040.view-types/050.calendar.md
  packages/noco-docs/static/img/v2/views/calendar/cal-range-1.png
  packages/noco-docs/static/img/v2/views/calendar/cal-range-2.png
  packages/noco-docs/static/img/v2/views/calendar/cal-range-3.png
  packages/noco-docs/static/img/v2/views/calendar/cal-range-4.png
Labels: 🐛 Type: Bug, size:L, lgtm

#9906 fix: data is missing when select option is added via cell
  packages/nc-gui/components/cell/MultiSelect.vue
  packages/nc-gui/components/cell/SingleSelect.vue
Labels: 🐛 Type: Bug, size:S, lgtm

#9894 fix: Merge duplicate plugin and recover broken plugins
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/composables/useNocoAi.ts
  packages/noco-docs/versioned_docs/version-0.109.7/040.developer-resources/020.rest-apis.md
  packages/nocodb/src/controllers/plugins.controller.ts
  packages/nocodb/src/helpers/NcPluginMgrv2.ts
  packages/nocodb/src/models/Plugin.ts
  packages/nocodb/src/plugins/backblaze/index.ts
  packages/nocodb/src/plugins/discord/index.ts
  packages/nocodb/src/plugins/gcs/index.ts
  packages/nocodb/src/plugins/linode/index.ts
  packages/nocodb/src/plugins/mailerSend/index.ts
  packages/nocodb/src/plugins/mattermost/index.ts
  packages/nocodb/src/plugins/minio/Minio.ts
  packages/nocodb/src/plugins/minio/MinioPlugin.ts
  packages/nocodb/src/plugins/minio/index.ts
  packages/nocodb/src/plugins/ovhCloud/index.ts
  packages/nocodb/src/plugins/r2/index.ts
  packages/nocodb/src/plugins/s3/index.ts
  packages/nocodb/src/plugins/scaleway/index.ts
  packages/nocodb/src/plugins/ses/index.ts
  packages/nocodb/src/plugins/slack/index.ts
  packages/nocodb/src/plugins/smtp/index.ts
  packages/nocodb/src/plugins/spaces/index.ts
  packages/nocodb/src/plugins/teams/index.ts
  packages/nocodb/src/plugins/twilio/index.ts
  packages/nocodb/src/plugins/twilioWhatsapp/index.ts
  packages/nocodb/src/plugins/upcloud/index.ts
  packages/nocodb/src/plugins/vultr/index.ts
  packages/nocodb/src/providers/init-meta-service.provider.ts
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/command-palette.service.ts
  packages/nocodb/src/services/plugins.service.ts
  packages/nocodb/src/types/nc-plugin/lib/XcPluginConfig.ts
  packages/nocodb/src/version-upgrader/NcUpgrader.ts
  packages/nocodb/src/version-upgrader/upgraders/0258003_ncDuplicatePluginMerge.ts
Labels: 🐛 Type: Bug, size:L, lgtm

#9777 chore: update runner image
  packages/nocodb/Dockerfile
  packages/nocodb/Dockerfile.local
  packages/nocodb/Dockerfile.timely
Labels: size:XS, lgtm

#9879 feat: base snapshots
  packages/nc-gui/assets/nc-icons/database.svg
  packages/nc-gui/assets/nc-icons/settings.svg
  packages/nc-gui/assets/nc-icons/users.svg
  packages/nc-gui/components/dashboard/TreeView/ProjectNode.vue
  packages/nc-gui/components/dashboard/settings/Misc.vue
  packages/nc-gui/components/dashboard/settings/base/Snapshots.vue
  packages/nc-gui/components/dashboard/settings/base/Visibility.vue
  packages/nc-gui/components/dashboard/settings/base/index.vue
  packages/nc-gui/components/general/AddBaseButton.vue
  packages/nc-gui/components/project/View.vue
  packages/nc-gui/composables/useBetaFeatureToggle.ts
  packages/nc-gui/context/index.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/lib/acl.ts
  packages/nc-gui/pages/index.vue
  packages/nc-gui/pages/index/[typeOrId]/[baseId].vue
  packages/nc-gui/store/config.ts
  packages/nocodb/src/interface/Jobs.ts
  packages/nocodb/src/meta/meta.service.ts
  packages/nocodb/src/models/Comment.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/bases.service.ts
  packages/nocodb/src/utils/globals.ts
  tests/playwright/pages/Dashboard/ProjectView/Settings.ts
  tests/playwright/pages/Dashboard/ProjectView/index.ts
  tests/playwright/pages/Dashboard/Settings/Miscellaneous.ts
  tests/playwright/pages/Dashboard/Settings/index.ts
  tests/playwright/tests/db/features/erd.spec.ts
  tests/playwright/tests/db/features/filters.spec.ts
Labels: 🔦 Type: Feature, size:XL, lgtm

#9915 fix: disable endDate for created-at, updated-at, formula
  packages/nc-gui/components/dlg/ViewCreate.vue
  packages/nc-gui/components/smartsheet/toolbar/Calendar/Range.vue
Labels: 🐛 Type: Bug, size:L, lgtm

#9914 Nc docs/extension
  packages/noco-docs/docs/.135.extensions/010.overview.md
  packages/noco-docs/docs/.135.extensions/020.data-exporter.md
  packages/noco-docs/docs/.135.extensions/030.upload-data-from-csv.md
  packages/noco-docs/docs/.135.extensions/040.bulk-update.md
  packages/noco-docs/docs/.135.extensions/050.url-preview.md
  packages/noco-docs/docs/.135.extensions/060.world-clock.md
  packages/noco-docs/docs/.135.extensions/070.org-chart.md
  packages/noco-docs/docs/.135.extensions/_category_.json
  packages/noco-docs/docs/160.developer-resources/.030.extensions/010.developing-extensions.md
  packages/noco-docs/docs/160.developer-resources/.030.extensions/_category_.json
  packages/noco-docs/static/img/v2/extensions/add-extension-1.png
  packages/noco-docs/static/img/v2/extensions/add-extension-2.png
  packages/noco-docs/static/img/v2/extensions/bulk-update-2.png
  packages/noco-docs/static/img/v2/extensions/bulk-update.png
  packages/noco-docs/static/img/v2/extensions/data-exporter.png
  packages/noco-docs/static/img/v2/extensions/expand.png
  packages/noco-docs/static/img/v2/extensions/extensions-side-panel.png
  packages/noco-docs/static/img/v2/extensions/more-actions.png
  packages/noco-docs/static/img/v2/extensions/reorder.png
  packages/noco-docs/static/img/v2/extensions/upload-csv.png
  packages/noco-docs/static/img/v2/extensions/url-preview.png
Labels: 📋 Scope : Docs, size:L, lgtm

#9886 docs: snapshot
  packages/noco-docs/docs/040.bases/065.snapshots.md
  packages/noco-docs/static/img/v2/base/snapshot-access.png
  packages/noco-docs/static/img/v2/base/snapshot-create-1.png
  packages/noco-docs/static/img/v2/base/snapshot-create-2.png
  packages/noco-docs/static/img/v2/base/snapshot-restore-1.png
  packages/noco-docs/static/img/v2/base/snapshot-restore-2.png
Labels: 📋 Scope : Docs, size:M, lgtm

#9920 fix: enable snapshots
  packages/nc-gui/components/dashboard/settings/base/index.vue
  packages/nc-gui/composables/useBetaFeatureToggle.ts
Labels: 🐛 Type: Bug, size:S, lgtm

#9053 fix: consider `NC_S3_ENDPOINT` besides `NC_S3_REGION`
  packages/noco-docs/docs/020.getting-started/050.self-hosted/020.environment-variables.md
  packages/nocodb/src/helpers/NcPluginMgrv2.ts
Labels: 🐛 Type: Bug, size:XS, lgtm

#9923 fix(nc-gui): decimal cell thousands separator display issue
  packages/nc-gui/components/cell/Decimal.vue
Labels: 🐛 Type: Bug, size:XS, lgtm

#9926 chore(docker): pin postgresql to 16.6
  docker-compose/1_Auto_Upstall/noco.sh
  docker-compose/2_pg/docker-compose.yml
Labels: 🐘 DB : Postgres, size:XS, lgtm
