Repository nocodb/nocodb, pull requests merged in 2025-01, with the labels that each got.

#9871 Nc feat/custom url support for shared view
  packages/nc-gui/assets/style.scss
  packages/nc-gui/components/dlg/share-and-collaborate/CustomUrl.vue
  packages/nc-gui/components/dlg/share-and-collaborate/ShareBase.vue
  packages/nc-gui/components/dlg/share-and-collaborate/SharePage.vue
  packages/nc-gui/components/general/CopyUrl.vue
  packages/nc-gui/components/general/IconSelector.vue
  packages/nc-gui/components/smartsheet/Form.vue
  packages/nc-gui/composables/useSharedView.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/layouts/shared-view.vue
  packages/nc-gui/middleware/03.redirect.global.ts
  packages/nc-gui/pages/index/[typeOrId]/calendar/[viewId]/index.vue
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId].vue
  packages/nc-gui/pages/index/[typeOrId]/form/[viewId]/index.vue
  packages/nc-gui/pages/index/[typeOrId]/gallery/[viewId]/index.vue
  packages/nc-gui/pages/index/[typeOrId]/kanban/[viewId]/index.vue
  packages/nc-gui/pages/index/[typeOrId]/map/[viewId]/index.vue
  packages/nc-gui/pages/index/[typeOrId]/view/[viewId].vue
  packages/nc-gui/windi.config.ts
  packages/noco-docs/docs/040.bases/060.share-base.md
  packages/noco-docs/docs/090.views/025.share-view.md
  packages/noco-docs/static/img/v2/base/customURL.png
  packages/noco-docs/static/img/v2/views/share-view/customURL.png
  packages/nocodb/src/controllers/shared-bases.controller.ts
  packages/nocodb/src/controllers/views.controller.ts
  packages/nocodb/src/models/Base.ts
  packages/nocodb/src/models/View.ts
  packages/nocodb/src/models/index.ts
  packages/nocodb/src/schema/swagger-v2.json
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/shared-bases.service.ts
  packages/nocodb/src/services/views.service.ts
  packages/nocodb/src/utils/globals.ts
Labels: 🔦 Type: Feature, 🚥 Status: On Hold, size:XL

#9966 test(extension-marketplace): marketplace test funcs
  packages/nc-gui/nuxt.config.ts
  packages/nocodb-sdk/src/lib/Api.ts
  tests/playwright/disabledTests/docs/tabs.spec.ts
  tests/playwright/fixtures/template.spec.ts
  tests/playwright/pages/Dashboard/ExpandedForm/index.ts
  tests/playwright/pages/Dashboard/Extensions/index.ts
  tests/playwright/pages/Dashboard/Import/ImportTemplate.ts
  tests/playwright/pages/Dashboard/TreeView.ts
  tests/playwright/pages/Dashboard/index.ts
  tests/playwright/pages/ProjectsPage/index.ts
  tests/playwright/tests/db/columns/columnBarcode.spec.ts
  tests/playwright/tests/db/columns/columnCheckbox.spec.ts
  tests/playwright/tests/db/columns/columnFormula.spec.ts
  tests/playwright/tests/db/columns/columnGeoData.spec.ts
  tests/playwright/tests/db/columns/columnLinkToAnotherRecord.spec.ts
  tests/playwright/tests/db/columns/columnLinkToAnotherRecordAdvanceOptions.spec.ts
  tests/playwright/tests/db/columns/columnLookupRollup.spec.ts
  tests/playwright/tests/db/columns/columnMenuOperations.spec.ts
  tests/playwright/tests/db/columns/columnQrCode.spec.ts
  tests/playwright/tests/db/columns/columnRating.spec.ts
  tests/playwright/tests/db/columns/columnRelationalExtendedTests.spec.ts
  tests/playwright/tests/db/features/baseShare.spec.ts
  tests/playwright/tests/db/features/expandedFormUrl.spec.ts
  tests/playwright/tests/db/features/filters.spec.ts
  tests/playwright/tests/db/features/findRowByScanner.spec.ts
  tests/playwright/tests/db/features/keyboardShortcuts.spec.ts
  tests/playwright/tests/db/features/pagination.spec.ts
  tests/playwright/tests/db/features/undo-redo.spec.ts
  tests/playwright/tests/db/features/webhook.spec.ts
  tests/playwright/tests/db/general/toolbarOperations.spec.ts
  tests/playwright/tests/db/general/viewMenu.spec.ts
  tests/playwright/tests/db/usersAccounts/rolesCreate.spec.ts
  tests/playwright/tests/db/usersAccounts/rolesPreview.spec.ts
  tests/playwright/tests/db/usersAccounts/rolesSuperUser.spec.ts
  tests/playwright/tests/db/views/viewForm.spec.ts
  tests/playwright/tests/db/views/viewFormShareSurvey.spec.ts
  tests/playwright/tests/db/views/viewGridShare.spec.ts
  tests/playwright/tests/db/views/viewKanban.spec.ts
  tests/playwright/tests/db/views/viewMap.spec.ts
Labels: Scope : Test [E2E], size:L

#10316 Nc nc fix/kanban order
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
Labels: 🛑 Status: Do Not Merge
