Repository nocodb/nocodb, pull requests merged in 2025-05, with the labels that each got.

#11327 Nc fix/checkbox issue
  packages/nc-gui/components/project/View.vue
  packages/nc-gui/components/smartsheet/Kanban.vue
  packages/nc-gui/components/smartsheet/toolbar/ColumnFilterMenu.vue
  packages/nc-gui/components/tabs/Smartsheet.vue
  packages/nc-gui/composables/useColumnFilteredOrSorted.ts
  packages/nc-gui/composables/useSmartsheetStore.ts
  packages/nocodb-sdk/src/lib/columnHelper/utils/url.ts
  packages/nocodb/src/db/field-handler/index.ts
Labels: 🛑 Status: Do Not Merge

#9686 Fea: new date formates 9652
  packages/noco-docs/docs/070.fields/040.field-types/070.date-time-based/010.date-time.md
  packages/noco-docs/docs/070.fields/040.field-types/070.date-time-based/020.date.md
  packages/nocodb-sdk/src/lib/dateTimeHelper.ts
  packages/nocodb/src/helpers/convertDateFormat.ts
Labels: 🔦 Type: Feature, size:S

#11422 Nc sync/cross base link
  packages/nc-gui/components/dlg/Table/Duplicate.vue
  packages/nc-gui/components/smartsheet/column/LinkedToAnotherRecordOptions.vue
  packages/nc-gui/components/smartsheet/column/RollupOptions.vue
  packages/nc-gui/components/smartsheet/expanded-form/index.vue
  packages/nc-gui/components/smartsheet/grid/canvas/cells/LTAR/index.ts
  packages/nc-gui/components/smartsheet/grid/canvas/cells/index.ts
  packages/nc-gui/components/smartsheet/grid/canvas/composables/useCanvasTable.ts
  packages/nc-gui/components/smartsheet/grid/canvas/index.vue
  packages/nc-gui/components/smartsheet/grid/canvas/loaders/BaseRoleLoader.ts
  packages/nc-gui/components/smartsheet/header/ColumnMenu.vue
  packages/nc-gui/components/virtual-cell/components/ItemChip.vue
  packages/nc-gui/components/virtual-cell/components/LinkedItems.vue
  packages/nc-gui/components/virtual-cell/components/ListItem.vue
  packages/nc-gui/components/virtual-cell/components/UnLinkedItems.vue
  packages/nc-gui/composables/useBetaFeatureToggle.ts
  packages/nc-gui/composables/useData.ts
  packages/nc-gui/composables/useExpandedFormStore.ts
  packages/nc-gui/composables/useGridViewData.ts
  packages/nc-gui/composables/useInfiniteData.ts
  packages/nc-gui/composables/useKanbanViewStore.ts
  packages/nc-gui/composables/useLTARStore.ts
  packages/nc-gui/composables/useMapViewDataStore.ts
  packages/nc-gui/composables/useMetas.ts
  packages/nc-gui/composables/useRoles/index.ts
  packages/nc-gui/composables/useSmartsheetLtarHelpers.ts
  packages/nc-gui/composables/useViewData.ts
  packages/nc-gui/lang/en.json
  packages/nc-gui/lib/types.ts
  packages/nc-gui/store/bases.ts
  packages/nocodb-sdk/src/lib/helperFunctions.ts
  packages/nocodb/src/db/BaseModelSqlv2.ts
  packages/nocodb/src/db/BaseModelSqlv2/add-remove-links.ts
  packages/nocodb/src/db/BaseModelSqlv2/relation-data-fetcher.ts
  packages/nocodb/src/db/BaseModelSqlv2/select-object.ts
  packages/nocodb/src/db/field-handler/handlers/lookup/lookup.general.handler.ts
  packages/nocodb/src/db/field-handler/handlers/ltar/ltar.general.handler.ts
  packages/nocodb/src/db/field-handler/utils/handlerUtils.ts
  packages/nocodb/src/db/formulav2/lookup-or-ltar-builder.ts
  packages/nocodb/src/db/genRollupSelectv2.ts
  packages/nocodb/src/db/generateLookupSelectQuery.ts
  packages/nocodb/src/db/relation-manager.ts
  packages/nocodb/src/db/relation-update-webhook-handler.ts
  packages/nocodb/src/helpers/catchError.ts
  packages/nocodb/src/helpers/columnHelpers.ts
  packages/nocodb/src/helpers/dataHelpers.ts
  packages/nocodb/src/helpers/dbHelpers.ts
  packages/nocodb/src/helpers/getAst.ts
  packages/nocodb/src/helpers/populateSamplePayload.ts
  packages/nocodb/src/meta/migrations/XcMigrationSourcev2.ts
  packages/nocodb/src/meta/migrations/v2/nc_079_cross_base_link.ts
  packages/nocodb/src/models/Column.ts
  packages/nocodb/src/models/LinkToAnotherRecordColumn.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/export.service.ts
  packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts
  packages/nocodb/src/schema/swagger.json
  packages/nocodb/src/services/columns.service.ts
  packages/nocodb/src/services/data-table.service.ts
  packages/nocodb/src/services/tables.service.ts
  packages/nocodb/src/utils/acl.ts
Labels: trigger-CI
