Repository nocodb/nocodb, pull requests merged in 2025-02, with the labels that each got.

#10434 fix internationalization
  packages/nocodb-sdk/src/lib/parser/common-token.ts
  packages/nocodb-sdk/src/lib/parser/queryFilter/query-filter-parser.spec.ts
  packages/nocodb-sdk/src/lib/regex/token.ts
Labels: trigger-CI

#10436 fix: Add whitespace support in where query param parser
  packages/nocodb-sdk/src/lib/parser/common-token.ts
  packages/nocodb-sdk/src/lib/regex/token.ts
Labels: trigger-CI

#10470 revert[06bb1aa]: Remove promotion of aaPanel/BaoTa.
  markdown/readme/languages/chinese.md
Labels: 📋 Scope : Docs

#9796 Update 030.expand-record.md
  packages/noco-docs/docs/080.records/030.expand-record.md
Labels: 📋 Scope : Docs, size:XS

#9977 fix: Prevent sum from failing if field is blank
  packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts
Labels: 🐛 Type: Bug, size:S

#10676 Nc feat/linked fields page designer
  packages/nc-gui/assets/nc-icons-v2/unlock.svg
  packages/nc-gui/assets/nc-icons/image-placeholder.svg
  packages/nc-gui/components/ai/PromptWithFields.vue
  packages/nc-gui/components/extensions/Extension.vue
  packages/nc-gui/components/extensions/Extension/Header.vue
  packages/nc-gui/components/n/RecordPicker/Item.vue
  packages/nc-gui/components/n/RecordPicker/index.vue
  packages/nc-gui/components/virtual-cell/Lookup.vue
  packages/nc-gui/composables/useLTARStore.ts
  packages/nc-gui/context/index.ts
  packages/nc-gui/nuxt.config.ts
  packages/nc-gui/utils/iconUtils.ts
Labels: 🛑 Status: Do Not Merge
